// GENERATED by tools/gen-builtins.mjs from spec/builtins.json — do not edit; edit the manifest and regenerate.
//
// One frozen record per builtin: min, max (Infinity when variadic), lazy,
// binds, and the extra arity rule ({ parity, message } or { allowed, message })
// or null. registry.mjs checks every define() against it.

export const BUILTIN_MANIFEST = Object.freeze({
  ABORT: { min: 1, max: 1, lazy: false, binds: false, arity: null },
  ABS: { min: 1, max: 1, lazy: false, binds: false, arity: null },
  ALL: { min: 2, max: 3, lazy: true, binds: true, arity: null },
  ANY: { min: 2, max: 3, lazy: true, binds: true, arity: null },
  BACKWARDS: { min: 1, max: 1, lazy: false, binds: false, arity: null },
  BLEN: { min: 1, max: 1, lazy: false, binds: false, arity: null },
  BTL: { min: 1, max: 1, lazy: false, binds: false, arity: null },
  BUCKET: { min: 2, max: 4, lazy: true, binds: true, arity: null },
  CANON: { min: 1, max: 1, lazy: false, binds: false, arity: null },
  CEIL: { min: 1, max: 1, lazy: false, binds: false, arity: null },
  CHAR: { min: 1, max: 1, lazy: false, binds: false, arity: null },
  COALESCE: { min: 1, max: Infinity, lazy: true, binds: false, arity: null },
  CODE: { min: 1, max: 1, lazy: false, binds: false, arity: null },
  COND: { min: 3, max: Infinity, lazy: true, binds: false, arity: { parity: "odd", message: "COND takes condition/result pairs and a final default (an odd number of arguments), got {count}" } },
  COUNT: { min: 1, max: 1, lazy: false, binds: false, arity: null },
  CRC32: { min: 1, max: 1, lazy: false, binds: false, arity: null },
  DECODE_BASE64: { min: 1, max: 1, lazy: false, binds: false, arity: null },
  DEDUPE: { min: 1, max: 1, lazy: false, binds: false, arity: null },
  DISTINCT: { min: 1, max: 1, lazy: false, binds: false, arity: null },
  DROP: { min: 2, max: 2, lazy: false, binds: false, arity: null },
  ENCODE_BASE64: { min: 1, max: 1, lazy: false, binds: false, arity: null },
  FILTER: { min: 2, max: 3, lazy: true, binds: true, arity: null },
  FIND: { min: 2, max: 3, lazy: false, binds: false, arity: null },
  FLOOR: { min: 1, max: 1, lazy: false, binds: false, arity: null },
  FROM_HEX: { min: 1, max: 1, lazy: false, binds: false, arity: null },
  FROM_UTF8: { min: 1, max: 1, lazy: false, binds: false, arity: null },
  GET: { min: 2, max: 3, lazy: true, binds: false, arity: null },
  HAS: { min: 2, max: 2, lazy: false, binds: false, arity: null },
  IF: { min: 2, max: 3, lazy: true, binds: false, arity: null },
  INDEXES: { min: 1, max: 1, lazy: false, binds: false, arity: null },
  ISNUM: { min: 1, max: 1, lazy: false, binds: false, arity: null },
  IS_BLANK: { min: 1, max: 1, lazy: false, binds: false, arity: null },
  IS_NOT_NULL: { min: 1, max: 1, lazy: false, binds: false, arity: null },
  IS_NULL: { min: 1, max: 1, lazy: false, binds: false, arity: null },
  IS_PRESENT: { min: 1, max: 1, lazy: false, binds: false, arity: null },
  JOIN: { min: 2, max: 2, lazy: false, binds: false, arity: null },
  LEFT: { min: 2, max: 2, lazy: false, binds: false, arity: null },
  LEN: { min: 1, max: 1, lazy: false, binds: false, arity: null },
  LINK: { min: 3, max: 5, lazy: true, binds: true, arity: { allowed: [3, 5], message: "LINK takes 3 or 5 arguments, got {count}" } },
  LINK_LEFT: { min: 3, max: 5, lazy: true, binds: true, arity: { allowed: [3, 5], message: "LINK_LEFT takes 3 or 5 arguments, got {count}" } },
  LIST: { min: 0, max: Infinity, lazy: false, binds: false, arity: null },
  LOWER: { min: 1, max: 1, lazy: false, binds: false, arity: null },
  LTB: { min: 1, max: 1, lazy: false, binds: false, arity: null },
  LTRIM: { min: 1, max: 1, lazy: false, binds: false, arity: null },
  MAP: { min: 2, max: 3, lazy: true, binds: true, arity: null },
  MAX: { min: 1, max: Infinity, lazy: false, binds: false, arity: null },
  MIN: { min: 1, max: Infinity, lazy: false, binds: false, arity: null },
  PADL: { min: 3, max: 3, lazy: false, binds: false, arity: null },
  PADR: { min: 3, max: 3, lazy: false, binds: false, arity: null },
  PATH: { min: 2, max: 3, lazy: true, binds: false, arity: null },
  POWER: { min: 2, max: 2, lazy: false, binds: false, arity: null },
  RECORD: { min: 0, max: Infinity, lazy: false, binds: false, arity: { parity: "even", message: "RECORD takes an even number of arguments (key-value pairs), got {count}" } },
  REPEAT: { min: 2, max: 2, lazy: false, binds: false, arity: null },
  REPLACE: { min: 3, max: 3, lazy: false, binds: false, arity: null },
  RFIND: { min: 2, max: 3, lazy: false, binds: false, arity: null },
  RGROUPS: { min: 2, max: 3, lazy: false, binds: false, arity: null },
  RIGHT: { min: 2, max: 2, lazy: false, binds: false, arity: null },
  RMATCH: { min: 2, max: 3, lazy: false, binds: false, arity: null },
  ROUND: { min: 2, max: 2, lazy: false, binds: false, arity: null },
  RREPLACE: { min: 3, max: 4, lazy: false, binds: false, arity: null },
  RTRIM: { min: 1, max: 1, lazy: false, binds: false, arity: null },
  SELECT_COLS: { min: 2, max: Infinity, lazy: false, binds: false, arity: null },
  SIGN: { min: 1, max: 1, lazy: false, binds: false, arity: null },
  SORT: { min: 1, max: 3, lazy: true, binds: true, arity: null },
  SORT_BY: { min: 2, max: 4, lazy: true, binds: true, arity: null },
  SORT_DESC: { min: 1, max: 3, lazy: true, binds: true, arity: null },
  SPLIT: { min: 2, max: 2, lazy: false, binds: false, arity: null },
  SUBSTR: { min: 2, max: 3, lazy: false, binds: false, arity: null },
  SUM: { min: 2, max: 3, lazy: true, binds: true, arity: null },
  TAKE: { min: 2, max: 2, lazy: false, binds: false, arity: null },
  TOP: { min: 2, max: 4, lazy: true, binds: true, arity: null },
  TOP_BY: { min: 3, max: 5, lazy: true, binds: true, arity: null },
  TOP_DESC: { min: 2, max: 4, lazy: true, binds: true, arity: null },
  TO_HEX: { min: 1, max: 1, lazy: false, binds: false, arity: null },
  TO_UTF8: { min: 1, max: 1, lazy: false, binds: false, arity: null },
  TRIM: { min: 1, max: 1, lazy: false, binds: false, arity: null },
  TRUNC: { min: 1, max: 1, lazy: false, binds: false, arity: null },
  UPPER: { min: 1, max: 1, lazy: false, binds: false, arity: null },
});

// The binding forms (spec/builtins.md): per accepted count, in the order the
// evaluator tries them, each argument's scope (outer | binder | inner), an
// optional guard { arg, is: 'name' | 'text' } and the implicit names bound
// inside. registry.mjs turns these into bindingForm().
export const BINDING_FORMS = Object.freeze({
  ALL: [
    { scopes: ["outer", "inner"], when: null, binds: ["_", "_K"] },
    { scopes: ["outer", "binder", "inner"], when: null, binds: ["_K"] },
  ],
  ANY: [
    { scopes: ["outer", "inner"], when: null, binds: ["_", "_K"] },
    { scopes: ["outer", "binder", "inner"], when: null, binds: ["_K"] },
  ],
  BUCKET: [
    { scopes: ["outer", "inner"], when: null, binds: ["_", "_K"] },
    { scopes: ["outer", "inner", "inner"], when: null, binds: ["_", "_K"] },
    { scopes: ["outer", "binder", "inner", "inner"], when: null, binds: ["_K"] },
  ],
  FILTER: [
    { scopes: ["outer", "inner"], when: null, binds: ["_", "_K"] },
    { scopes: ["outer", "binder", "inner"], when: null, binds: ["_K"] },
  ],
  LINK: [
    { scopes: ["outer", "outer", "inner"], when: null, binds: ["_", "_1", "_2", "_K"] },
    { scopes: ["outer", "outer", "binder", "binder", "inner"], when: null, binds: ["_", "_1", "_2", "_K"] },
  ],
  LINK_LEFT: [
    { scopes: ["outer", "outer", "inner"], when: null, binds: ["_", "_1", "_2", "_K"] },
    { scopes: ["outer", "outer", "binder", "binder", "inner"], when: null, binds: ["_", "_1", "_2", "_K"] },
  ],
  MAP: [
    { scopes: ["outer", "inner"], when: null, binds: ["_", "_K"] },
    { scopes: ["outer", "binder", "inner"], when: null, binds: ["_K"] },
  ],
  SORT: [
    { scopes: ["outer"], when: null, binds: ["_", "_K"] },
    { scopes: ["outer", "inner"], when: null, binds: ["_", "_K"] },
    { scopes: ["outer", "binder", "inner"], when: null, binds: ["_K"] },
  ],
  SORT_BY: [
    { scopes: ["outer", "inner"], when: null, binds: ["_", "_K"] },
    { scopes: ["outer", "inner", "outer"], when: { arg: 2, is: "text" }, binds: ["_", "_K"] },
    { scopes: ["outer", "binder", "inner"], when: { arg: 1, is: "name" }, binds: ["_K"] },
    { scopes: ["outer", "inner", "outer"], when: null, binds: ["_", "_K"] },
    { scopes: ["outer", "binder", "inner", "outer"], when: null, binds: ["_K"] },
  ],
  SORT_DESC: [
    { scopes: ["outer"], when: null, binds: ["_", "_K"] },
    { scopes: ["outer", "inner"], when: null, binds: ["_", "_K"] },
    { scopes: ["outer", "binder", "inner"], when: null, binds: ["_K"] },
  ],
  SUM: [
    { scopes: ["outer", "inner"], when: null, binds: ["_", "_K"] },
    { scopes: ["outer", "binder", "inner"], when: null, binds: ["_K"] },
  ],
  TOP: [
    { scopes: ["outer", "outer"], when: null, binds: ["_", "_K"] },
    { scopes: ["outer", "inner", "outer"], when: null, binds: ["_", "_K"] },
    { scopes: ["outer", "binder", "inner", "outer"], when: null, binds: ["_K"] },
  ],
  TOP_BY: [
    { scopes: ["outer", "inner", "outer"], when: null, binds: ["_", "_K"] },
    { scopes: ["outer", "inner", "outer", "outer"], when: { arg: 2, is: "text" }, binds: ["_", "_K"] },
    { scopes: ["outer", "binder", "inner", "outer"], when: { arg: 1, is: "name" }, binds: ["_K"] },
    { scopes: ["outer", "inner", "outer", "outer"], when: null, binds: ["_", "_K"] },
    { scopes: ["outer", "binder", "inner", "outer", "outer"], when: null, binds: ["_K"] },
  ],
  TOP_DESC: [
    { scopes: ["outer", "outer"], when: null, binds: ["_", "_K"] },
    { scopes: ["outer", "inner", "outer"], when: null, binds: ["_", "_K"] },
    { scopes: ["outer", "binder", "inner", "outer"], when: null, binds: ["_K"] },
  ],
});

// Classification (spec/builtins.md): the pipeline steps (whether each keeps
// its rows as they are, and whether it sorts), where each regex builtin takes
// its pattern and its flags, how the SQL translators type a builtin's
// arguments (numeric positions; whether a BIN or a BOOL argument is accepted),
// and the builtins whose result is a list. Hosts classify through these
// rather than keeping lists of their own.
export const PIPELINE_STEPS = Object.freeze({
  BUCKET: Object.freeze({ keepsRows: false, sorts: false }),
  DEDUPE: Object.freeze({ keepsRows: true, sorts: false }),
  DISTINCT: Object.freeze({ keepsRows: true, sorts: false }),
  DROP: Object.freeze({ keepsRows: true, sorts: false }),
  FILTER: Object.freeze({ keepsRows: true, sorts: false }),
  LINK: Object.freeze({ keepsRows: false, sorts: false }),
  LINK_LEFT: Object.freeze({ keepsRows: false, sorts: false }),
  MAP: Object.freeze({ keepsRows: false, sorts: false }),
  SELECT_COLS: Object.freeze({ keepsRows: false, sorts: false }),
  SORT: Object.freeze({ keepsRows: true, sorts: true }),
  SORT_BY: Object.freeze({ keepsRows: true, sorts: true }),
  SORT_DESC: Object.freeze({ keepsRows: true, sorts: true }),
  TAKE: Object.freeze({ keepsRows: true, sorts: false }),
  TOP: Object.freeze({ keepsRows: true, sorts: true }),
  TOP_BY: Object.freeze({ keepsRows: true, sorts: true }),
  TOP_DESC: Object.freeze({ keepsRows: true, sorts: true }),
});

export const REGEX_CALLS = Object.freeze({
  RFIND: Object.freeze({ pattern: 0, flags: 2 }),
  RGROUPS: Object.freeze({ pattern: 0, flags: 2 }),
  RMATCH: Object.freeze({ pattern: 0, flags: 2 }),
  RREPLACE: Object.freeze({ pattern: 0, flags: 3 }),
});

export const SQL_ARGS = Object.freeze({
  ABS: Object.freeze({ numeric: Object.freeze([0]), bin: false, bool: false }),
  BLEN: Object.freeze({ numeric: null, bin: true, bool: false }),
  CANON: Object.freeze({ numeric: Object.freeze([0]), bin: false, bool: false }),
  CEIL: Object.freeze({ numeric: Object.freeze([0]), bin: false, bool: false }),
  CHAR: Object.freeze({ numeric: Object.freeze([0]), bin: false, bool: false }),
  CRC32: Object.freeze({ numeric: null, bin: true, bool: false }),
  ENCODE_BASE64: Object.freeze({ numeric: null, bin: true, bool: false }),
  FIND: Object.freeze({ numeric: Object.freeze([2]), bin: false, bool: false }),
  FLOOR: Object.freeze({ numeric: Object.freeze([0]), bin: false, bool: false }),
  FROM_UTF8: Object.freeze({ numeric: null, bin: true, bool: false }),
  ISNUM: Object.freeze({ numeric: null, bin: true, bool: true }),
  LEFT: Object.freeze({ numeric: Object.freeze([1]), bin: false, bool: false }),
  MAX: Object.freeze({ numeric: 'all', bin: false, bool: false }),
  MIN: Object.freeze({ numeric: 'all', bin: false, bool: false }),
  PADL: Object.freeze({ numeric: Object.freeze([1]), bin: false, bool: false }),
  PADR: Object.freeze({ numeric: Object.freeze([1]), bin: false, bool: false }),
  POWER: Object.freeze({ numeric: Object.freeze([0, 1]), bin: false, bool: false }),
  REPEAT: Object.freeze({ numeric: Object.freeze([1]), bin: false, bool: false }),
  RIGHT: Object.freeze({ numeric: Object.freeze([1]), bin: false, bool: false }),
  ROUND: Object.freeze({ numeric: Object.freeze([0, 1]), bin: false, bool: false }),
  SIGN: Object.freeze({ numeric: Object.freeze([0]), bin: false, bool: false }),
  SUBSTR: Object.freeze({ numeric: Object.freeze([1, 2]), bin: false, bool: false }),
  TO_HEX: Object.freeze({ numeric: null, bin: true, bool: false }),
  TO_UTF8: Object.freeze({ numeric: null, bin: true, bool: false }),
  TRUNC: Object.freeze({ numeric: Object.freeze([0]), bin: false, bool: false }),
});

export const YIELDS_LIST = Object.freeze(new Set(["BTL", "BUCKET", "DEDUPE", "DISTINCT", "DROP", "FILTER", "INDEXES", "LINK", "LINK_LEFT", "LIST", "MAP", "RECORD", "RGROUPS", "SELECT_COLS", "SORT", "SORT_BY", "SORT_DESC", "SPLIT", "TAKE", "TOP", "TOP_BY", "TOP_DESC"]));
