// GENERATED by tools/gen-math-ops.mjs from spec/math-ops.json — do not edit; edit the manifest and regenerate.
//
// What the math plan compiles: MATH_OPERATORS maps a binary operator token and
// MATH_PREFIX a prefix operator name to a symbolic operation; MATH_BUILTINS
// maps a builtin name to { op, arity (1 | 2 | 'fold'), aux }. MATH_OPS lists
// every operation; math_plan.mjs maps each to its own opcode and refuses to
// load if one is missing.

export const MATH_OPERATORS = Object.freeze({
  "+": "ADD",
  "-": "SUB",
  "*": "MUL",
  "/": "DIV",
  "%": "MOD",
});

export const MATH_PREFIX = Object.freeze({
  "NEG": "NEG",
});

export const MATH_BUILTINS = Object.freeze({
  "ABS": { op: "ABS", arity: 1, aux: null },
  "SIGN": { op: "SIGN", arity: 1, aux: null },
  "CEIL": { op: "CEIL", arity: 1, aux: null },
  "FLOOR": { op: "FLOOR", arity: 1, aux: null },
  "TRUNC": { op: "TRUNC", arity: 1, aux: null },
  "ROUND": { op: "ROUND", arity: 2, aux: 1 },
  "POWER": { op: "POWER", arity: 2, aux: 1 },
  "MIN": { op: "MIN", arity: "fold", aux: null },
  "MAX": { op: "MAX", arity: "fold", aux: null },
});

export const MATH_OPS = Object.freeze(["ADD", "SUB", "MUL", "DIV", "MOD", "NEG", "ABS", "SIGN", "CEIL", "FLOOR", "TRUNC", "ROUND", "POWER", "MIN", "MAX"]);
