-- The entity-attribute-value catalogue of examples/sql-eav, for SQLite. Loaded by tools/check-usage.sh.
DROP TABLE IF EXISTS attributes;
DROP TABLE IF EXISTS entities;
CREATE TABLE entities (id INTEGER PRIMARY KEY, sku TEXT NOT NULL, kind TEXT NOT NULL);
CREATE TABLE attributes (entity_id INTEGER NOT NULL REFERENCES entities, name TEXT NOT NULL, value TEXT NOT NULL, PRIMARY KEY (entity_id, name));
INSERT INTO entities VALUES
  (1, 'LMP-01', 'lamp'),
  (2, 'LMP-02', 'lamp'),
  (3, 'CHR-01', 'chair'),
  (4, 'CHR-02', 'chair'),
  (5, 'TBL-01', 'table'),
  (6, 'TBL-02', 'table'),
  (7, 'LMP-03', 'lamp'),
  (8, 'SHF-01', 'shelf'),
  (9, 'SHF-02', 'shelf'),
  (10, 'CHR-03', 'chair');
INSERT INTO attributes VALUES
  (1, 'color', 'red'),
  (1, 'material', 'steel'),
  (1, 'price', '49.90'),
  (1, 'watts', '40'),
  (2, 'color', 'white'),
  (2, 'material', 'glass'),
  (2, 'price', '89.00'),
  (2, 'watts', '60'),
  (3, 'color', 'red'),
  (3, 'material', 'oak'),
  (3, 'price', '129.00'),
  (4, 'color', 'blue'),
  (4, 'material', 'steel'),
  (4, 'price', '74.50'),
  (4, 'stackable', 'yes'),
  (5, 'color', 'natural'),
  (5, 'material', 'oak'),
  (5, 'price', '349.00'),
  (5, 'seats', '6'),
  (6, 'color', 'blue'),
  (6, 'material', 'steel'),
  (6, 'price', 'call us'),
  (6, 'seats', '4'),
  (7, 'color', 'blue'),
  (7, 'material', 'steel'),
  (7, 'price', '35.00'),
  (7, 'watts', '25'),
  (8, 'color', 'white'),
  (8, 'material', 'pine'),
  (8, 'price', '45.00'),
  (9, 'color', 'red'),
  (9, 'material', 'steel'),
  (9, 'price', '59.99'),
  (9, 'shelves', '5'),
  (10, 'color', 'Red'),
  (10, 'material', 'plastic'),
  (10, 'price', '19.99'),
  (10, 'stackable', 'yes');
