// GENERATED by tools/gen-math-ops.mjs from spec/math-ops.json — do not edit; edit the manifest and regenerate.
//
// What the math plan compiles: Operators maps a binary operator token and
// Prefix a prefix operator name to a symbolic operation; Builtins
// maps a builtin name to {Op, Arity, Aux}. Ops lists every
// operation; the optimizer maps each to its own native OpCode.

package mathops

type BuiltinSpec struct {
	Op    string
	Arity string // "1", "2" or "fold"
	Aux   int    // -1 if none
}

var Operators = map[string]string{
	"+": "ADD",
	"-": "SUB",
	"*": "MUL",
	"/": "DIV",
	"%": "MOD",
}

var Prefix = map[string]string{
	"NEG": "NEG",
}

var Builtins = map[string]BuiltinSpec{
	"ABS":   {Op: "ABS", Arity: "1", Aux: -1},
	"SIGN":  {Op: "SIGN", Arity: "1", Aux: -1},
	"CEIL":  {Op: "CEIL", Arity: "1", Aux: -1},
	"FLOOR": {Op: "FLOOR", Arity: "1", Aux: -1},
	"TRUNC": {Op: "TRUNC", Arity: "1", Aux: -1},
	"ROUND": {Op: "ROUND", Arity: "2", Aux: 1},
	"POWER": {Op: "POWER", Arity: "2", Aux: 1},
	"MIN":   {Op: "MIN", Arity: "fold", Aux: -1},
	"MAX":   {Op: "MAX", Arity: "fold", Aux: -1},
}

var Ops = []string{
	"ADD",
	"SUB",
	"MUL",
	"DIV",
	"MOD",
	"NEG",
	"ABS",
	"SIGN",
	"CEIL",
	"FLOOR",
	"TRUNC",
	"ROUND",
	"POWER",
	"MIN",
	"MAX",
}
