;;;; GENERATED by tools/gen-lexicon.mjs from spec/lexicon.json — do not edit; edit the lexicon and regenerate.
;;;;
;;;; *LEXICON-RESERVED*: the reserved words. *LEXICON-SYMBOLS*: every symbol
;;;; token, longest first. *LEXICON-BP*: (level . binding power), higher binds
;;;; tighter. *LEXICON-OPS*: one plist per operator, tightest level first; see
;;;; spec/lexicon.md for the fields. :relation is an index into eq ne lt le gt
;;;; ge (-1 when none); :assoc is #\L, #\R, #\N or NIL.

(in-package #:sel)

(defparameter *lexicon-reserved* '("TRUE" "FALSE" "NULL" "AND" "OR" "NOT" "XOR" "EQL" "IN" "BAND" "BOR" "BXOR"))

(defparameter *lexicon-symbols* '("???" "$==" "$!=" "$<=" "$>=" ".>" "??" "==" "!=" "<=" ">=" "$<" "$>" "+=" "-=" "*=" "/=" "%=" "&=" "[" "-" "*" "/" "%" "+" "&" "<" ">" "=" "," ";" "(" ")" "]"))

(defparameter *lexicon-bp*
  '(
    (:postfix . 17)
    (:neg . 16)
    (:mul . 15)
    (:add . 14)
    (:concat . 13)
    (:band . 12)
    (:bxor . 11)
    (:bor . 10)
    (:coalesce . 9)
    (:compare . 8)
    (:not . 7)
    (:and . 6)
    (:xor . 5)
    (:or . 4)
    (:assign . 3)
    (:list . 2)
    (:seq . 1)))

(defparameter *lexicon-ops*
  '(
    ("[" :word nil :fixity :postfix :level :postfix :bp 17 :assoc nil :family :postfix :node :index :name nil :relation -1 :compound nil :short-circuit nil)
    (".>" :word nil :fixity :postfix :level :postfix :bp 17 :assoc nil :family :postfix :node :pipe :name nil :relation -1 :compound nil :short-circuit nil)
    ("-" :word nil :fixity :prefix :level :neg :bp 16 :assoc nil :family :arith :node :un :name "NEG" :relation -1 :compound nil :short-circuit nil)
    ("*" :word nil :fixity :infix :level :mul :bp 15 :assoc #\L :family :arith :node :bin :name nil :relation -1 :compound nil :short-circuit nil)
    ("/" :word nil :fixity :infix :level :mul :bp 15 :assoc #\L :family :arith :node :bin :name nil :relation -1 :compound nil :short-circuit nil)
    ("%" :word nil :fixity :infix :level :mul :bp 15 :assoc #\L :family :arith :node :bin :name nil :relation -1 :compound nil :short-circuit nil)
    ("+" :word nil :fixity :infix :level :add :bp 14 :assoc #\L :family :arith :node :bin :name nil :relation -1 :compound nil :short-circuit nil)
    ("-" :word nil :fixity :infix :level :add :bp 14 :assoc #\L :family :arith :node :bin :name nil :relation -1 :compound nil :short-circuit nil)
    ("&" :word nil :fixity :infix :level :concat :bp 13 :assoc #\L :family :concat :node :bin :name nil :relation -1 :compound nil :short-circuit nil)
    ("BAND" :word t :fixity :infix :level :band :bp 12 :assoc #\L :family :bitwise :node :bin :name nil :relation -1 :compound nil :short-circuit nil)
    ("BXOR" :word t :fixity :infix :level :bxor :bp 11 :assoc #\L :family :bitwise :node :bin :name nil :relation -1 :compound nil :short-circuit nil)
    ("BOR" :word t :fixity :infix :level :bor :bp 10 :assoc #\L :family :bitwise :node :bin :name nil :relation -1 :compound nil :short-circuit nil)
    ("??" :word nil :fixity :infix :level :coalesce :bp 9 :assoc #\R :family :coalesce :node :bin :name nil :relation -1 :compound nil :short-circuit t)
    ("???" :word nil :fixity :infix :level :coalesce :bp 9 :assoc #\R :family :coalesce :node :bin :name nil :relation -1 :compound nil :short-circuit t)
    ("==" :word nil :fixity :infix :level :compare :bp 8 :assoc #\N :family :compare :node :bin :name nil :relation 0 :compound nil :short-circuit nil)
    ("!=" :word nil :fixity :infix :level :compare :bp 8 :assoc #\N :family :compare :node :bin :name nil :relation 1 :compound nil :short-circuit nil)
    ("<" :word nil :fixity :infix :level :compare :bp 8 :assoc #\N :family :compare :node :bin :name nil :relation 2 :compound nil :short-circuit nil)
    ("<=" :word nil :fixity :infix :level :compare :bp 8 :assoc #\N :family :compare :node :bin :name nil :relation 3 :compound nil :short-circuit nil)
    (">" :word nil :fixity :infix :level :compare :bp 8 :assoc #\N :family :compare :node :bin :name nil :relation 4 :compound nil :short-circuit nil)
    (">=" :word nil :fixity :infix :level :compare :bp 8 :assoc #\N :family :compare :node :bin :name nil :relation 5 :compound nil :short-circuit nil)
    ("$==" :word nil :fixity :infix :level :compare :bp 8 :assoc #\N :family :text-compare :node :bin :name nil :relation 0 :compound nil :short-circuit nil)
    ("$!=" :word nil :fixity :infix :level :compare :bp 8 :assoc #\N :family :text-compare :node :bin :name nil :relation 1 :compound nil :short-circuit nil)
    ("$<" :word nil :fixity :infix :level :compare :bp 8 :assoc #\N :family :text-compare :node :bin :name nil :relation 2 :compound nil :short-circuit nil)
    ("$<=" :word nil :fixity :infix :level :compare :bp 8 :assoc #\N :family :text-compare :node :bin :name nil :relation 3 :compound nil :short-circuit nil)
    ("$>" :word nil :fixity :infix :level :compare :bp 8 :assoc #\N :family :text-compare :node :bin :name nil :relation 4 :compound nil :short-circuit nil)
    ("$>=" :word nil :fixity :infix :level :compare :bp 8 :assoc #\N :family :text-compare :node :bin :name nil :relation 5 :compound nil :short-circuit nil)
    ("EQL" :word t :fixity :infix :level :compare :bp 8 :assoc #\N :family :deep-compare :node :bin :name nil :relation -1 :compound nil :short-circuit nil)
    ("IN" :word t :fixity :infix :level :compare :bp 8 :assoc #\N :family :deep-compare :node :bin :name nil :relation -1 :compound nil :short-circuit nil)
    ("NOT" :word t :fixity :prefix :level :not :bp 7 :assoc nil :family :logic :node :un :name "NOT" :relation -1 :compound nil :short-circuit nil)
    ("AND" :word t :fixity :infix :level :and :bp 6 :assoc #\L :family :logic :node :bin :name nil :relation -1 :compound nil :short-circuit t)
    ("XOR" :word t :fixity :infix :level :xor :bp 5 :assoc #\L :family :logic :node :bin :name nil :relation -1 :compound nil :short-circuit nil)
    ("OR" :word t :fixity :infix :level :or :bp 4 :assoc #\L :family :logic :node :bin :name nil :relation -1 :compound nil :short-circuit t)
    ("=" :word nil :fixity :infix :level :assign :bp 3 :assoc #\R :family :assign :node :assign :name nil :relation -1 :compound nil :short-circuit nil)
    ("+=" :word nil :fixity :infix :level :assign :bp 3 :assoc #\R :family :assign :node :assign :name nil :relation -1 :compound "+" :short-circuit nil)
    ("-=" :word nil :fixity :infix :level :assign :bp 3 :assoc #\R :family :assign :node :assign :name nil :relation -1 :compound "-" :short-circuit nil)
    ("*=" :word nil :fixity :infix :level :assign :bp 3 :assoc #\R :family :assign :node :assign :name nil :relation -1 :compound "*" :short-circuit nil)
    ("/=" :word nil :fixity :infix :level :assign :bp 3 :assoc #\R :family :assign :node :assign :name nil :relation -1 :compound "/" :short-circuit nil)
    ("%=" :word nil :fixity :infix :level :assign :bp 3 :assoc #\R :family :assign :node :assign :name nil :relation -1 :compound "%" :short-circuit nil)
    ("&=" :word nil :fixity :infix :level :assign :bp 3 :assoc #\R :family :assign :node :assign :name nil :relation -1 :compound "&" :short-circuit nil)
    ("," :word nil :fixity :infix :level :list :bp 2 :assoc #\L :family :list :node :list :name nil :relation -1 :compound nil :short-circuit nil)
    (";" :word nil :fixity :infix :level :seq :bp 1 :assoc #\L :family :sequence :node :seq :name nil :relation -1 :compound nil :short-circuit nil)))
