;;;; GENERATED by tools/gen-math-ops.mjs from spec/math-ops.json — do not edit; edit the manifest and regenerate.
;;;;
;;;; What the math plan compiles: one list per operation, (name kind token arity
;;;; aux) with kind :operator | :prefix | :builtin, arity 1 | 2 | :fold and aux
;;;; NIL or the auxiliary-position argument. math-plan.lisp maps each name to
;;;; its keyword and refuses to load if the executor lacks one.

(in-package #:sel)

(setf *math-op-data*
      '(
        ("ADD" :operator "+" 2 nil)
        ("SUB" :operator "-" 2 nil)
        ("MUL" :operator "*" 2 nil)
        ("DIV" :operator "/" 2 nil)
        ("MOD" :operator "%" 2 nil)
        ("NEG" :prefix "NEG" 1 nil)
        ("ABS" :builtin "ABS" 1 nil)
        ("SIGN" :builtin "SIGN" 1 nil)
        ("CEIL" :builtin "CEIL" 1 nil)
        ("FLOOR" :builtin "FLOOR" 1 nil)
        ("TRUNC" :builtin "TRUNC" 1 nil)
        ("ROUND" :builtin "ROUND" 2 1)
        ("POWER" :builtin "POWER" 2 1)
        ("MIN" :builtin "MIN" :fold nil)
        ("MAX" :builtin "MAX" :fold nil)))
