// GENERATED by tools/gen-lexicon.mjs from spec/lexicon.json — do not edit; edit the lexicon and regenerate.
//
// RESERVED: the reserved words. SYMBOLS: every symbol token, longest first.
// BP_<LEVEL>: each precedence level's binding power (higher binds tighter).
// OPS: one entry per operator, tightest level first; see spec/lexicon.md for
// the fields. infix_symbol / infix_word / prefix answer the parser's lookups
// with a match, so the table costs nothing per token.

#[derive(Clone, Copy, Debug, PartialEq, Eq)]
pub enum Fixity {
    Infix,
    Prefix,
    Postfix,
}

#[derive(Clone, Copy, Debug, PartialEq, Eq)]
pub enum Assoc {
    Left,
    Right,
    NonAssoc,
}

#[derive(Clone, Copy, Debug, PartialEq, Eq)]
pub enum Family {
    Arith,
    Concat,
    TextCompare,
    DeepCompare,
    Coalesce,
    Logic,
    Bitwise,
    Assign,
    Sequence,
    List,
    Compare,
    Postfix,
}

#[derive(Clone, Copy, Debug, PartialEq, Eq)]
pub enum Relation {
    Eq,
    Ne,
    Lt,
    Le,
    Gt,
    Ge,
}

#[derive(Clone, Copy, Debug)]
pub struct Op {
    pub token: &'static str,
    pub word: bool,
    pub fixity: Fixity,
    pub level: &'static str,
    pub bp: u8,
    pub assoc: Option<Assoc>,
    pub family: Family,
    pub node: &'static str,
    pub name: Option<&'static str>,
    pub relation: Option<Relation>,
    pub compound: Option<&'static str>,
    pub short_circuit: bool,
}

pub const RESERVED: &[&str] = &["TRUE", "FALSE", "NULL", "AND", "OR", "NOT", "XOR", "EQL", "IN", "BAND", "BOR", "BXOR"];

pub const SYMBOLS: &[&str] = &["???", "$==", "$!=", "$<=", "$>=", ".>", "??", "==", "!=", "<=", ">=", "$<", "$>", "+=", "-=", "*=", "/=", "%=", "&=", "[", "-", "*", "/", "%", "+", "&", "<", ">", "=", ",", ";", "(", ")", "]"];

pub const BP_POSTFIX: u8 = 17;
pub const BP_NEG: u8 = 16;
pub const BP_MUL: u8 = 15;
pub const BP_ADD: u8 = 14;
pub const BP_CONCAT: u8 = 13;
pub const BP_BAND: u8 = 12;
pub const BP_BXOR: u8 = 11;
pub const BP_BOR: u8 = 10;
pub const BP_COALESCE: u8 = 9;
pub const BP_COMPARE: u8 = 8;
pub const BP_NOT: u8 = 7;
pub const BP_AND: u8 = 6;
pub const BP_XOR: u8 = 5;
pub const BP_OR: u8 = 4;
pub const BP_ASSIGN: u8 = 3;
pub const BP_LIST: u8 = 2;
pub const BP_SEQ: u8 = 1;

pub const OPS: &[Op] = &[
    Op { token: "[", word: false, fixity: Fixity::Postfix, level: "POSTFIX", bp: 17, assoc: None, family: Family::Postfix, node: "index", name: None, relation: None, compound: None, short_circuit: false },
    Op { token: ".>", word: false, fixity: Fixity::Postfix, level: "POSTFIX", bp: 17, assoc: None, family: Family::Postfix, node: "pipe", name: None, relation: None, compound: None, short_circuit: false },
    Op { token: "-", word: false, fixity: Fixity::Prefix, level: "NEG", bp: 16, assoc: None, family: Family::Arith, node: "un", name: Some("NEG"), relation: None, compound: None, short_circuit: false },
    Op { token: "*", word: false, fixity: Fixity::Infix, level: "MUL", bp: 15, assoc: Some(Assoc::Left), family: Family::Arith, node: "bin", name: None, relation: None, compound: None, short_circuit: false },
    Op { token: "/", word: false, fixity: Fixity::Infix, level: "MUL", bp: 15, assoc: Some(Assoc::Left), family: Family::Arith, node: "bin", name: None, relation: None, compound: None, short_circuit: false },
    Op { token: "%", word: false, fixity: Fixity::Infix, level: "MUL", bp: 15, assoc: Some(Assoc::Left), family: Family::Arith, node: "bin", name: None, relation: None, compound: None, short_circuit: false },
    Op { token: "+", word: false, fixity: Fixity::Infix, level: "ADD", bp: 14, assoc: Some(Assoc::Left), family: Family::Arith, node: "bin", name: None, relation: None, compound: None, short_circuit: false },
    Op { token: "-", word: false, fixity: Fixity::Infix, level: "ADD", bp: 14, assoc: Some(Assoc::Left), family: Family::Arith, node: "bin", name: None, relation: None, compound: None, short_circuit: false },
    Op { token: "&", word: false, fixity: Fixity::Infix, level: "CONCAT", bp: 13, assoc: Some(Assoc::Left), family: Family::Concat, node: "bin", name: None, relation: None, compound: None, short_circuit: false },
    Op { token: "BAND", word: true, fixity: Fixity::Infix, level: "BAND", bp: 12, assoc: Some(Assoc::Left), family: Family::Bitwise, node: "bin", name: None, relation: None, compound: None, short_circuit: false },
    Op { token: "BXOR", word: true, fixity: Fixity::Infix, level: "BXOR", bp: 11, assoc: Some(Assoc::Left), family: Family::Bitwise, node: "bin", name: None, relation: None, compound: None, short_circuit: false },
    Op { token: "BOR", word: true, fixity: Fixity::Infix, level: "BOR", bp: 10, assoc: Some(Assoc::Left), family: Family::Bitwise, node: "bin", name: None, relation: None, compound: None, short_circuit: false },
    Op { token: "??", word: false, fixity: Fixity::Infix, level: "COALESCE", bp: 9, assoc: Some(Assoc::Right), family: Family::Coalesce, node: "bin", name: None, relation: None, compound: None, short_circuit: true },
    Op { token: "???", word: false, fixity: Fixity::Infix, level: "COALESCE", bp: 9, assoc: Some(Assoc::Right), family: Family::Coalesce, node: "bin", name: None, relation: None, compound: None, short_circuit: true },
    Op { token: "==", word: false, fixity: Fixity::Infix, level: "COMPARE", bp: 8, assoc: Some(Assoc::NonAssoc), family: Family::Compare, node: "bin", name: None, relation: Some(Relation::Eq), compound: None, short_circuit: false },
    Op { token: "!=", word: false, fixity: Fixity::Infix, level: "COMPARE", bp: 8, assoc: Some(Assoc::NonAssoc), family: Family::Compare, node: "bin", name: None, relation: Some(Relation::Ne), compound: None, short_circuit: false },
    Op { token: "<", word: false, fixity: Fixity::Infix, level: "COMPARE", bp: 8, assoc: Some(Assoc::NonAssoc), family: Family::Compare, node: "bin", name: None, relation: Some(Relation::Lt), compound: None, short_circuit: false },
    Op { token: "<=", word: false, fixity: Fixity::Infix, level: "COMPARE", bp: 8, assoc: Some(Assoc::NonAssoc), family: Family::Compare, node: "bin", name: None, relation: Some(Relation::Le), compound: None, short_circuit: false },
    Op { token: ">", word: false, fixity: Fixity::Infix, level: "COMPARE", bp: 8, assoc: Some(Assoc::NonAssoc), family: Family::Compare, node: "bin", name: None, relation: Some(Relation::Gt), compound: None, short_circuit: false },
    Op { token: ">=", word: false, fixity: Fixity::Infix, level: "COMPARE", bp: 8, assoc: Some(Assoc::NonAssoc), family: Family::Compare, node: "bin", name: None, relation: Some(Relation::Ge), compound: None, short_circuit: false },
    Op { token: "$==", word: false, fixity: Fixity::Infix, level: "COMPARE", bp: 8, assoc: Some(Assoc::NonAssoc), family: Family::TextCompare, node: "bin", name: None, relation: Some(Relation::Eq), compound: None, short_circuit: false },
    Op { token: "$!=", word: false, fixity: Fixity::Infix, level: "COMPARE", bp: 8, assoc: Some(Assoc::NonAssoc), family: Family::TextCompare, node: "bin", name: None, relation: Some(Relation::Ne), compound: None, short_circuit: false },
    Op { token: "$<", word: false, fixity: Fixity::Infix, level: "COMPARE", bp: 8, assoc: Some(Assoc::NonAssoc), family: Family::TextCompare, node: "bin", name: None, relation: Some(Relation::Lt), compound: None, short_circuit: false },
    Op { token: "$<=", word: false, fixity: Fixity::Infix, level: "COMPARE", bp: 8, assoc: Some(Assoc::NonAssoc), family: Family::TextCompare, node: "bin", name: None, relation: Some(Relation::Le), compound: None, short_circuit: false },
    Op { token: "$>", word: false, fixity: Fixity::Infix, level: "COMPARE", bp: 8, assoc: Some(Assoc::NonAssoc), family: Family::TextCompare, node: "bin", name: None, relation: Some(Relation::Gt), compound: None, short_circuit: false },
    Op { token: "$>=", word: false, fixity: Fixity::Infix, level: "COMPARE", bp: 8, assoc: Some(Assoc::NonAssoc), family: Family::TextCompare, node: "bin", name: None, relation: Some(Relation::Ge), compound: None, short_circuit: false },
    Op { token: "EQL", word: true, fixity: Fixity::Infix, level: "COMPARE", bp: 8, assoc: Some(Assoc::NonAssoc), family: Family::DeepCompare, node: "bin", name: None, relation: None, compound: None, short_circuit: false },
    Op { token: "IN", word: true, fixity: Fixity::Infix, level: "COMPARE", bp: 8, assoc: Some(Assoc::NonAssoc), family: Family::DeepCompare, node: "bin", name: None, relation: None, compound: None, short_circuit: false },
    Op { token: "NOT", word: true, fixity: Fixity::Prefix, level: "NOT", bp: 7, assoc: None, family: Family::Logic, node: "un", name: Some("NOT"), relation: None, compound: None, short_circuit: false },
    Op { token: "AND", word: true, fixity: Fixity::Infix, level: "AND", bp: 6, assoc: Some(Assoc::Left), family: Family::Logic, node: "bin", name: None, relation: None, compound: None, short_circuit: true },
    Op { token: "XOR", word: true, fixity: Fixity::Infix, level: "XOR", bp: 5, assoc: Some(Assoc::Left), family: Family::Logic, node: "bin", name: None, relation: None, compound: None, short_circuit: false },
    Op { token: "OR", word: true, fixity: Fixity::Infix, level: "OR", bp: 4, assoc: Some(Assoc::Left), family: Family::Logic, node: "bin", name: None, relation: None, compound: None, short_circuit: true },
    Op { token: "=", word: false, fixity: Fixity::Infix, level: "ASSIGN", bp: 3, assoc: Some(Assoc::Right), family: Family::Assign, node: "assign", name: None, relation: None, compound: None, short_circuit: false },
    Op { token: "+=", word: false, fixity: Fixity::Infix, level: "ASSIGN", bp: 3, assoc: Some(Assoc::Right), family: Family::Assign, node: "assign", name: None, relation: None, compound: Some("+"), short_circuit: false },
    Op { token: "-=", word: false, fixity: Fixity::Infix, level: "ASSIGN", bp: 3, assoc: Some(Assoc::Right), family: Family::Assign, node: "assign", name: None, relation: None, compound: Some("-"), short_circuit: false },
    Op { token: "*=", word: false, fixity: Fixity::Infix, level: "ASSIGN", bp: 3, assoc: Some(Assoc::Right), family: Family::Assign, node: "assign", name: None, relation: None, compound: Some("*"), short_circuit: false },
    Op { token: "/=", word: false, fixity: Fixity::Infix, level: "ASSIGN", bp: 3, assoc: Some(Assoc::Right), family: Family::Assign, node: "assign", name: None, relation: None, compound: Some("/"), short_circuit: false },
    Op { token: "%=", word: false, fixity: Fixity::Infix, level: "ASSIGN", bp: 3, assoc: Some(Assoc::Right), family: Family::Assign, node: "assign", name: None, relation: None, compound: Some("%"), short_circuit: false },
    Op { token: "&=", word: false, fixity: Fixity::Infix, level: "ASSIGN", bp: 3, assoc: Some(Assoc::Right), family: Family::Assign, node: "assign", name: None, relation: None, compound: Some("&"), short_circuit: false },
    Op { token: ",", word: false, fixity: Fixity::Infix, level: "LIST", bp: 2, assoc: Some(Assoc::Left), family: Family::List, node: "list", name: None, relation: None, compound: None, short_circuit: false },
    Op { token: ";", word: false, fixity: Fixity::Infix, level: "SEQ", bp: 1, assoc: Some(Assoc::Left), family: Family::Sequence, node: "seq", name: None, relation: None, compound: None, short_circuit: false },
];

/// A symbol token as an infix operator.
pub fn infix_symbol(token: &str) -> Option<&'static Op> {
    match token {
        "*" => Some(&OPS[3]),
        "/" => Some(&OPS[4]),
        "%" => Some(&OPS[5]),
        "+" => Some(&OPS[6]),
        "-" => Some(&OPS[7]),
        "&" => Some(&OPS[8]),
        "??" => Some(&OPS[12]),
        "???" => Some(&OPS[13]),
        "==" => Some(&OPS[14]),
        "!=" => Some(&OPS[15]),
        "<" => Some(&OPS[16]),
        "<=" => Some(&OPS[17]),
        ">" => Some(&OPS[18]),
        ">=" => Some(&OPS[19]),
        "$==" => Some(&OPS[20]),
        "$!=" => Some(&OPS[21]),
        "$<" => Some(&OPS[22]),
        "$<=" => Some(&OPS[23]),
        "$>" => Some(&OPS[24]),
        "$>=" => Some(&OPS[25]),
        "=" => Some(&OPS[32]),
        "+=" => Some(&OPS[33]),
        "-=" => Some(&OPS[34]),
        "*=" => Some(&OPS[35]),
        "/=" => Some(&OPS[36]),
        "%=" => Some(&OPS[37]),
        "&=" => Some(&OPS[38]),
        "," => Some(&OPS[39]),
        ";" => Some(&OPS[40]),
        _ => None,
    }
}

/// A word (an identifier token) as an infix operator.
pub fn infix_word(token: &str) -> Option<&'static Op> {
    match token {
        "BAND" => Some(&OPS[9]),
        "BXOR" => Some(&OPS[10]),
        "BOR" => Some(&OPS[11]),
        "EQL" => Some(&OPS[26]),
        "IN" => Some(&OPS[27]),
        "AND" => Some(&OPS[29]),
        "XOR" => Some(&OPS[30]),
        "OR" => Some(&OPS[31]),
        _ => None,
    }
}

/// A token as a prefix operator.
pub fn prefix(token: &str) -> Option<&'static Op> {
    match token {
        "-" => Some(&OPS[2]),
        "NOT" => Some(&OPS[28]),
        _ => None,
    }
}
