// GENERATED by tools/gen-math-ops.mjs from spec/math-ops.json — do not edit; edit the manifest and regenerate.
//
// What the math plan compiles: Operators maps a binary operator token and
// Prefix a prefix operator name to a symbolic operation; Builtins
// maps a builtin name to {op, arity, aux}. Ops lists every
// operation; the optimizer maps each to its own native OpCode.

#[derive(Clone, Copy, Debug, PartialEq, Eq)]
pub enum MathArity {
    One,
    Two,
    Fold,
}

#[derive(Clone, Copy, Debug, PartialEq, Eq)]
pub struct BuiltinSpec {
    pub op: &'static str,
    pub arity: MathArity,
    pub aux: Option<usize>,
}

pub const OPERATORS: &[(&str, &str)] = &[
    ("+", "ADD"),
    ("-", "SUB"),
    ("*", "MUL"),
    ("/", "DIV"),
    ("%", "MOD"),
];

pub const PREFIX: &[(&str, &str)] = &[
    ("NEG", "NEG"),
];

pub const BUILTINS: &[(&str, BuiltinSpec)] = &[
    ("ABS", BuiltinSpec { op: "ABS", arity: MathArity::One, aux: None }),
    ("SIGN", BuiltinSpec { op: "SIGN", arity: MathArity::One, aux: None }),
    ("CEIL", BuiltinSpec { op: "CEIL", arity: MathArity::One, aux: None }),
    ("FLOOR", BuiltinSpec { op: "FLOOR", arity: MathArity::One, aux: None }),
    ("TRUNC", BuiltinSpec { op: "TRUNC", arity: MathArity::One, aux: None }),
    ("ROUND", BuiltinSpec { op: "ROUND", arity: MathArity::Two, aux: Some(1) }),
    ("POWER", BuiltinSpec { op: "POWER", arity: MathArity::Two, aux: Some(1) }),
    ("MIN", BuiltinSpec { op: "MIN", arity: MathArity::Fold, aux: None }),
    ("MAX", BuiltinSpec { op: "MAX", arity: MathArity::Fold, aux: None }),
];

pub const OPS: &[&str] = &[
    "ADD",
    "SUB",
    "MUL",
    "DIV",
    "MOD",
    "NEG",
    "ABS",
    "SIGN",
    "CEIL",
    "FLOOR",
    "TRUNC",
    "ROUND",
    "POWER",
    "MIN",
    "MAX",
];
