<?php
// GENERATED by tools/gen-sql-map.mjs from sql/dialects/*.json — do not edit.
// Regenerate with: node tools/gen-sql-map.mjs
// The format is normative in sql/MAP.md; the design is in docs/SQL-TRANSLATION.md.

declare(strict_types=1);

namespace Sel\Sql;

final class MapData
{
    /**
     * Every dialect, with its chain already flattened, so a lookup is a hash
     * access and nothing else. Runtime registration is what re-introduces the
     * chain, and it is the only thing that does.
     *
     * @var array<string, array<string, mixed>>
     */
    public const DIALECTS = [
        'ansi' => [
            'dialect' => 'ansi',
            'extends' => null,
            'version' => '1999',
            'target' => false,
            'lexical' => [
                'identQuote' => '"',
                'identEscape' => '""',
                'textQuote' => '\'',
                'textEscape' => [
                    '\'' => '\'\'',
                ],
                'true' => 'TRUE',
                'false' => 'FALSE',
                'binaryLiteral' => 'X\'{hex}\'',
                'textCollate' => '',
                'numericCast' => 'CAST({0} AS DECIMAL(38,10))',
                'isTrue' => '({0}) IS TRUE',
                'isNotTrue' => '({0}) IS NOT TRUE',
                'placeholder' => '?',
            ],
            'ops' => [
                '+' => [
                    'tpl' => '({0} + {1})',
                    'ret' => 'NUM',
                ],
                '-' => [
                    'tpl' => '({0} - {1})',
                    'ret' => 'NUM',
                ],
                '*' => [
                    'tpl' => '({0} * {1})',
                    'ret' => 'NUM',
                ],
                '/' => [
                    'tpl' => '({0} / {1})',
                    'ret' => 'NUM',
                    'caveat' => 'division-scale',
                ],
                '%' => [
                    'tpl' => 'MOD({0}, {1})',
                    'ret' => 'NUM',
                ],
                'NEG' => [
                    'tpl' => '(-{0})',
                    'ret' => 'NUM',
                ],
                '&' => [
                    'variants' => [
                        'text' => '({0} || {1})',
                    ],
                    'ret' => '@concat',
                    'caveat' => 'concat-null',
                ],
                'AND' => [
                    'tpl' => '({0} AND {1})',
                    'ret' => 'BOOL',
                ],
                'OR' => [
                    'tpl' => '({0} OR {1})',
                    'ret' => 'BOOL',
                ],
                'NOT' => [
                    'tpl' => '(NOT {0})',
                    'ret' => 'BOOL',
                ],
                'XOR' => [
                    'tpl' => '(({0}) <> ({1}))',
                    'ret' => 'BOOL',
                ],
                '==' => [
                    'variants' => [
                        'num' => '({0} = {1})',
                        'coerce' => '({numericCast:0} = {numericCast:1})',
                    ],
                    'ret' => 'BOOL',
                ],
                '!=' => [
                    'variants' => [
                        'num' => '({0} <> {1})',
                        'coerce' => '({numericCast:0} <> {numericCast:1})',
                    ],
                    'ret' => 'BOOL',
                ],
                '<' => [
                    'variants' => [
                        'num' => '({0} < {1})',
                        'coerce' => '({numericCast:0} < {numericCast:1})',
                    ],
                    'ret' => 'BOOL',
                ],
                '<=' => [
                    'variants' => [
                        'num' => '({0} <= {1})',
                        'coerce' => '({numericCast:0} <= {numericCast:1})',
                    ],
                    'ret' => 'BOOL',
                ],
                '>' => [
                    'variants' => [
                        'num' => '({0} > {1})',
                        'coerce' => '({numericCast:0} > {numericCast:1})',
                    ],
                    'ret' => 'BOOL',
                ],
                '>=' => [
                    'variants' => [
                        'num' => '({0} >= {1})',
                        'coerce' => '({numericCast:0} >= {numericCast:1})',
                    ],
                    'ret' => 'BOOL',
                ],
                '$==' => [
                    'variants' => [
                        'text' => '({0}{textCollate} = {1}{textCollate})',
                    ],
                    'ret' => 'BOOL',
                ],
                '$!=' => [
                    'variants' => [
                        'text' => '({0}{textCollate} <> {1}{textCollate})',
                    ],
                    'ret' => 'BOOL',
                ],
                '$<' => [
                    'variants' => [
                        'text' => '({0}{textCollate} < {1}{textCollate})',
                    ],
                    'ret' => 'BOOL',
                ],
                '$<=' => [
                    'variants' => [
                        'text' => '({0}{textCollate} <= {1}{textCollate})',
                    ],
                    'ret' => 'BOOL',
                ],
                '$>' => [
                    'variants' => [
                        'text' => '({0}{textCollate} > {1}{textCollate})',
                    ],
                    'ret' => 'BOOL',
                ],
                '$>=' => [
                    'variants' => [
                        'text' => '({0}{textCollate} >= {1}{textCollate})',
                    ],
                    'ret' => 'BOOL',
                ],
                'EQL' => [
                    'variants' => [
                        'text' => '({0}{textCollate} = {1}{textCollate})',
                    ],
                    'ret' => 'BOOL',
                ],
                'IN' => [
                    'variants' => [
                        'list' => '({0} IN ({1:}))',
                        'scalar' => '({0}{textCollate} = {1}{textCollate})',
                    ],
                    'ret' => 'BOOL',
                ],
                'BAND' => 'SQL\'s & is an integer operator; SEL\'s BAND is a byte-string operator over BIN of equal length, and no portable spelling of that exists',
                'BOR' => 'SQL\'s | is an integer operator; SEL\'s BOR is a byte-string operator over BIN of equal length, and no portable spelling of that exists',
                'BXOR' => 'SQL\'s ^ is an integer operator; SEL\'s BXOR is a byte-string operator over BIN of equal length, and no portable spelling of that exists',
            ],
            'funcs' => [
                'LEN' => [
                    'tpl' => 'CHAR_LENGTH({0})',
                    'ret' => 'NUM',
                ],
                'SUBSTR' => [
                    'tpl' => [
                        '2' => 'SUBSTRING({0} FROM {1})',
                        '3' => 'SUBSTRING({0} FROM {1} FOR {2})',
                    ],
                    'ret' => 'TEXT',
                ],
                'UPPER' => [
                    'tpl' => 'UPPER({0})',
                    'ret' => 'TEXT',
                    'caveat' => 'unicode-case',
                ],
                'LOWER' => [
                    'tpl' => 'LOWER({0})',
                    'ret' => 'TEXT',
                    'caveat' => 'unicode-case',
                ],
                'TRIM' => [
                    'tpl' => 'TRIM(BOTH FROM {0})',
                    'ret' => 'TEXT',
                    'caveat' => 'trim-charset',
                ],
                'LTRIM' => [
                    'tpl' => 'TRIM(LEADING FROM {0})',
                    'ret' => 'TEXT',
                    'caveat' => 'trim-charset',
                ],
                'RTRIM' => [
                    'tpl' => 'TRIM(TRAILING FROM {0})',
                    'ret' => 'TEXT',
                    'caveat' => 'trim-charset',
                ],
                'ABS' => [
                    'tpl' => 'ABS({0})',
                    'ret' => 'NUM',
                ],
                'CEIL' => [
                    'tpl' => 'CEIL({0})',
                    'ret' => 'NUM',
                ],
                'FLOOR' => [
                    'tpl' => 'FLOOR({0})',
                    'ret' => 'NUM',
                ],
                'POWER' => [
                    'tpl' => 'POWER({0}, {1})',
                    'ret' => 'NUM',
                    'caveat' => 'power-float',
                ],
                'LEFT' => 'no ANSI spelling; each server has its own, so this is set per dialect',
                'RIGHT' => 'no ANSI spelling; each server has its own, so this is set per dialect',
                'FIND' => 'ANSI POSITION exists but takes no start offset and spells its arguments differently in every server',
                'REPLACE' => 'not ANSI; set per dialect',
                'SPLIT' => 'yields a list, and a SQL expression is a scalar',
                'BACKWARDS' => 'no ANSI spelling; set per dialect',
                'REPEAT' => 'not ANSI; set per dialect',
                'PADL' => 'not ANSI; set per dialect',
                'PADR' => 'not ANSI; set per dialect',
                'CHAR' => 'not ANSI; the code-point-to-character spelling differs per server and per charset',
                'CODE' => 'not ANSI; set per dialect',
                'SIGN' => 'not ANSI; set per dialect',
                'TRUNC' => 'not ANSI; ROUND-toward-zero is spelled differently in every server',
                'ROUND' => 'not ANSI as a two-argument scale function; set per dialect',
                'MIN' => 'SEL\'s MIN is a scalar over its arguments, not a column aggregate; the scalar form is LEAST or GREATEST and is not ANSI',
                'MAX' => 'SEL\'s MAX is a scalar over its arguments, not a column aggregate; the scalar form is LEAST or GREATEST and is not ANSI',
                'ISNUM' => 'would need a regex or a failure-tolerant cast, and neither is ANSI',
                'BLEN' => 'not ANSI; octet length of a text value depends on the server\'s charset handling',
                'TO_UTF8' => 'SEL\'s TEXT/BIN distinction has no SQL counterpart; a cast to a binary type is per dialect',
                'FROM_UTF8' => 'SEL\'s TEXT/BIN distinction has no SQL counterpart; a cast from a binary type is per dialect',
                'TO_HEX' => 'not ANSI; set per dialect',
                'FROM_HEX' => 'not ANSI; set per dialect',
                'ENCODE_BASE64' => 'not ANSI; set per dialect',
                'DECODE_BASE64' => 'not ANSI; set per dialect',
                'CRC32' => 'not ANSI; set per dialect',
                'BTL' => 'yields a list, and a SQL expression is a scalar',
                'LTB' => 'takes a list, and a SQL expression is a scalar',
                'RMATCH' => 'regular expressions are not ANSI; set per dialect',
                'RFIND' => 'regular expressions are not ANSI; set per dialect',
                'RREPLACE' => 'regular expressions are not ANSI; set per dialect',
                'RGROUPS' => 'yields a list, and a SQL expression is a scalar',
            ],
            'skel' => [
                'case' => [
                    'tpl' => 'CASE {branches} ELSE {else} END',
                ],
                'caseBranch' => [
                    'tpl' => 'WHEN {cond} THEN {then}',
                ],
                'all' => [
                    'tpl' => 'NOT EXISTS (SELECT 1 FROM {from} WHERE {corr} AND ({body}) IS NOT TRUE)',
                ],
                'any' => [
                    'tpl' => 'EXISTS (SELECT 1 FROM {from} WHERE {corr} AND ({body}) IS TRUE)',
                ],
                'sum' => [
                    'tpl' => '(SELECT COALESCE(SUM({body}), 0) FROM {from} WHERE {corr})',
                ],
                'count' => [
                    'tpl' => '(SELECT COUNT(*) FROM {from} WHERE {corr})',
                ],
                'inRelation' => [
                    'tpl' => '({needle} IN (SELECT {body} FROM {from} WHERE {corr}))',
                ],
                'join' => 'LISTAGG is SQL:2016 and is spelled differently by every server that has it',
            ],
        ],
        'mariadb' => [
            'dialect' => 'mariadb',
            'extends' => 'mysql-family',
            'version' => '10.5',
            'target' => true,
            'lexical' => [
                'identQuote' => '`',
                'identEscape' => '``',
                'textQuote' => '\'',
                'textEscape' => [
                    '\'' => '\'\'',
                    '\\' => '\\\\',
                ],
                'true' => 'TRUE',
                'false' => 'FALSE',
                'binaryLiteral' => 'X\'{hex}\'',
                'textCollate' => ' COLLATE utf8mb4_bin',
                'numericCast' => 'CAST({0} AS DECIMAL(65,10))',
                'isTrue' => '({0}) IS TRUE',
                'isNotTrue' => '({0}) IS NOT TRUE',
                'placeholder' => '?',
            ],
            'ops' => [
                '+' => [
                    'tpl' => '({0} + {1})',
                    'ret' => 'NUM',
                ],
                '-' => [
                    'tpl' => '({0} - {1})',
                    'ret' => 'NUM',
                ],
                '*' => [
                    'tpl' => '({0} * {1})',
                    'ret' => 'NUM',
                ],
                '/' => [
                    'tpl' => '({0} / {1})',
                    'ret' => 'NUM',
                    'caveat' => 'division-scale',
                ],
                '%' => [
                    'tpl' => 'MOD({0}, {1})',
                    'ret' => 'NUM',
                ],
                'NEG' => [
                    'tpl' => '(-{0})',
                    'ret' => 'NUM',
                ],
                '&' => [
                    'variants' => [
                        'text' => 'CONCAT({0}, {1})',
                        'bin' => 'CONCAT({0}, {1})',
                    ],
                    'ret' => '@concat',
                    'caveat' => 'concat-null',
                ],
                'AND' => [
                    'tpl' => '({0} AND {1})',
                    'ret' => 'BOOL',
                ],
                'OR' => [
                    'tpl' => '({0} OR {1})',
                    'ret' => 'BOOL',
                ],
                'NOT' => [
                    'tpl' => '(NOT {0})',
                    'ret' => 'BOOL',
                ],
                'XOR' => [
                    'tpl' => '({0} XOR {1})',
                    'ret' => 'BOOL',
                ],
                '==' => [
                    'variants' => [
                        'num' => '({0} = {1})',
                        'coerce' => '({numericCast:0} = {numericCast:1})',
                    ],
                    'ret' => 'BOOL',
                ],
                '!=' => [
                    'variants' => [
                        'num' => '({0} <> {1})',
                        'coerce' => '({numericCast:0} <> {numericCast:1})',
                    ],
                    'ret' => 'BOOL',
                ],
                '<' => [
                    'variants' => [
                        'num' => '({0} < {1})',
                        'coerce' => '({numericCast:0} < {numericCast:1})',
                    ],
                    'ret' => 'BOOL',
                ],
                '<=' => [
                    'variants' => [
                        'num' => '({0} <= {1})',
                        'coerce' => '({numericCast:0} <= {numericCast:1})',
                    ],
                    'ret' => 'BOOL',
                ],
                '>' => [
                    'variants' => [
                        'num' => '({0} > {1})',
                        'coerce' => '({numericCast:0} > {numericCast:1})',
                    ],
                    'ret' => 'BOOL',
                ],
                '>=' => [
                    'variants' => [
                        'num' => '({0} >= {1})',
                        'coerce' => '({numericCast:0} >= {numericCast:1})',
                    ],
                    'ret' => 'BOOL',
                ],
                '$==' => [
                    'variants' => [
                        'text' => '({0}{textCollate} = {1}{textCollate})',
                    ],
                    'ret' => 'BOOL',
                ],
                '$!=' => [
                    'variants' => [
                        'text' => '({0}{textCollate} <> {1}{textCollate})',
                    ],
                    'ret' => 'BOOL',
                ],
                '$<' => [
                    'variants' => [
                        'text' => '({0}{textCollate} < {1}{textCollate})',
                    ],
                    'ret' => 'BOOL',
                ],
                '$<=' => [
                    'variants' => [
                        'text' => '({0}{textCollate} <= {1}{textCollate})',
                    ],
                    'ret' => 'BOOL',
                ],
                '$>' => [
                    'variants' => [
                        'text' => '({0}{textCollate} > {1}{textCollate})',
                    ],
                    'ret' => 'BOOL',
                ],
                '$>=' => [
                    'variants' => [
                        'text' => '({0}{textCollate} >= {1}{textCollate})',
                    ],
                    'ret' => 'BOOL',
                ],
                'EQL' => [
                    'variants' => [
                        'text' => '({0}{textCollate} = {1}{textCollate})',
                    ],
                    'ret' => 'BOOL',
                ],
                'IN' => [
                    'variants' => [
                        'list' => '({0} IN ({1:}))',
                        'scalar' => '({0}{textCollate} = {1}{textCollate})',
                    ],
                    'ret' => 'BOOL',
                ],
                'BAND' => 'SQL\'s & is an integer operator; SEL\'s BAND is a byte-string operator over BIN of equal length, and no portable spelling of that exists',
                'BOR' => 'SQL\'s | is an integer operator; SEL\'s BOR is a byte-string operator over BIN of equal length, and no portable spelling of that exists',
                'BXOR' => 'SQL\'s ^ is an integer operator; SEL\'s BXOR is a byte-string operator over BIN of equal length, and no portable spelling of that exists',
            ],
            'funcs' => [
                'LEN' => [
                    'tpl' => 'CHAR_LENGTH({0})',
                    'ret' => 'NUM',
                ],
                'SUBSTR' => [
                    'tpl' => [
                        '2' => 'SUBSTRING({0}, {1})',
                        '3' => 'SUBSTRING({0}, {1}, {2})',
                    ],
                    'ret' => 'TEXT',
                ],
                'UPPER' => [
                    'tpl' => 'UPPER({0})',
                    'ret' => 'TEXT',
                    'caveat' => 'unicode-case',
                ],
                'LOWER' => [
                    'tpl' => 'LOWER({0})',
                    'ret' => 'TEXT',
                    'caveat' => 'unicode-case',
                ],
                'TRIM' => [
                    'tpl' => 'REGEXP_REPLACE({0}, \'^[ \\\\t\\\\r\\\\n]+|[ \\\\t\\\\r\\\\n]+$\', \'\')',
                    'ret' => 'TEXT',
                ],
                'LTRIM' => [
                    'tpl' => 'REGEXP_REPLACE({0}, \'^[ \\\\t\\\\r\\\\n]+\', \'\')',
                    'ret' => 'TEXT',
                ],
                'RTRIM' => [
                    'tpl' => 'REGEXP_REPLACE({0}, \'[ \\\\t\\\\r\\\\n]+$\', \'\')',
                    'ret' => 'TEXT',
                ],
                'ABS' => [
                    'tpl' => 'ABS({0})',
                    'ret' => 'NUM',
                ],
                'CEIL' => [
                    'tpl' => 'CEIL({0})',
                    'ret' => 'NUM',
                ],
                'FLOOR' => [
                    'tpl' => 'FLOOR({0})',
                    'ret' => 'NUM',
                ],
                'POWER' => [
                    'tpl' => 'POWER({0}, {1})',
                    'ret' => 'NUM',
                    'caveat' => 'power-float',
                ],
                'LEFT' => [
                    'tpl' => 'LEFT({0}, {1})',
                    'ret' => 'TEXT',
                ],
                'RIGHT' => [
                    'tpl' => 'RIGHT({0}, {1})',
                    'ret' => 'TEXT',
                ],
                'FIND' => [
                    'tpl' => [
                        '2' => 'INSTR({1}, {0})',
                        '3' => 'LOCATE({0}, {1}, {2})',
                    ],
                    'ret' => 'NUM',
                ],
                'REPLACE' => [
                    'tpl' => 'REPLACE({2}, {0}, {1})',
                    'ret' => 'TEXT',
                ],
                'SPLIT' => 'yields a list, and a SQL expression is a scalar',
                'BACKWARDS' => [
                    'tpl' => 'REVERSE({0})',
                    'ret' => 'TEXT',
                ],
                'REPEAT' => [
                    'tpl' => 'REPEAT({0}, {1})',
                    'ret' => 'TEXT',
                ],
                'PADL' => [
                    'tpl' => 'LPAD({0}, {1}, {2})',
                    'ret' => 'TEXT',
                ],
                'PADR' => [
                    'tpl' => 'RPAD({0}, {1}, {2})',
                    'ret' => 'TEXT',
                ],
                'CHAR' => 'CHAR(n USING utf8mb4) reads n as a byte sequence in that charset, not as a code point: CHAR(233 USING utf8mb4) is NULL because 0xE9 alone is not valid UTF-8, where SEL says the character is e-acute',
                'CODE' => 'ORD returns the first character\'s bytes read as an integer, not its code point; SEL\'s CODE is a code point',
                'SIGN' => [
                    'tpl' => 'SIGN({0})',
                    'ret' => 'NUM',
                ],
                'TRUNC' => [
                    'tpl' => 'TRUNCATE({0}, 0)',
                    'ret' => 'NUM',
                ],
                'ROUND' => [
                    'tpl' => 'ROUND({0}, {1})',
                    'ret' => 'NUM',
                    'caveat' => 'rounding-mode',
                ],
                'MIN' => [
                    'tpl' => 'LEAST({*})',
                    'ret' => 'NUM',
                ],
                'MAX' => [
                    'tpl' => 'GREATEST({*})',
                    'ret' => 'NUM',
                ],
                'ISNUM' => [
                    'tpl' => '({0} REGEXP \'^-?[0-9]+(\\\\.[0-9]+)?$\')',
                    'ret' => 'BOOL',
                ],
                'BLEN' => [
                    'tpl' => 'LENGTH({0})',
                    'ret' => 'NUM',
                ],
                'TO_UTF8' => [
                    'tpl' => 'CAST({0} AS BINARY)',
                    'ret' => 'BIN',
                ],
                'FROM_UTF8' => [
                    'tpl' => 'CONVERT({0} USING utf8mb4)',
                    'ret' => 'TEXT',
                ],
                'TO_HEX' => [
                    'tpl' => 'LOWER(HEX({0}))',
                    'ret' => 'TEXT',
                ],
                'FROM_HEX' => [
                    'tpl' => 'UNHEX({0})',
                    'ret' => 'BIN',
                ],
                'ENCODE_BASE64' => [
                    'tpl' => 'REPLACE(REPLACE(TO_BASE64({0}), CHAR(10), \'\'), CHAR(13), \'\')',
                    'ret' => 'TEXT',
                ],
                'DECODE_BASE64' => [
                    'tpl' => 'FROM_BASE64({0})',
                    'ret' => 'BIN',
                    'caveat' => 'input-laxity',
                ],
                'CRC32' => [
                    'tpl' => 'LPAD(LOWER(HEX(CRC32({0}))), 8, \'0\')',
                    'ret' => 'TEXT',
                ],
                'BTL' => 'yields a list, and a SQL expression is a scalar',
                'LTB' => 'takes a list, and a SQL expression is a scalar',
                'RMATCH' => [
                    'tpl' => '({1}{textCollate} REGEXP CONCAT(\'(?s)\', {0}))',
                    'ret' => 'BOOL',
                    'caveat' => 'regex-engine',
                ],
                'RFIND' => [
                    'tpl' => 'REGEXP_INSTR({1}{textCollate}, CONCAT(\'(?s)\', {0}))',
                    'ret' => 'NUM',
                    'caveat' => 'regex-engine',
                ],
                'RREPLACE' => 'SEL replacement syntax is $0-$9 and MariaDB\'s is \\1; rewriting one into the other is only possible when the replacement is a literal, which the map cannot express',
                'RGROUPS' => 'yields a list, and a SQL expression is a scalar',
            ],
            'skel' => [
                'case' => [
                    'tpl' => 'CASE {branches} ELSE {else} END',
                ],
                'caseBranch' => [
                    'tpl' => 'WHEN {cond} THEN {then}',
                ],
                'all' => [
                    'tpl' => 'NOT EXISTS (SELECT 1 FROM {from} WHERE {corr} AND ({body}) IS NOT TRUE)',
                ],
                'any' => [
                    'tpl' => 'EXISTS (SELECT 1 FROM {from} WHERE {corr} AND ({body}) IS TRUE)',
                ],
                'sum' => [
                    'tpl' => '(SELECT COALESCE(SUM({body}), 0) FROM {from} WHERE {corr})',
                ],
                'count' => [
                    'tpl' => '(SELECT COUNT(*) FROM {from} WHERE {corr})',
                ],
                'inRelation' => [
                    'tpl' => '({needle} IN (SELECT {body} FROM {from} WHERE {corr}))',
                ],
                'join' => 'GROUP_CONCAT does not specify an order without an ORDER BY, and a relation binding has no key to order by; SEL\'s JOIN concatenates in insertion order',
            ],
        ],
        'mysql-family' => [
            'dialect' => 'mysql-family',
            'extends' => 'ansi',
            'version' => '0',
            'target' => false,
            'lexical' => [
                'identQuote' => '`',
                'identEscape' => '``',
                'textQuote' => '\'',
                'textEscape' => [
                    '\'' => '\'\'',
                    '\\' => '\\\\',
                ],
                'true' => 'TRUE',
                'false' => 'FALSE',
                'binaryLiteral' => 'X\'{hex}\'',
                'textCollate' => ' COLLATE utf8mb4_bin',
                'numericCast' => 'CAST({0} AS DECIMAL(65,10))',
                'isTrue' => '({0}) IS TRUE',
                'isNotTrue' => '({0}) IS NOT TRUE',
                'placeholder' => '?',
            ],
            'ops' => [
                '+' => [
                    'tpl' => '({0} + {1})',
                    'ret' => 'NUM',
                ],
                '-' => [
                    'tpl' => '({0} - {1})',
                    'ret' => 'NUM',
                ],
                '*' => [
                    'tpl' => '({0} * {1})',
                    'ret' => 'NUM',
                ],
                '/' => [
                    'tpl' => '({0} / {1})',
                    'ret' => 'NUM',
                    'caveat' => 'division-scale',
                ],
                '%' => [
                    'tpl' => 'MOD({0}, {1})',
                    'ret' => 'NUM',
                ],
                'NEG' => [
                    'tpl' => '(-{0})',
                    'ret' => 'NUM',
                ],
                '&' => [
                    'variants' => [
                        'text' => 'CONCAT({0}, {1})',
                        'bin' => 'CONCAT({0}, {1})',
                    ],
                    'ret' => '@concat',
                    'caveat' => 'concat-null',
                ],
                'AND' => [
                    'tpl' => '({0} AND {1})',
                    'ret' => 'BOOL',
                ],
                'OR' => [
                    'tpl' => '({0} OR {1})',
                    'ret' => 'BOOL',
                ],
                'NOT' => [
                    'tpl' => '(NOT {0})',
                    'ret' => 'BOOL',
                ],
                'XOR' => [
                    'tpl' => '({0} XOR {1})',
                    'ret' => 'BOOL',
                ],
                '==' => [
                    'variants' => [
                        'num' => '({0} = {1})',
                        'coerce' => '({numericCast:0} = {numericCast:1})',
                    ],
                    'ret' => 'BOOL',
                ],
                '!=' => [
                    'variants' => [
                        'num' => '({0} <> {1})',
                        'coerce' => '({numericCast:0} <> {numericCast:1})',
                    ],
                    'ret' => 'BOOL',
                ],
                '<' => [
                    'variants' => [
                        'num' => '({0} < {1})',
                        'coerce' => '({numericCast:0} < {numericCast:1})',
                    ],
                    'ret' => 'BOOL',
                ],
                '<=' => [
                    'variants' => [
                        'num' => '({0} <= {1})',
                        'coerce' => '({numericCast:0} <= {numericCast:1})',
                    ],
                    'ret' => 'BOOL',
                ],
                '>' => [
                    'variants' => [
                        'num' => '({0} > {1})',
                        'coerce' => '({numericCast:0} > {numericCast:1})',
                    ],
                    'ret' => 'BOOL',
                ],
                '>=' => [
                    'variants' => [
                        'num' => '({0} >= {1})',
                        'coerce' => '({numericCast:0} >= {numericCast:1})',
                    ],
                    'ret' => 'BOOL',
                ],
                '$==' => [
                    'variants' => [
                        'text' => '({0}{textCollate} = {1}{textCollate})',
                    ],
                    'ret' => 'BOOL',
                ],
                '$!=' => [
                    'variants' => [
                        'text' => '({0}{textCollate} <> {1}{textCollate})',
                    ],
                    'ret' => 'BOOL',
                ],
                '$<' => [
                    'variants' => [
                        'text' => '({0}{textCollate} < {1}{textCollate})',
                    ],
                    'ret' => 'BOOL',
                ],
                '$<=' => [
                    'variants' => [
                        'text' => '({0}{textCollate} <= {1}{textCollate})',
                    ],
                    'ret' => 'BOOL',
                ],
                '$>' => [
                    'variants' => [
                        'text' => '({0}{textCollate} > {1}{textCollate})',
                    ],
                    'ret' => 'BOOL',
                ],
                '$>=' => [
                    'variants' => [
                        'text' => '({0}{textCollate} >= {1}{textCollate})',
                    ],
                    'ret' => 'BOOL',
                ],
                'EQL' => [
                    'variants' => [
                        'text' => '({0}{textCollate} = {1}{textCollate})',
                    ],
                    'ret' => 'BOOL',
                ],
                'IN' => [
                    'variants' => [
                        'list' => '({0} IN ({1:}))',
                        'scalar' => '({0}{textCollate} = {1}{textCollate})',
                    ],
                    'ret' => 'BOOL',
                ],
                'BAND' => 'SQL\'s & is an integer operator; SEL\'s BAND is a byte-string operator over BIN of equal length, and no portable spelling of that exists',
                'BOR' => 'SQL\'s | is an integer operator; SEL\'s BOR is a byte-string operator over BIN of equal length, and no portable spelling of that exists',
                'BXOR' => 'SQL\'s ^ is an integer operator; SEL\'s BXOR is a byte-string operator over BIN of equal length, and no portable spelling of that exists',
            ],
            'funcs' => [
                'LEN' => [
                    'tpl' => 'CHAR_LENGTH({0})',
                    'ret' => 'NUM',
                ],
                'SUBSTR' => [
                    'tpl' => [
                        '2' => 'SUBSTRING({0}, {1})',
                        '3' => 'SUBSTRING({0}, {1}, {2})',
                    ],
                    'ret' => 'TEXT',
                ],
                'UPPER' => [
                    'tpl' => 'UPPER({0})',
                    'ret' => 'TEXT',
                    'caveat' => 'unicode-case',
                ],
                'LOWER' => [
                    'tpl' => 'LOWER({0})',
                    'ret' => 'TEXT',
                    'caveat' => 'unicode-case',
                ],
                'TRIM' => [
                    'tpl' => 'REGEXP_REPLACE({0}, \'^[ \\\\t\\\\r\\\\n]+|[ \\\\t\\\\r\\\\n]+$\', \'\')',
                    'ret' => 'TEXT',
                ],
                'LTRIM' => [
                    'tpl' => 'REGEXP_REPLACE({0}, \'^[ \\\\t\\\\r\\\\n]+\', \'\')',
                    'ret' => 'TEXT',
                ],
                'RTRIM' => [
                    'tpl' => 'REGEXP_REPLACE({0}, \'[ \\\\t\\\\r\\\\n]+$\', \'\')',
                    'ret' => 'TEXT',
                ],
                'ABS' => [
                    'tpl' => 'ABS({0})',
                    'ret' => 'NUM',
                ],
                'CEIL' => [
                    'tpl' => 'CEIL({0})',
                    'ret' => 'NUM',
                ],
                'FLOOR' => [
                    'tpl' => 'FLOOR({0})',
                    'ret' => 'NUM',
                ],
                'POWER' => [
                    'tpl' => 'POWER({0}, {1})',
                    'ret' => 'NUM',
                    'caveat' => 'power-float',
                ],
                'LEFT' => [
                    'tpl' => 'LEFT({0}, {1})',
                    'ret' => 'TEXT',
                ],
                'RIGHT' => [
                    'tpl' => 'RIGHT({0}, {1})',
                    'ret' => 'TEXT',
                ],
                'FIND' => [
                    'tpl' => [
                        '2' => 'INSTR({1}, {0})',
                        '3' => 'LOCATE({0}, {1}, {2})',
                    ],
                    'ret' => 'NUM',
                ],
                'REPLACE' => [
                    'tpl' => 'REPLACE({2}, {0}, {1})',
                    'ret' => 'TEXT',
                ],
                'SPLIT' => 'yields a list, and a SQL expression is a scalar',
                'BACKWARDS' => [
                    'tpl' => 'REVERSE({0})',
                    'ret' => 'TEXT',
                ],
                'REPEAT' => [
                    'tpl' => 'REPEAT({0}, {1})',
                    'ret' => 'TEXT',
                ],
                'PADL' => [
                    'tpl' => 'LPAD({0}, {1}, {2})',
                    'ret' => 'TEXT',
                ],
                'PADR' => [
                    'tpl' => 'RPAD({0}, {1}, {2})',
                    'ret' => 'TEXT',
                ],
                'CHAR' => 'CHAR(n USING utf8mb4) reads n as a byte sequence in that charset, not as a code point: CHAR(233 USING utf8mb4) is NULL because 0xE9 alone is not valid UTF-8, where SEL says the character is e-acute',
                'CODE' => 'ORD returns the first character\'s bytes read as an integer, not its code point; SEL\'s CODE is a code point',
                'SIGN' => [
                    'tpl' => 'SIGN({0})',
                    'ret' => 'NUM',
                ],
                'TRUNC' => [
                    'tpl' => 'TRUNCATE({0}, 0)',
                    'ret' => 'NUM',
                ],
                'ROUND' => [
                    'tpl' => 'ROUND({0}, {1})',
                    'ret' => 'NUM',
                    'caveat' => 'rounding-mode',
                ],
                'MIN' => [
                    'tpl' => 'LEAST({*})',
                    'ret' => 'NUM',
                ],
                'MAX' => [
                    'tpl' => 'GREATEST({*})',
                    'ret' => 'NUM',
                ],
                'ISNUM' => [
                    'tpl' => '({0} REGEXP \'^-?[0-9]+(\\\\.[0-9]+)?$\')',
                    'ret' => 'BOOL',
                ],
                'BLEN' => [
                    'tpl' => 'LENGTH({0})',
                    'ret' => 'NUM',
                ],
                'TO_UTF8' => [
                    'tpl' => 'CAST({0} AS BINARY)',
                    'ret' => 'BIN',
                ],
                'FROM_UTF8' => [
                    'tpl' => 'CONVERT({0} USING utf8mb4)',
                    'ret' => 'TEXT',
                ],
                'TO_HEX' => [
                    'tpl' => 'LOWER(HEX({0}))',
                    'ret' => 'TEXT',
                ],
                'FROM_HEX' => [
                    'tpl' => 'UNHEX({0})',
                    'ret' => 'BIN',
                ],
                'ENCODE_BASE64' => [
                    'tpl' => 'REPLACE(REPLACE(TO_BASE64({0}), CHAR(10), \'\'), CHAR(13), \'\')',
                    'ret' => 'TEXT',
                ],
                'DECODE_BASE64' => [
                    'tpl' => 'FROM_BASE64({0})',
                    'ret' => 'BIN',
                    'caveat' => 'input-laxity',
                ],
                'CRC32' => [
                    'tpl' => 'LPAD(LOWER(HEX(CRC32({0}))), 8, \'0\')',
                    'ret' => 'TEXT',
                ],
                'BTL' => 'yields a list, and a SQL expression is a scalar',
                'LTB' => 'takes a list, and a SQL expression is a scalar',
                'RMATCH' => 'regular expressions are not ANSI; set per dialect',
                'RFIND' => [
                    'tpl' => 'REGEXP_INSTR({1}, {0})',
                    'ret' => 'NUM',
                    'caveat' => 'regex-engine',
                ],
                'RREPLACE' => 'SEL replacement syntax is $0-$9 and MariaDB\'s is \\1; rewriting one into the other is only possible when the replacement is a literal, which the map cannot express',
                'RGROUPS' => 'yields a list, and a SQL expression is a scalar',
            ],
            'skel' => [
                'case' => [
                    'tpl' => 'CASE {branches} ELSE {else} END',
                ],
                'caseBranch' => [
                    'tpl' => 'WHEN {cond} THEN {then}',
                ],
                'all' => [
                    'tpl' => 'NOT EXISTS (SELECT 1 FROM {from} WHERE {corr} AND ({body}) IS NOT TRUE)',
                ],
                'any' => [
                    'tpl' => 'EXISTS (SELECT 1 FROM {from} WHERE {corr} AND ({body}) IS TRUE)',
                ],
                'sum' => [
                    'tpl' => '(SELECT COALESCE(SUM({body}), 0) FROM {from} WHERE {corr})',
                ],
                'count' => [
                    'tpl' => '(SELECT COUNT(*) FROM {from} WHERE {corr})',
                ],
                'inRelation' => [
                    'tpl' => '({needle} IN (SELECT {body} FROM {from} WHERE {corr}))',
                ],
                'join' => 'GROUP_CONCAT does not specify an order without an ORDER BY, and a relation binding has no key to order by; SEL\'s JOIN concatenates in insertion order',
            ],
        ],
    ];
}
