// GENERATED by tools/gen-lexicon.mjs from spec/lexicon.json — do not edit; edit the lexicon and regenerate.
//
// RESERVED: the reserved words. SYMBOLS: every symbol token, longest first.
// BP_<LEVEL>: each precedence level's binding power (higher binds tighter).
// OPS: one entry per operator, tightest level first; see spec/lexicon.md for
// the fields. relation is an index into eq ne lt le gt ge (-1 when none);
// assoc is 'L', 'R', 'N', or 0 unless infix.
#pragma once

namespace sel_lexicon {

enum class Fixity : unsigned char { Infix, Prefix, Postfix };

enum class Family : unsigned char { Arith, Concat, TextCompare, DeepCompare, Coalesce, Logic, Bitwise, Assign, Sequence, List, Compare, Postfix };

struct Op {
  const char* token;
  bool word;
  Fixity fixity;
  const char* level;
  int bp;
  char assoc;
  Family family;
  const char* node;
  const char* name;
  int relation;
  const char* compound;
  bool short_circuit;
};

inline const char* const RESERVED[] = {"TRUE", "FALSE", "NULL", "AND", "OR", "NOT", "XOR", "EQL", "IN", "BAND", "BOR", "BXOR"};
inline constexpr int RESERVED_COUNT = 12;

inline const char* const SYMBOLS[] = {"???", "$==", "$!=", "$<=", "$>=", ".>", "??", "==", "!=", "<=", ">=", "$<", "$>", "+=", "-=", "*=", "/=", "%=", "&=", "[", "-", "*", "/", "%", "+", "&", "<", ">", "=", ",", ";", "(", ")", "]"};
inline constexpr int SYMBOL_COUNT = 34;

inline constexpr int BP_POSTFIX = 17;
inline constexpr int BP_NEG = 16;
inline constexpr int BP_MUL = 15;
inline constexpr int BP_ADD = 14;
inline constexpr int BP_CONCAT = 13;
inline constexpr int BP_BAND = 12;
inline constexpr int BP_BXOR = 11;
inline constexpr int BP_BOR = 10;
inline constexpr int BP_COALESCE = 9;
inline constexpr int BP_COMPARE = 8;
inline constexpr int BP_NOT = 7;
inline constexpr int BP_AND = 6;
inline constexpr int BP_XOR = 5;
inline constexpr int BP_OR = 4;
inline constexpr int BP_ASSIGN = 3;
inline constexpr int BP_LIST = 2;
inline constexpr int BP_SEQ = 1;

inline const Op OPS[] = {
  {"[", false, Fixity::Postfix, "POSTFIX", 17, 0, Family::Postfix, "index", nullptr, -1, nullptr, false},
  {".>", false, Fixity::Postfix, "POSTFIX", 17, 0, Family::Postfix, "pipe", nullptr, -1, nullptr, false},
  {"-", false, Fixity::Prefix, "NEG", 16, 0, Family::Arith, "un", "NEG", -1, nullptr, false},
  {"*", false, Fixity::Infix, "MUL", 15, 'L', Family::Arith, "bin", nullptr, -1, nullptr, false},
  {"/", false, Fixity::Infix, "MUL", 15, 'L', Family::Arith, "bin", nullptr, -1, nullptr, false},
  {"%", false, Fixity::Infix, "MUL", 15, 'L', Family::Arith, "bin", nullptr, -1, nullptr, false},
  {"+", false, Fixity::Infix, "ADD", 14, 'L', Family::Arith, "bin", nullptr, -1, nullptr, false},
  {"-", false, Fixity::Infix, "ADD", 14, 'L', Family::Arith, "bin", nullptr, -1, nullptr, false},
  {"&", false, Fixity::Infix, "CONCAT", 13, 'L', Family::Concat, "bin", nullptr, -1, nullptr, false},
  {"BAND", true, Fixity::Infix, "BAND", 12, 'L', Family::Bitwise, "bin", nullptr, -1, nullptr, false},
  {"BXOR", true, Fixity::Infix, "BXOR", 11, 'L', Family::Bitwise, "bin", nullptr, -1, nullptr, false},
  {"BOR", true, Fixity::Infix, "BOR", 10, 'L', Family::Bitwise, "bin", nullptr, -1, nullptr, false},
  {"??", false, Fixity::Infix, "COALESCE", 9, 'R', Family::Coalesce, "bin", nullptr, -1, nullptr, true},
  {"???", false, Fixity::Infix, "COALESCE", 9, 'R', Family::Coalesce, "bin", nullptr, -1, nullptr, true},
  {"==", false, Fixity::Infix, "COMPARE", 8, 'N', Family::Compare, "bin", nullptr, 0, nullptr, false},
  {"!=", false, Fixity::Infix, "COMPARE", 8, 'N', Family::Compare, "bin", nullptr, 1, nullptr, false},
  {"<", false, Fixity::Infix, "COMPARE", 8, 'N', Family::Compare, "bin", nullptr, 2, nullptr, false},
  {"<=", false, Fixity::Infix, "COMPARE", 8, 'N', Family::Compare, "bin", nullptr, 3, nullptr, false},
  {">", false, Fixity::Infix, "COMPARE", 8, 'N', Family::Compare, "bin", nullptr, 4, nullptr, false},
  {">=", false, Fixity::Infix, "COMPARE", 8, 'N', Family::Compare, "bin", nullptr, 5, nullptr, false},
  {"$==", false, Fixity::Infix, "COMPARE", 8, 'N', Family::TextCompare, "bin", nullptr, 0, nullptr, false},
  {"$!=", false, Fixity::Infix, "COMPARE", 8, 'N', Family::TextCompare, "bin", nullptr, 1, nullptr, false},
  {"$<", false, Fixity::Infix, "COMPARE", 8, 'N', Family::TextCompare, "bin", nullptr, 2, nullptr, false},
  {"$<=", false, Fixity::Infix, "COMPARE", 8, 'N', Family::TextCompare, "bin", nullptr, 3, nullptr, false},
  {"$>", false, Fixity::Infix, "COMPARE", 8, 'N', Family::TextCompare, "bin", nullptr, 4, nullptr, false},
  {"$>=", false, Fixity::Infix, "COMPARE", 8, 'N', Family::TextCompare, "bin", nullptr, 5, nullptr, false},
  {"EQL", true, Fixity::Infix, "COMPARE", 8, 'N', Family::DeepCompare, "bin", nullptr, -1, nullptr, false},
  {"IN", true, Fixity::Infix, "COMPARE", 8, 'N', Family::DeepCompare, "bin", nullptr, -1, nullptr, false},
  {"NOT", true, Fixity::Prefix, "NOT", 7, 0, Family::Logic, "un", "NOT", -1, nullptr, false},
  {"AND", true, Fixity::Infix, "AND", 6, 'L', Family::Logic, "bin", nullptr, -1, nullptr, true},
  {"XOR", true, Fixity::Infix, "XOR", 5, 'L', Family::Logic, "bin", nullptr, -1, nullptr, false},
  {"OR", true, Fixity::Infix, "OR", 4, 'L', Family::Logic, "bin", nullptr, -1, nullptr, true},
  {"=", false, Fixity::Infix, "ASSIGN", 3, 'R', Family::Assign, "assign", nullptr, -1, nullptr, false},
  {"+=", false, Fixity::Infix, "ASSIGN", 3, 'R', Family::Assign, "assign", nullptr, -1, "+", false},
  {"-=", false, Fixity::Infix, "ASSIGN", 3, 'R', Family::Assign, "assign", nullptr, -1, "-", false},
  {"*=", false, Fixity::Infix, "ASSIGN", 3, 'R', Family::Assign, "assign", nullptr, -1, "*", false},
  {"/=", false, Fixity::Infix, "ASSIGN", 3, 'R', Family::Assign, "assign", nullptr, -1, "/", false},
  {"%=", false, Fixity::Infix, "ASSIGN", 3, 'R', Family::Assign, "assign", nullptr, -1, "%", false},
  {"&=", false, Fixity::Infix, "ASSIGN", 3, 'R', Family::Assign, "assign", nullptr, -1, "&", false},
  {",", false, Fixity::Infix, "LIST", 2, 'L', Family::List, "list", nullptr, -1, nullptr, false},
  {";", false, Fixity::Infix, "SEQ", 1, 'L', Family::Sequence, "seq", nullptr, -1, nullptr, false},
};

inline constexpr int OP_COUNT = 41;

}  // namespace sel_lexicon
