// GENERATED by tools/gen-builtins.mjs from spec/builtins.json — do not edit; edit the manifest and regenerate.
//
// One entry per builtin, sorted by name so lookup can bisect: min, max (-1
// when variadic — the includer maps it to its own sentinel), lazy, binds and
// the extra arity rule as a plain function, or nullptr. sel.cpp checks every
// define() against it.
#pragma once

#include <string>

namespace sel_builtin_manifest {

struct Entry {
  const char* name;
  int min;
  int max;
  bool lazy;
  bool binds;
  std::string (*arity_error)(int);
};

inline std::string arity_COND(int n) {
  if (n % 2 == 0) return "COND takes condition/result pairs and a final default (an odd number of arguments), got " + std::to_string(n) + "";
  return "";
}

inline std::string arity_LINK(int n) {
  if (!(n == 3 || n == 5)) return "LINK takes 3 or 5 arguments, got " + std::to_string(n) + "";
  return "";
}

inline std::string arity_LINK_LEFT(int n) {
  if (!(n == 3 || n == 5)) return "LINK_LEFT takes 3 or 5 arguments, got " + std::to_string(n) + "";
  return "";
}

inline std::string arity_RECORD(int n) {
  if (n % 2 != 0) return "RECORD takes an even number of arguments (key-value pairs), got " + std::to_string(n) + "";
  return "";
}

inline const Entry ENTRIES[] = {
  {"ABORT", 1, 1, false, false, nullptr},
  {"ABS", 1, 1, false, false, nullptr},
  {"ALL", 2, 3, true, true, nullptr},
  {"ANY", 2, 3, true, true, nullptr},
  {"BACKWARDS", 1, 1, false, false, nullptr},
  {"BLEN", 1, 1, false, false, nullptr},
  {"BTL", 1, 1, false, false, nullptr},
  {"BUCKET", 2, 4, true, true, nullptr},
  {"CANON", 1, 1, false, false, nullptr},
  {"CEIL", 1, 1, false, false, nullptr},
  {"CHAR", 1, 1, false, false, nullptr},
  {"COALESCE", 1, -1, true, false, nullptr},
  {"CODE", 1, 1, false, false, nullptr},
  {"COND", 3, -1, true, false, arity_COND},
  {"COUNT", 1, 1, false, false, nullptr},
  {"CRC32", 1, 1, false, false, nullptr},
  {"DECODE_BASE64", 1, 1, false, false, nullptr},
  {"DEDUPE", 1, 1, false, false, nullptr},
  {"DISTINCT", 1, 1, false, false, nullptr},
  {"DROP", 2, 2, false, false, nullptr},
  {"ENCODE_BASE64", 1, 1, false, false, nullptr},
  {"FILTER", 2, 3, true, true, nullptr},
  {"FIND", 2, 3, false, false, nullptr},
  {"FLOOR", 1, 1, false, false, nullptr},
  {"FROM_HEX", 1, 1, false, false, nullptr},
  {"FROM_UTF8", 1, 1, false, false, nullptr},
  {"GET", 2, 3, true, false, nullptr},
  {"HAS", 2, 2, false, false, nullptr},
  {"IF", 2, 3, true, false, nullptr},
  {"INDEXES", 1, 1, false, false, nullptr},
  {"ISNUM", 1, 1, false, false, nullptr},
  {"IS_BLANK", 1, 1, false, false, nullptr},
  {"IS_NOT_NULL", 1, 1, false, false, nullptr},
  {"IS_NULL", 1, 1, false, false, nullptr},
  {"IS_PRESENT", 1, 1, false, false, nullptr},
  {"JOIN", 2, 2, false, false, nullptr},
  {"LEFT", 2, 2, false, false, nullptr},
  {"LEN", 1, 1, false, false, nullptr},
  {"LINK", 3, 5, true, true, arity_LINK},
  {"LINK_LEFT", 3, 5, true, true, arity_LINK_LEFT},
  {"LIST", 0, -1, false, false, nullptr},
  {"LOWER", 1, 1, false, false, nullptr},
  {"LTB", 1, 1, false, false, nullptr},
  {"LTRIM", 1, 1, false, false, nullptr},
  {"MAP", 2, 3, true, true, nullptr},
  {"MAX", 1, -1, false, false, nullptr},
  {"MIN", 1, -1, false, false, nullptr},
  {"PADL", 3, 3, false, false, nullptr},
  {"PADR", 3, 3, false, false, nullptr},
  {"PATH", 2, 3, true, false, nullptr},
  {"POWER", 2, 2, false, false, nullptr},
  {"RECORD", 0, -1, false, false, arity_RECORD},
  {"REPEAT", 2, 2, false, false, nullptr},
  {"REPLACE", 3, 3, false, false, nullptr},
  {"RFIND", 2, 3, false, false, nullptr},
  {"RGROUPS", 2, 3, false, false, nullptr},
  {"RIGHT", 2, 2, false, false, nullptr},
  {"RMATCH", 2, 3, false, false, nullptr},
  {"ROUND", 2, 2, false, false, nullptr},
  {"RREPLACE", 3, 4, false, false, nullptr},
  {"RTRIM", 1, 1, false, false, nullptr},
  {"SELECT_COLS", 2, -1, false, false, nullptr},
  {"SIGN", 1, 1, false, false, nullptr},
  {"SORT", 1, 3, true, true, nullptr},
  {"SORT_BY", 2, 4, true, true, nullptr},
  {"SORT_DESC", 1, 3, true, true, nullptr},
  {"SPLIT", 2, 2, false, false, nullptr},
  {"SUBSTR", 2, 3, false, false, nullptr},
  {"SUM", 2, 3, true, true, nullptr},
  {"TAKE", 2, 2, false, false, nullptr},
  {"TOP", 2, 4, true, true, nullptr},
  {"TOP_BY", 3, 5, true, true, nullptr},
  {"TOP_DESC", 2, 4, true, true, nullptr},
  {"TO_HEX", 1, 1, false, false, nullptr},
  {"TO_UTF8", 1, 1, false, false, nullptr},
  {"TRIM", 1, 1, false, false, nullptr},
  {"TRUNC", 1, 1, false, false, nullptr},
  {"UPPER", 1, 1, false, false, nullptr},
};

inline constexpr int COUNT = 78;

// The binding forms (spec/builtins.md): per accepted count, in the order the
// evaluator tries them, each argument's scope, an optional guard on one
// argument (kind 0 = none, 1 = a bare name, 2 = a text literal) and the
// implicit names bound inside. sel.cpp turns these into binding_form().
enum class Scope : unsigned char { Outer, Binder, Inner };

struct Form {
  const char* name;
  int count;
  Scope scopes[5];
  int when_arg;        // -1 when unguarded
  int when_kind;       // 1 name, 2 text
  const char* binds[4];
  int bind_count;
};

inline const Form FORMS[] = {
  {"ALL", 2, {Scope::Outer, Scope::Inner, Scope::Outer, Scope::Outer, Scope::Outer}, -1, 0, {"_", "_K", nullptr, nullptr}, 2},
  {"ALL", 3, {Scope::Outer, Scope::Binder, Scope::Inner, Scope::Outer, Scope::Outer}, -1, 0, {"_K", nullptr, nullptr, nullptr}, 1},
  {"ANY", 2, {Scope::Outer, Scope::Inner, Scope::Outer, Scope::Outer, Scope::Outer}, -1, 0, {"_", "_K", nullptr, nullptr}, 2},
  {"ANY", 3, {Scope::Outer, Scope::Binder, Scope::Inner, Scope::Outer, Scope::Outer}, -1, 0, {"_K", nullptr, nullptr, nullptr}, 1},
  {"BUCKET", 2, {Scope::Outer, Scope::Inner, Scope::Outer, Scope::Outer, Scope::Outer}, -1, 0, {"_", "_K", nullptr, nullptr}, 2},
  {"BUCKET", 3, {Scope::Outer, Scope::Inner, Scope::Inner, Scope::Outer, Scope::Outer}, -1, 0, {"_", "_K", nullptr, nullptr}, 2},
  {"BUCKET", 4, {Scope::Outer, Scope::Binder, Scope::Inner, Scope::Inner, Scope::Outer}, -1, 0, {"_K", nullptr, nullptr, nullptr}, 1},
  {"FILTER", 2, {Scope::Outer, Scope::Inner, Scope::Outer, Scope::Outer, Scope::Outer}, -1, 0, {"_", "_K", nullptr, nullptr}, 2},
  {"FILTER", 3, {Scope::Outer, Scope::Binder, Scope::Inner, Scope::Outer, Scope::Outer}, -1, 0, {"_K", nullptr, nullptr, nullptr}, 1},
  {"LINK", 3, {Scope::Outer, Scope::Outer, Scope::Inner, Scope::Outer, Scope::Outer}, -1, 0, {"_", "_1", "_2", "_K"}, 4},
  {"LINK", 5, {Scope::Outer, Scope::Outer, Scope::Binder, Scope::Binder, Scope::Inner}, -1, 0, {"_", "_1", "_2", "_K"}, 4},
  {"LINK_LEFT", 3, {Scope::Outer, Scope::Outer, Scope::Inner, Scope::Outer, Scope::Outer}, -1, 0, {"_", "_1", "_2", "_K"}, 4},
  {"LINK_LEFT", 5, {Scope::Outer, Scope::Outer, Scope::Binder, Scope::Binder, Scope::Inner}, -1, 0, {"_", "_1", "_2", "_K"}, 4},
  {"MAP", 2, {Scope::Outer, Scope::Inner, Scope::Outer, Scope::Outer, Scope::Outer}, -1, 0, {"_", "_K", nullptr, nullptr}, 2},
  {"MAP", 3, {Scope::Outer, Scope::Binder, Scope::Inner, Scope::Outer, Scope::Outer}, -1, 0, {"_K", nullptr, nullptr, nullptr}, 1},
  {"SORT", 1, {Scope::Outer, Scope::Outer, Scope::Outer, Scope::Outer, Scope::Outer}, -1, 0, {"_", "_K", nullptr, nullptr}, 2},
  {"SORT", 2, {Scope::Outer, Scope::Inner, Scope::Outer, Scope::Outer, Scope::Outer}, -1, 0, {"_", "_K", nullptr, nullptr}, 2},
  {"SORT", 3, {Scope::Outer, Scope::Binder, Scope::Inner, Scope::Outer, Scope::Outer}, -1, 0, {"_K", nullptr, nullptr, nullptr}, 1},
  {"SORT_BY", 2, {Scope::Outer, Scope::Inner, Scope::Outer, Scope::Outer, Scope::Outer}, -1, 0, {"_", "_K", nullptr, nullptr}, 2},
  {"SORT_BY", 3, {Scope::Outer, Scope::Inner, Scope::Outer, Scope::Outer, Scope::Outer}, 2, 2, {"_", "_K", nullptr, nullptr}, 2},
  {"SORT_BY", 3, {Scope::Outer, Scope::Binder, Scope::Inner, Scope::Outer, Scope::Outer}, 1, 1, {"_K", nullptr, nullptr, nullptr}, 1},
  {"SORT_BY", 3, {Scope::Outer, Scope::Inner, Scope::Outer, Scope::Outer, Scope::Outer}, -1, 0, {"_", "_K", nullptr, nullptr}, 2},
  {"SORT_BY", 4, {Scope::Outer, Scope::Binder, Scope::Inner, Scope::Outer, Scope::Outer}, -1, 0, {"_K", nullptr, nullptr, nullptr}, 1},
  {"SORT_DESC", 1, {Scope::Outer, Scope::Outer, Scope::Outer, Scope::Outer, Scope::Outer}, -1, 0, {"_", "_K", nullptr, nullptr}, 2},
  {"SORT_DESC", 2, {Scope::Outer, Scope::Inner, Scope::Outer, Scope::Outer, Scope::Outer}, -1, 0, {"_", "_K", nullptr, nullptr}, 2},
  {"SORT_DESC", 3, {Scope::Outer, Scope::Binder, Scope::Inner, Scope::Outer, Scope::Outer}, -1, 0, {"_K", nullptr, nullptr, nullptr}, 1},
  {"SUM", 2, {Scope::Outer, Scope::Inner, Scope::Outer, Scope::Outer, Scope::Outer}, -1, 0, {"_", "_K", nullptr, nullptr}, 2},
  {"SUM", 3, {Scope::Outer, Scope::Binder, Scope::Inner, Scope::Outer, Scope::Outer}, -1, 0, {"_K", nullptr, nullptr, nullptr}, 1},
  {"TOP", 2, {Scope::Outer, Scope::Outer, Scope::Outer, Scope::Outer, Scope::Outer}, -1, 0, {"_", "_K", nullptr, nullptr}, 2},
  {"TOP", 3, {Scope::Outer, Scope::Inner, Scope::Outer, Scope::Outer, Scope::Outer}, -1, 0, {"_", "_K", nullptr, nullptr}, 2},
  {"TOP", 4, {Scope::Outer, Scope::Binder, Scope::Inner, Scope::Outer, Scope::Outer}, -1, 0, {"_K", nullptr, nullptr, nullptr}, 1},
  {"TOP_BY", 3, {Scope::Outer, Scope::Inner, Scope::Outer, Scope::Outer, Scope::Outer}, -1, 0, {"_", "_K", nullptr, nullptr}, 2},
  {"TOP_BY", 4, {Scope::Outer, Scope::Inner, Scope::Outer, Scope::Outer, Scope::Outer}, 2, 2, {"_", "_K", nullptr, nullptr}, 2},
  {"TOP_BY", 4, {Scope::Outer, Scope::Binder, Scope::Inner, Scope::Outer, Scope::Outer}, 1, 1, {"_K", nullptr, nullptr, nullptr}, 1},
  {"TOP_BY", 4, {Scope::Outer, Scope::Inner, Scope::Outer, Scope::Outer, Scope::Outer}, -1, 0, {"_", "_K", nullptr, nullptr}, 2},
  {"TOP_BY", 5, {Scope::Outer, Scope::Binder, Scope::Inner, Scope::Outer, Scope::Outer}, -1, 0, {"_K", nullptr, nullptr, nullptr}, 1},
  {"TOP_DESC", 2, {Scope::Outer, Scope::Outer, Scope::Outer, Scope::Outer, Scope::Outer}, -1, 0, {"_", "_K", nullptr, nullptr}, 2},
  {"TOP_DESC", 3, {Scope::Outer, Scope::Inner, Scope::Outer, Scope::Outer, Scope::Outer}, -1, 0, {"_", "_K", nullptr, nullptr}, 2},
  {"TOP_DESC", 4, {Scope::Outer, Scope::Binder, Scope::Inner, Scope::Outer, Scope::Outer}, -1, 0, {"_K", nullptr, nullptr, nullptr}, 1},
};

inline constexpr int FORM_COUNT = 39;

// Classification (spec/builtins.md): the pipeline steps (whether each keeps
// its rows as they are, and whether it sorts), where each regex builtin takes
// its pattern and its flags, how the SQL translators type a builtin's
// arguments (numeric positions; whether a BIN or a BOOL argument is accepted),
// and the builtins whose result is a list. Hosts classify through these
// rather than keeping lists of their own.
struct PipelineStep {
  const char* name;
  bool keeps_rows;
  bool sorts;
};

inline const PipelineStep PIPELINE_STEPS[] = {
  {"BUCKET", false, false},
  {"DEDUPE", true, false},
  {"DISTINCT", true, false},
  {"DROP", true, false},
  {"FILTER", true, false},
  {"LINK", false, false},
  {"LINK_LEFT", false, false},
  {"MAP", false, false},
  {"SELECT_COLS", false, false},
  {"SORT", true, true},
  {"SORT_BY", true, true},
  {"SORT_DESC", true, true},
  {"TAKE", true, false},
  {"TOP", true, true},
  {"TOP_BY", true, true},
  {"TOP_DESC", true, true},
};

inline constexpr int PIPELINE_STEP_COUNT = 16;

struct RegexCall {
  const char* name;
  int pattern;
  int flags;
};

inline const RegexCall REGEX_CALLS[] = {
  {"RFIND", 0, 2},
  {"RGROUPS", 0, 2},
  {"RMATCH", 0, 2},
  {"RREPLACE", 0, 3},
};

inline constexpr int REGEX_CALL_COUNT = 4;

// numeric_all: every argument is a number; otherwise numeric[0..numeric_count).
struct SqlArgs {
  const char* name;
  bool numeric_all;
  int numeric[4];
  int numeric_count;
  bool bin;
  bool boolean;
};

inline const SqlArgs SQL_ARGS[] = {
  {"ABS", false, {0, -1, -1, -1}, 1, false, false},
  {"BLEN", false, {-1, -1, -1, -1}, 0, true, false},
  {"CANON", false, {0, -1, -1, -1}, 1, false, false},
  {"CEIL", false, {0, -1, -1, -1}, 1, false, false},
  {"CHAR", false, {0, -1, -1, -1}, 1, false, false},
  {"CRC32", false, {-1, -1, -1, -1}, 0, true, false},
  {"ENCODE_BASE64", false, {-1, -1, -1, -1}, 0, true, false},
  {"FIND", false, {2, -1, -1, -1}, 1, false, false},
  {"FLOOR", false, {0, -1, -1, -1}, 1, false, false},
  {"FROM_UTF8", false, {-1, -1, -1, -1}, 0, true, false},
  {"ISNUM", false, {-1, -1, -1, -1}, 0, true, true},
  {"LEFT", false, {1, -1, -1, -1}, 1, false, false},
  {"MAX", true, {-1, -1, -1, -1}, 0, false, false},
  {"MIN", true, {-1, -1, -1, -1}, 0, false, false},
  {"PADL", false, {1, -1, -1, -1}, 1, false, false},
  {"PADR", false, {1, -1, -1, -1}, 1, false, false},
  {"POWER", false, {0, 1, -1, -1}, 2, false, false},
  {"REPEAT", false, {1, -1, -1, -1}, 1, false, false},
  {"RIGHT", false, {1, -1, -1, -1}, 1, false, false},
  {"ROUND", false, {0, 1, -1, -1}, 2, false, false},
  {"SIGN", false, {0, -1, -1, -1}, 1, false, false},
  {"SUBSTR", false, {1, 2, -1, -1}, 2, false, false},
  {"TO_HEX", false, {-1, -1, -1, -1}, 0, true, false},
  {"TO_UTF8", false, {-1, -1, -1, -1}, 0, true, false},
  {"TRUNC", false, {0, -1, -1, -1}, 1, false, false},
};

inline constexpr int SQL_ARGS_COUNT = 25;

inline const char* const YIELDS_LIST[] = {"BTL", "BUCKET", "DEDUPE", "DISTINCT", "DROP", "FILTER", "INDEXES", "LINK", "LINK_LEFT", "LIST", "MAP", "RECORD", "RGROUPS", "SELECT_COLS", "SORT", "SORT_BY", "SORT_DESC", "SPLIT", "TAKE", "TOP", "TOP_BY", "TOP_DESC"};

inline constexpr int YIELDS_LIST_COUNT = 22;

}  // namespace sel_builtin_manifest
