// GENERATED by tools/gen-math-ops.mjs from spec/math-ops.json — do not edit; edit the manifest and regenerate.
//
// What the math plan compiles: one entry per operation with its source kind
// (1 binary operator, 2 prefix operator, 3 builtin), its token, its operand
// count (1, 2, or 0 for a left fold of one or more) and the auxiliary error
// position argument (-1 when none). sel.cpp maps each name to its MathOp and
// refuses to start if one is missing.
#pragma once

namespace sel_math_ops {

struct Op {
  const char* name;
  int kind;
  const char* token;
  int arity;
  int aux;
};

inline const Op OPS[] = {
  {"ADD", 1, "+", 2, -1},
  {"SUB", 1, "-", 2, -1},
  {"MUL", 1, "*", 2, -1},
  {"DIV", 1, "/", 2, -1},
  {"MOD", 1, "%", 2, -1},
  {"NEG", 2, "NEG", 1, -1},
  {"ABS", 3, "ABS", 1, -1},
  {"SIGN", 3, "SIGN", 1, -1},
  {"CEIL", 3, "CEIL", 1, -1},
  {"FLOOR", 3, "FLOOR", 1, -1},
  {"TRUNC", 3, "TRUNC", 1, -1},
  {"ROUND", 3, "ROUND", 2, 1},
  {"POWER", 3, "POWER", 2, 1},
  {"MIN", 3, "MIN", 0, -1},
  {"MAX", 3, "MAX", 0, -1},
};

inline constexpr int COUNT = 15;

}  // namespace sel_math_ops
