// GENERATED by tools/gen-lexicon.mjs from spec/lexicon.json — do not edit; edit the lexicon and regenerate.
//
// Reserved: the reserved words. Symbols: every symbol token, longest first.
// BP<Level>: each precedence level's binding power (higher binds tighter).
// Ops: one entry per operator, tightest level first; see spec/lexicon.md.
// Assoc is 'L', 'R', 'N', or 0 unless infix; Name is a prefix operator's
// node name; Relation indexes eq ne lt le gt ge (-1 when none); Compound is
// the binary operator a compound assignment applies.

package lexicon

type Fixity uint8

const (
	Infix Fixity = iota
	Prefix
	Postfix
)

type Family uint8

const (
	FamilyArith Family = iota
	FamilyConcat
	FamilyTextCompare
	FamilyDeepCompare
	FamilyCoalesce
	FamilyLogic
	FamilyBitwise
	FamilyAssign
	FamilySequence
	FamilyList
	FamilyCompare
	FamilyPostfix
)

type Op struct {
	Token        string
	Word         bool
	Fixity       Fixity
	Level        string
	BP           int
	Assoc        byte
	Family       Family
	Node         string
	Name         string
	Relation     int
	Compound     string
	ShortCircuit bool
}

var Reserved = []string{"TRUE", "FALSE", "NULL", "AND", "OR", "NOT", "XOR", "EQL", "IN", "BAND", "BOR", "BXOR"}

var Symbols = []string{"???", "$==", "$!=", "$<=", "$>=", ".>", "??", "==", "!=", "<=", ">=", "$<", "$>", "+=", "-=", "*=", "/=", "%=", "&=", "[", "-", "*", "/", "%", "+", "&", "<", ">", "=", ",", ";", "(", ")", "]"}

const (
	BPPostfix  = 17
	BPNeg      = 16
	BPMul      = 15
	BPAdd      = 14
	BPConcat   = 13
	BPBand     = 12
	BPBxor     = 11
	BPBor      = 10
	BPCoalesce = 9
	BPCompare  = 8
	BPNot      = 7
	BPAnd      = 6
	BPXor      = 5
	BPOr       = 4
	BPAssign   = 3
	BPList     = 2
	BPSeq      = 1
)

var Ops = []Op{
	{Token: "[", Word: false, Fixity: Postfix, Level: "POSTFIX", BP: 17, Assoc: 0, Family: FamilyPostfix, Node: "index", Name: "", Relation: -1, Compound: "", ShortCircuit: false},
	{Token: ".>", Word: false, Fixity: Postfix, Level: "POSTFIX", BP: 17, Assoc: 0, Family: FamilyPostfix, Node: "pipe", Name: "", Relation: -1, Compound: "", ShortCircuit: false},
	{Token: "-", Word: false, Fixity: Prefix, Level: "NEG", BP: 16, Assoc: 0, Family: FamilyArith, Node: "un", Name: "NEG", Relation: -1, Compound: "", ShortCircuit: false},
	{Token: "*", Word: false, Fixity: Infix, Level: "MUL", BP: 15, Assoc: 'L', Family: FamilyArith, Node: "bin", Name: "", Relation: -1, Compound: "", ShortCircuit: false},
	{Token: "/", Word: false, Fixity: Infix, Level: "MUL", BP: 15, Assoc: 'L', Family: FamilyArith, Node: "bin", Name: "", Relation: -1, Compound: "", ShortCircuit: false},
	{Token: "%", Word: false, Fixity: Infix, Level: "MUL", BP: 15, Assoc: 'L', Family: FamilyArith, Node: "bin", Name: "", Relation: -1, Compound: "", ShortCircuit: false},
	{Token: "+", Word: false, Fixity: Infix, Level: "ADD", BP: 14, Assoc: 'L', Family: FamilyArith, Node: "bin", Name: "", Relation: -1, Compound: "", ShortCircuit: false},
	{Token: "-", Word: false, Fixity: Infix, Level: "ADD", BP: 14, Assoc: 'L', Family: FamilyArith, Node: "bin", Name: "", Relation: -1, Compound: "", ShortCircuit: false},
	{Token: "&", Word: false, Fixity: Infix, Level: "CONCAT", BP: 13, Assoc: 'L', Family: FamilyConcat, Node: "bin", Name: "", Relation: -1, Compound: "", ShortCircuit: false},
	{Token: "BAND", Word: true, Fixity: Infix, Level: "BAND", BP: 12, Assoc: 'L', Family: FamilyBitwise, Node: "bin", Name: "", Relation: -1, Compound: "", ShortCircuit: false},
	{Token: "BXOR", Word: true, Fixity: Infix, Level: "BXOR", BP: 11, Assoc: 'L', Family: FamilyBitwise, Node: "bin", Name: "", Relation: -1, Compound: "", ShortCircuit: false},
	{Token: "BOR", Word: true, Fixity: Infix, Level: "BOR", BP: 10, Assoc: 'L', Family: FamilyBitwise, Node: "bin", Name: "", Relation: -1, Compound: "", ShortCircuit: false},
	{Token: "??", Word: false, Fixity: Infix, Level: "COALESCE", BP: 9, Assoc: 'R', Family: FamilyCoalesce, Node: "bin", Name: "", Relation: -1, Compound: "", ShortCircuit: true},
	{Token: "???", Word: false, Fixity: Infix, Level: "COALESCE", BP: 9, Assoc: 'R', Family: FamilyCoalesce, Node: "bin", Name: "", Relation: -1, Compound: "", ShortCircuit: true},
	{Token: "==", Word: false, Fixity: Infix, Level: "COMPARE", BP: 8, Assoc: 'N', Family: FamilyCompare, Node: "bin", Name: "", Relation: 0, Compound: "", ShortCircuit: false},
	{Token: "!=", Word: false, Fixity: Infix, Level: "COMPARE", BP: 8, Assoc: 'N', Family: FamilyCompare, Node: "bin", Name: "", Relation: 1, Compound: "", ShortCircuit: false},
	{Token: "<", Word: false, Fixity: Infix, Level: "COMPARE", BP: 8, Assoc: 'N', Family: FamilyCompare, Node: "bin", Name: "", Relation: 2, Compound: "", ShortCircuit: false},
	{Token: "<=", Word: false, Fixity: Infix, Level: "COMPARE", BP: 8, Assoc: 'N', Family: FamilyCompare, Node: "bin", Name: "", Relation: 3, Compound: "", ShortCircuit: false},
	{Token: ">", Word: false, Fixity: Infix, Level: "COMPARE", BP: 8, Assoc: 'N', Family: FamilyCompare, Node: "bin", Name: "", Relation: 4, Compound: "", ShortCircuit: false},
	{Token: ">=", Word: false, Fixity: Infix, Level: "COMPARE", BP: 8, Assoc: 'N', Family: FamilyCompare, Node: "bin", Name: "", Relation: 5, Compound: "", ShortCircuit: false},
	{Token: "$==", Word: false, Fixity: Infix, Level: "COMPARE", BP: 8, Assoc: 'N', Family: FamilyTextCompare, Node: "bin", Name: "", Relation: 0, Compound: "", ShortCircuit: false},
	{Token: "$!=", Word: false, Fixity: Infix, Level: "COMPARE", BP: 8, Assoc: 'N', Family: FamilyTextCompare, Node: "bin", Name: "", Relation: 1, Compound: "", ShortCircuit: false},
	{Token: "$<", Word: false, Fixity: Infix, Level: "COMPARE", BP: 8, Assoc: 'N', Family: FamilyTextCompare, Node: "bin", Name: "", Relation: 2, Compound: "", ShortCircuit: false},
	{Token: "$<=", Word: false, Fixity: Infix, Level: "COMPARE", BP: 8, Assoc: 'N', Family: FamilyTextCompare, Node: "bin", Name: "", Relation: 3, Compound: "", ShortCircuit: false},
	{Token: "$>", Word: false, Fixity: Infix, Level: "COMPARE", BP: 8, Assoc: 'N', Family: FamilyTextCompare, Node: "bin", Name: "", Relation: 4, Compound: "", ShortCircuit: false},
	{Token: "$>=", Word: false, Fixity: Infix, Level: "COMPARE", BP: 8, Assoc: 'N', Family: FamilyTextCompare, Node: "bin", Name: "", Relation: 5, Compound: "", ShortCircuit: false},
	{Token: "EQL", Word: true, Fixity: Infix, Level: "COMPARE", BP: 8, Assoc: 'N', Family: FamilyDeepCompare, Node: "bin", Name: "", Relation: -1, Compound: "", ShortCircuit: false},
	{Token: "IN", Word: true, Fixity: Infix, Level: "COMPARE", BP: 8, Assoc: 'N', Family: FamilyDeepCompare, Node: "bin", Name: "", Relation: -1, Compound: "", ShortCircuit: false},
	{Token: "NOT", Word: true, Fixity: Prefix, Level: "NOT", BP: 7, Assoc: 0, Family: FamilyLogic, Node: "un", Name: "NOT", Relation: -1, Compound: "", ShortCircuit: false},
	{Token: "AND", Word: true, Fixity: Infix, Level: "AND", BP: 6, Assoc: 'L', Family: FamilyLogic, Node: "bin", Name: "", Relation: -1, Compound: "", ShortCircuit: true},
	{Token: "XOR", Word: true, Fixity: Infix, Level: "XOR", BP: 5, Assoc: 'L', Family: FamilyLogic, Node: "bin", Name: "", Relation: -1, Compound: "", ShortCircuit: false},
	{Token: "OR", Word: true, Fixity: Infix, Level: "OR", BP: 4, Assoc: 'L', Family: FamilyLogic, Node: "bin", Name: "", Relation: -1, Compound: "", ShortCircuit: true},
	{Token: "=", Word: false, Fixity: Infix, Level: "ASSIGN", BP: 3, Assoc: 'R', Family: FamilyAssign, Node: "assign", Name: "", Relation: -1, Compound: "", ShortCircuit: false},
	{Token: "+=", Word: false, Fixity: Infix, Level: "ASSIGN", BP: 3, Assoc: 'R', Family: FamilyAssign, Node: "assign", Name: "", Relation: -1, Compound: "+", ShortCircuit: false},
	{Token: "-=", Word: false, Fixity: Infix, Level: "ASSIGN", BP: 3, Assoc: 'R', Family: FamilyAssign, Node: "assign", Name: "", Relation: -1, Compound: "-", ShortCircuit: false},
	{Token: "*=", Word: false, Fixity: Infix, Level: "ASSIGN", BP: 3, Assoc: 'R', Family: FamilyAssign, Node: "assign", Name: "", Relation: -1, Compound: "*", ShortCircuit: false},
	{Token: "/=", Word: false, Fixity: Infix, Level: "ASSIGN", BP: 3, Assoc: 'R', Family: FamilyAssign, Node: "assign", Name: "", Relation: -1, Compound: "/", ShortCircuit: false},
	{Token: "%=", Word: false, Fixity: Infix, Level: "ASSIGN", BP: 3, Assoc: 'R', Family: FamilyAssign, Node: "assign", Name: "", Relation: -1, Compound: "%", ShortCircuit: false},
	{Token: "&=", Word: false, Fixity: Infix, Level: "ASSIGN", BP: 3, Assoc: 'R', Family: FamilyAssign, Node: "assign", Name: "", Relation: -1, Compound: "&", ShortCircuit: false},
	{Token: ",", Word: false, Fixity: Infix, Level: "LIST", BP: 2, Assoc: 'L', Family: FamilyList, Node: "list", Name: "", Relation: -1, Compound: "", ShortCircuit: false},
	{Token: ";", Word: false, Fixity: Infix, Level: "SEQ", BP: 1, Assoc: 'L', Family: FamilySequence, Node: "seq", Name: "", Relation: -1, Compound: "", ShortCircuit: false},
}
