<?php

declare(strict_types=1);

namespace Sel\Builtins;

use Sel\Limits;

use function Sel\fail;

/**
 * The static exponential-ambiguity rule of spec/SPEC.md §7.8 ("Refused for its
 * running time"): the pattern's tree becomes a Glushkov position automaton and a
 * pattern a backtracking engine can be driven to exponential time on is refused
 * with E_REGEX_SYNTAX — the same follow edge generated twice, two different paths
 * from a state back to itself on one word (EDA), a nullable choice inside a loop,
 * an ambiguity budget above AMB_MAX — as is one whose analysis would exceed the
 * closed-form caps. Polynomial ambiguity is accepted on purpose.
 *
 * A port of tools/regex-ambiguity-ref.py: same construction, same counts, same
 * verdicts, and everything iterative but the walk over the tree (whose depth the
 * group-depth cap of 200 already bounds).
 *
 * Analysis nodes are arrays with a kind `k` and cached nullable `nl`, minimum and
 * maximum length `mn` / `mx`:
 *
 *   EPS                 nothing (an anchor, an empty branch)
 *   LET  ranges         one code point out of a normalised range set
 *   CAT  items          a sequence
 *   ALT  br             alternatives
 *   GRP  x              a group, transparent to the analysis
 *   REP  x, lo, hi      a quantified atom (hi null = unbounded)
 *   OPT  x              internal: optional, no cost of its own
 */
final class RegexAmbiguity
{
    private const MAX_CP = 0x10FFFF;
    private const UNROLL = 8;
    // The §7.8 caps, from spec/limits.json.
    private const P_MAX = Limits::REGEX_ANALYSIS_POSITIONS;   // positions
    private const E_MAX = Limits::REGEX_ANALYSIS_EDGES;       // follow edges
    private const D_MAX = Limits::REGEX_ANALYSIS_RANGES;      // sum over edges of the range count at the target
    private const Q_MAX = Limits::REGEX_ANALYSIS_PAIR_WORK;   // pair-graph work
    private const AMB_MAX = Limits::REGEX_AMBIGUITY_BUDGET;
    // A pair of positions packed into one int key, (a << KEY_SHIFT) | b: every
    // position is below P_MAX (2^17), so it fits in KEY_SHIFT bits.
    private const KEY_SHIFT = 17;
    private const KEY_MASK = (1 << self::KEY_SHIFT) - 1;
    private const SAT = 1 << 40;

    // The analysis of one pattern.
    /** @var list<list<array{int,int}>> range set per position; position 0 is the start */
    private array $cls = [[]];
    /** @var list<list<int>> follow edges per position */
    private array $succ = [[]];
    /** @var array<int,bool> follow edge (a << KEY_SHIFT | b) => generated by a synchronised loop */
    private array $tag = [];
    private int $edges = 0;
    private int $work = 0;
    private int $amb = 0;

    private string $pattern;
    /** @var array<string,mixed>|null */
    private ?array $pos;

    /** @param array<string,mixed>|null $pos */
    private function __construct(string $pattern, ?array $pos)
    {
        $this->pattern = $pattern;
        $this->pos = $pos;
    }

    /**
     * Refuses the pattern (E_REGEX_SYNTAX) or returns.
     *
     * @param array<string,mixed> $tree the parse tree of Regex::parse
     * @param array<string,mixed>|null $pos
     */
    public static function check(array $tree, bool $ignoreCase, string $pattern, ?array $pos): void
    {
        $a = new self($pattern, $pos);
        $a->analyse(self::convert($tree, $ignoreCase));
    }

    private function reject(string $why): never
    {
        fail(
            'E_REGEX_SYNTAX',
            'the pattern can take exponential time to match (' . $why . ') — spec §7.8; '
                . 'rewrite it so no input can be matched in two different ways by a loop'
                // A refusal of the whole pattern: offset 0 (spec/errors.md, "Message conventions").
                . ' (at offset 0 of /' . Regex::excerpt($this->pattern) . '/)',
            $this->pos,
        );
    }

    // --- range sets ------------------------------------------------------------

    /**
     * @param list<array{int,int}> $rs
     * @return list<array{int,int}> sorted, overlapping and adjacent ranges merged
     */
    private static function norm(array $rs): array
    {
        usort($rs, static fn (array $x, array $y): int => $x[0] <=> $y[0] ?: $x[1] <=> $y[1]);
        $out = [];
        $m = -1;
        foreach ($rs as [$a, $b]) {
            if ($m >= 0 && $a <= $out[$m][1] + 1) {
                if ($b > $out[$m][1]) $out[$m][1] = $b;
            } else {
                $out[] = [$a, $b];
                $m++;
            }
        }
        return $out;
    }

    /** @param list<array{int,int}> $rs @return list<array{int,int}> */
    private static function negate(array $rs): array
    {
        $out = [];
        $next = 0;
        foreach (self::norm($rs) as [$a, $b]) {
            if ($a > $next) $out[] = [$next, $a - 1];
            $next = $b + 1;
        }
        if ($next <= self::MAX_CP) $out[] = [$next, self::MAX_CP];
        return $out;
    }

    /** @param list<array{int,int}> $rs */
    private static function has(array $rs, int $c): bool
    {
        foreach ($rs as [$a, $b]) if ($a <= $c && $c <= $b) return true;
        return false;
    }

    /**
     * `i`: simple case folding restricted to what an ASCII pattern can reach — the
     * ASCII case mirror, plus U+212A with k/K and U+017F with s/S.
     *
     * @param list<array{int,int}> $rs
     * @return list<array{int,int}>
     */
    private static function fold(array $rs): array
    {
        $extra = [];
        foreach ($rs as [$a, $b]) {
            $lo = max($a, 0x41);
            $hi = min($b, 0x5A);
            if ($lo <= $hi) $extra[] = [$lo + 32, $hi + 32];
            $lo = max($a, 0x61);
            $hi = min($b, 0x7A);
            if ($lo <= $hi) $extra[] = [$lo - 32, $hi - 32];
        }
        $all = self::norm(array_merge($rs, $extra));
        $more = [];
        if (self::has($all, 0x6B) || self::has($all, 0x4B)) $more[] = [0x212A, 0x212A];
        if (self::has($all, 0x73) || self::has($all, 0x53)) $more[] = [0x17F, 0x17F];
        return self::norm(array_merge($all, $more));
    }

    /**
     * @param list<array{int,int}> $x
     * @param list<array{int,int}> $y
     */
    private static function intersects(array $x, array $y): bool
    {
        $i = 0;
        $j = 0;
        $nx = count($x);
        $ny = count($y);
        while ($i < $nx && $j < $ny) {
            if ($x[$i][1] < $y[$j][0]) $i++;
            elseif ($y[$j][1] < $x[$i][0]) $j++;
            else return true;
        }
        return false;
    }

    /**
     * The largest number of the given classes that share one code point.
     *
     * @param list<list<array{int,int}>> $classes
     */
    private static function maxCover(array $classes): int
    {
        $ev = [];
        foreach ($classes as $c) {
            foreach ($c as [$a, $b]) {
                $ev[] = [$a, 1];
                $ev[] = [$b + 1, -1];
            }
        }
        // Closings before openings at a shared point.
        usort($ev, static fn (array $x, array $y): int => $x[0] <=> $y[0] ?: $x[1] <=> $y[1]);
        $best = 0;
        $cur = 0;
        foreach ($ev as [, $d]) {
            $cur += $d;
            if ($cur > $best) $best = $cur;
        }
        return $best;
    }

    // --- the analysis tree -----------------------------------------------------

    /** @return array<string,mixed> */
    private static function eps(): array
    {
        return ['k' => 'EPS', 'nl' => true, 'mn' => 0, 'mx' => 0];
    }

    /** @param list<array<string,mixed>> $items @return array<string,mixed> */
    private static function cat(array $items): array
    {
        $nl = true;
        $mn = 0;
        $mx = 0;
        foreach ($items as $x) {
            $nl = $nl && $x['nl'];
            $mn += $x['mn'];
            $mx += $x['mx'];
        }
        return ['k' => 'CAT', 'items' => $items, 'nl' => $nl, 'mn' => min($mn, self::SAT), 'mx' => min($mx, self::SAT)];
    }

    /** @param array<string,mixed> $x @return array<string,mixed> */
    private static function opt(array $x): array
    {
        return ['k' => 'OPT', 'x' => $x, 'nl' => true, 'mn' => 0, 'mx' => $x['mx']];
    }

    /**
     * The parse tree of Regex::parse as the analysis tree. The class of a node is
     * the same set the reference computes: a class is folded and then negated, an
     * escape such as \W is negated and then folded — the two differ under `i`.
     *
     * @param array<string,mixed> $n
     * @return array<string,mixed>
     */
    private static function convert(array $n, bool $ic): array
    {
        switch ($n['k']) {
            case 'lit': case 'any': case 'cls':
                $rs = self::norm($n['ranges']);
                if ($n['k'] === 'cls' && $n['neg']) {
                    if ($ic && !empty($n['esc'])) {
                        $rs = self::fold(self::negate($rs));
                    } else {
                        $rs = self::negate($ic ? self::fold($rs) : $rs);
                    }
                } elseif ($ic) {
                    $rs = self::fold($rs);
                }
                return ['k' => 'LET', 'ranges' => $rs, 'nl' => false, 'mn' => 1, 'mx' => 1];
            case 'eps':
                return self::eps();
            case 'cat':
                if ($n['items'] === []) return self::eps();
                $items = [];
                foreach ($n['items'] as $it) $items[] = self::convert($it, $ic);
                return count($items) === 1 ? $items[0] : self::cat($items);
            case 'alt':
                $br = [];
                $nl = false;
                $mn = self::SAT;
                $mx = 0;
                foreach ($n['br'] as $b) {
                    $c = self::convert($b, $ic);
                    $br[] = $c;
                    $nl = $nl || $c['nl'];
                    $mn = min($mn, $c['mn']);
                    $mx = max($mx, $c['mx']);
                }
                return ['k' => 'ALT', 'br' => $br, 'nl' => $nl, 'mn' => $mn, 'mx' => $mx];
            case 'grp':
                $x = self::convert($n['x'], $ic);
                return ['k' => 'GRP', 'x' => $x, 'nl' => $x['nl'], 'mn' => $x['mn'], 'mx' => $x['mx']];
            default: // rep
                $x = self::convert($n['x'], $ic);
                $lo = $n['lo'];
                $hi = $n['hi'];
                if ($hi === 0 || $x['mx'] === 0) $mx = 0;
                elseif ($hi === null) $mx = self::SAT;
                else $mx = min(self::SAT, $hi * $x['mx']);
                return [
                    'k' => 'REP', 'x' => $x, 'lo' => $lo, 'hi' => $hi,
                    'nl' => $lo === 0 || $x['nl'],
                    'mn' => min(self::SAT, $lo * $x['mn']),
                    'mx' => $mx,
                ];
        }
    }

    // --- the position automaton ------------------------------------------------

    /**
     * @param list<int> $last positions
     * @param list<int> $first positions
     */
    private function join(array $last, array $first, bool $sync): void
    {
        $nl = count($last);
        $this->edges += $nl * count($first);
        $d = 0;
        foreach ($first as $q) $d += count($this->cls[$q]);
        $this->work += $nl * $d;
        if ($this->edges > self::E_MAX || $this->work > self::D_MAX) {
            $this->reject('the analysis would exceed its edge cap');
        }
        foreach ($last as $a) {
            foreach ($first as $b) {
                $key = ($a << self::KEY_SHIFT) | $b;
                if (isset($this->tag[$key])) {
                    if ($this->tag[$key] && $sync) continue;
                    $this->reject('a follow edge is generated twice');
                }
                $this->tag[$key] = $sync;
                $this->succ[$a][] = $b;
            }
        }
    }

    private function epsilon(int $k, bool $inLoop): void
    {
        if ($k <= 0) return;
        if ($inLoop) $this->reject('a nullable choice inside a loop');
        $this->amb += $k;
        if ($this->amb > self::AMB_MAX) $this->reject('the ambiguity budget is exceeded');
    }

    /**
     * @param array<string,mixed> $n
     * @return array{bool,list<int>,list<int>} nullable, first positions, last positions
     */
    private function walk(array $n, bool $inLoop): array
    {
        switch ($n['k']) {
            case 'EPS':
                return [true, [], []];
            case 'LET':
                if (count($this->cls) >= self::P_MAX) $this->reject('the analysis would exceed its position cap');
                $this->cls[] = $n['ranges'];
                $this->succ[] = [];
                $i = count($this->cls) - 1;
                return [false, [$i], [$i]];
            case 'GRP':
                return $this->walk($n['x'], $inLoop);
            case 'OPT':
                [, $f, $l] = $this->walk($n['x'], $inLoop);
                return [true, $f, $l];
            case 'ALT':
                $nullable = 0;
                foreach ($n['br'] as $b) if ($b['nl']) $nullable++;
                if ($nullable >= 2) $this->epsilon(self::ceilLog2($nullable), $inLoop);
                $f = [];
                $l = [];
                foreach ($n['br'] as $b) {
                    [, $f2, $l2] = $this->walk($b, $inLoop);
                    array_push($f, ...$f2);
                    array_push($l, ...$l2);
                }
                return [$nullable > 0, $f, $l];
            case 'CAT':
                $nl = true;
                $f = [];
                $l = [];
                foreach ($n['items'] as $it) {
                    [$n2, $f2, $l2] = $this->walk($it, $inLoop);
                    $this->join($l, $f2, false);
                    if ($nl) array_push($f, ...$f2);
                    $l = $n2 ? array_merge($l, $l2) : $l2;
                    $nl = $nl && $n2;
                }
                return [$nl, $f, $l];
            default: // REP
                $x = $n['x'];
                $lo = $n['lo'];
                $hi = $n['hi'];
                if ($hi === 0) return [true, [], []];
                if ($hi !== null && $hi <= self::UNROLL) {
                    if ($lo === 0 && $hi === 1 && $x['nl']) $this->epsilon(1, $inLoop);
                    $tail = self::eps();
                    for ($k = 0; $k < $hi - $lo; $k++) {
                        $tail = self::opt(self::cat([$x, $tail]));
                    }
                    $items = [];
                    for ($k = 0; $k < $lo; $k++) $items[] = $x;
                    $items[] = $tail;
                    return $this->walk(self::cat($items), $inLoop);
                }
                [, $f, $l] = $this->walk($x, true);
                $this->join($l, $f, $x['mn'] === $x['mx'] && $x['mx'] > 0 && $x['mx'] < self::SAT);
                return [$lo === 0 || $x['nl'], $f, $l];
        }
    }

    /** ceil(log2 k) for k >= 1 */
    private static function ceilLog2(int $k): int
    {
        $b = 0;
        $v = $k - 1;
        while ($v > 0) {
            $b++;
            $v >>= 1;
        }
        return $b;
    }

    /**
     * Iterative Tarjan. Returns the component id per node and whether the node lies
     * on a cycle (a component of more than one node, or a self-loop).
     *
     * @return array{list<int>,list<bool>}
     */
    private function scc(): array
    {
        $succ = $this->succ;
        $n = count($succ);
        $index = array_fill(0, $n, -1);
        $low = array_fill(0, $n, 0);
        $on = array_fill(0, $n, false);
        $comp = array_fill(0, $n, -1);
        $stack = [];
        $counter = 0;
        $ncomp = 0;
        for ($root = 0; $root < $n; $root++) {
            if ($index[$root] !== -1) continue;
            $work = [[$root, 0]];
            $index[$root] = $low[$root] = $counter++;
            $stack[] = $root;
            $on[$root] = true;
            while ($work !== []) {
                [$v, $ei] = $work[count($work) - 1];
                if ($ei < count($succ[$v])) {
                    $work[count($work) - 1] = [$v, $ei + 1];
                    $w = $succ[$v][$ei];
                    if ($index[$w] === -1) {
                        $index[$w] = $low[$w] = $counter++;
                        $stack[] = $w;
                        $on[$w] = true;
                        $work[] = [$w, 0];
                    } elseif ($on[$w]) {
                        if ($index[$w] < $low[$v]) $low[$v] = $index[$w];
                    }
                } else {
                    array_pop($work);
                    if ($work !== []) {
                        $u = $work[count($work) - 1][0];
                        if ($low[$v] < $low[$u]) $low[$u] = $low[$v];
                    }
                    if ($low[$v] === $index[$v]) {
                        do {
                            $w = array_pop($stack);
                            $on[$w] = false;
                            $comp[$w] = $ncomp;
                        } while ($w !== $v);
                        $ncomp++;
                    }
                }
            }
        }
        $size = array_fill(0, $ncomp, 0);
        for ($v = 0; $v < $n; $v++) $size[$comp[$v]]++;
        $cyc = [];
        for ($v = 0; $v < $n; $v++) {
            $cyc[$v] = $size[$comp[$v]] > 1 || in_array($v, $succ[$v], true);
        }
        return [$comp, $cyc];
    }

    /** @param array<string,mixed> $tree */
    private function analyse(array $tree): void
    {
        [, $first] = $this->walk($tree, false);
        $this->succ[0] = $first;
        $succ = $this->succ;
        $cls = $this->cls;
        $n = count($succ);
        [$comp, $cyc] = $this->scc();

        // (d) the budget: choices outside every cycle
        for ($p = 0; $p < $n; $p++) {
            if (!$cyc[$p] && count($succ[$p]) >= 2) {
                $classes = [];
                foreach ($succ[$p] as $q) $classes[] = $cls[$q];
                $m = self::maxCover($classes);
                if ($m >= 2) {
                    $this->amb += self::ceilLog2($m);
                    if ($this->amb > self::AMB_MAX) $this->reject('the ambiguity budget is exceeded');
                }
            }
        }

        // (b) EDA: two different paths from a state back to itself on one word
        $inScc = [];
        $d = static function (int $p) use (&$inScc, $succ, $comp): int {
            if (!isset($inScc[$p])) {
                $c = 0;
                foreach ($succ[$p] as $q) if ($comp[$q] === $comp[$p]) $c++;
                $inScc[$p] = $c;
            }
            return $inScc[$p];
        };
        $reach = [];
        $order = [];
        for ($q = 0; $q < $n; $q++) {
            if ($cyc[$q] && $cls[$q] !== []) {
                $key = ($q << self::KEY_SHIFT) | $q;
                $reach[$key] = true;
                $order[] = $key;
            }
        }
        $qWork = 0;
        $rev = [];
        $mask = self::KEY_MASK;
        while ($order !== []) {
            $node = array_pop($order);
            $p = $node >> self::KEY_SHIFT;
            $r = $node & $mask;
            $qWork += $d($p) * $d($r);
            if ($qWork > self::Q_MAX) $this->reject('the analysis would exceed its pair-graph cap');
            foreach ($succ[$p] as $p2) {
                if ($comp[$p2] !== $comp[$p]) continue;
                foreach ($succ[$r] as $r2) {
                    if ($comp[$r2] !== $comp[$p] || !self::intersects($cls[$p2], $cls[$r2])) continue;
                    $next = ($p2 << self::KEY_SHIFT) | $r2;
                    $rev[$next][] = $node;
                    if (!isset($reach[$next])) {
                        $reach[$next] = true;
                        $order[] = $next;
                    }
                }
            }
        }
        $back = [];
        $todo = [];
        foreach ($reach as $key => $_) {
            if (($key >> self::KEY_SHIFT) === ($key & $mask)) {
                $back[$key] = true;
                $todo[] = $key;
            }
        }
        while ($todo !== []) {
            $v = array_pop($todo);
            foreach ($rev[$v] ?? [] as $u) {
                if (!isset($back[$u])) {
                    $back[$u] = true;
                    $todo[] = $u;
                }
            }
        }
        foreach ($back as $key => $_) {
            if (($key >> self::KEY_SHIFT) !== ($key & $mask)) $this->reject('two different paths loop on one word (exponential ambiguity)');
        }
    }
}
