// GENERATED by tools/gen-builtins.mjs from spec/builtins.json — do not edit; edit the manifest and regenerate.
//
// One entry per builtin: min, max (None when variadic), lazy, binds, and
// the extra arity rule as a validator function or None.

#![allow(non_snake_case, unpredictable_function_pointer_comparisons)]

#[derive(Clone, Copy, Debug, PartialEq, Eq)]
pub struct Entry {
    pub name: &'static str,
    pub min: usize,
    pub max: Option<usize>,
    pub lazy: bool,
    pub binds: bool,
    pub arity_error: Option<fn(usize) -> Option<String>>,
}

#[derive(Clone, Copy, Debug, PartialEq, Eq)]
pub enum Scope {
    Outer,
    Binder,
    Inner,
}

#[derive(Clone, Copy, Debug, PartialEq, Eq)]
pub enum WhenKind {
    None,
    Name,
    Text,
}

#[derive(Clone, Debug)]
pub struct Form {
    pub name: &'static str,
    pub count: usize,
    pub scopes: &'static [Scope],
    pub when_arg: Option<usize>,
    pub when_kind: WhenKind,
    pub binds: &'static [&'static str],
}

fn arity_COND(n: usize) -> Option<String> {
    if n % 2 == 0 {
        Some(format!("{}{}{}", "COND takes condition/result pairs and a final default (an odd number of arguments), got ", n, ""))
    } else {
        None
    }
}

fn arity_LINK(n: usize) -> Option<String> {
    if !(n == 3 || n == 5) {
        Some(format!("{}{}{}", "LINK takes 3 or 5 arguments, got ", n, ""))
    } else {
        None
    }
}

fn arity_LINK_LEFT(n: usize) -> Option<String> {
    if !(n == 3 || n == 5) {
        Some(format!("{}{}{}", "LINK_LEFT takes 3 or 5 arguments, got ", n, ""))
    } else {
        None
    }
}

fn arity_RECORD(n: usize) -> Option<String> {
    if n % 2 != 0 {
        Some(format!("{}{}{}", "RECORD takes an even number of arguments (key-value pairs), got ", n, ""))
    } else {
        None
    }
}

pub const BUILTINS: &[(&str, Entry)] = &[
    ("ABORT", Entry { name: "ABORT", min: 1, max: Some(1), lazy: false, binds: false, arity_error: None }),
    ("ABS", Entry { name: "ABS", min: 1, max: Some(1), lazy: false, binds: false, arity_error: None }),
    ("ALL", Entry { name: "ALL", min: 2, max: Some(3), lazy: true, binds: true, arity_error: None }),
    ("ANY", Entry { name: "ANY", min: 2, max: Some(3), lazy: true, binds: true, arity_error: None }),
    ("BACKWARDS", Entry { name: "BACKWARDS", min: 1, max: Some(1), lazy: false, binds: false, arity_error: None }),
    ("BLEN", Entry { name: "BLEN", min: 1, max: Some(1), lazy: false, binds: false, arity_error: None }),
    ("BTL", Entry { name: "BTL", min: 1, max: Some(1), lazy: false, binds: false, arity_error: None }),
    ("BUCKET", Entry { name: "BUCKET", min: 2, max: Some(4), lazy: true, binds: true, arity_error: None }),
    ("CANON", Entry { name: "CANON", min: 1, max: Some(1), lazy: false, binds: false, arity_error: None }),
    ("CEIL", Entry { name: "CEIL", min: 1, max: Some(1), lazy: false, binds: false, arity_error: None }),
    ("CHAR", Entry { name: "CHAR", min: 1, max: Some(1), lazy: false, binds: false, arity_error: None }),
    ("COALESCE", Entry { name: "COALESCE", min: 1, max: None, lazy: true, binds: false, arity_error: None }),
    ("CODE", Entry { name: "CODE", min: 1, max: Some(1), lazy: false, binds: false, arity_error: None }),
    ("COND", Entry { name: "COND", min: 3, max: None, lazy: true, binds: false, arity_error: Some(arity_COND) }),
    ("COUNT", Entry { name: "COUNT", min: 1, max: Some(1), lazy: false, binds: false, arity_error: None }),
    ("CRC32", Entry { name: "CRC32", min: 1, max: Some(1), lazy: false, binds: false, arity_error: None }),
    ("DECODE_BASE64", Entry { name: "DECODE_BASE64", min: 1, max: Some(1), lazy: false, binds: false, arity_error: None }),
    ("DEDUPE", Entry { name: "DEDUPE", min: 1, max: Some(1), lazy: false, binds: false, arity_error: None }),
    ("DISTINCT", Entry { name: "DISTINCT", min: 1, max: Some(1), lazy: false, binds: false, arity_error: None }),
    ("DROP", Entry { name: "DROP", min: 2, max: Some(2), lazy: false, binds: false, arity_error: None }),
    ("ENCODE_BASE64", Entry { name: "ENCODE_BASE64", min: 1, max: Some(1), lazy: false, binds: false, arity_error: None }),
    ("FILTER", Entry { name: "FILTER", min: 2, max: Some(3), lazy: true, binds: true, arity_error: None }),
    ("FIND", Entry { name: "FIND", min: 2, max: Some(3), lazy: false, binds: false, arity_error: None }),
    ("FLOOR", Entry { name: "FLOOR", min: 1, max: Some(1), lazy: false, binds: false, arity_error: None }),
    ("FROM_HEX", Entry { name: "FROM_HEX", min: 1, max: Some(1), lazy: false, binds: false, arity_error: None }),
    ("FROM_UTF8", Entry { name: "FROM_UTF8", min: 1, max: Some(1), lazy: false, binds: false, arity_error: None }),
    ("GET", Entry { name: "GET", min: 2, max: Some(3), lazy: true, binds: false, arity_error: None }),
    ("HAS", Entry { name: "HAS", min: 2, max: Some(2), lazy: false, binds: false, arity_error: None }),
    ("IF", Entry { name: "IF", min: 2, max: Some(3), lazy: true, binds: false, arity_error: None }),
    ("INDEXES", Entry { name: "INDEXES", min: 1, max: Some(1), lazy: false, binds: false, arity_error: None }),
    ("ISNUM", Entry { name: "ISNUM", min: 1, max: Some(1), lazy: false, binds: false, arity_error: None }),
    ("IS_BLANK", Entry { name: "IS_BLANK", min: 1, max: Some(1), lazy: false, binds: false, arity_error: None }),
    ("IS_NOT_NULL", Entry { name: "IS_NOT_NULL", min: 1, max: Some(1), lazy: false, binds: false, arity_error: None }),
    ("IS_NULL", Entry { name: "IS_NULL", min: 1, max: Some(1), lazy: false, binds: false, arity_error: None }),
    ("IS_PRESENT", Entry { name: "IS_PRESENT", min: 1, max: Some(1), lazy: false, binds: false, arity_error: None }),
    ("JOIN", Entry { name: "JOIN", min: 2, max: Some(2), lazy: false, binds: false, arity_error: None }),
    ("LEFT", Entry { name: "LEFT", min: 2, max: Some(2), lazy: false, binds: false, arity_error: None }),
    ("LEN", Entry { name: "LEN", min: 1, max: Some(1), lazy: false, binds: false, arity_error: None }),
    ("LINK", Entry { name: "LINK", min: 3, max: Some(5), lazy: true, binds: true, arity_error: Some(arity_LINK) }),
    ("LINK_LEFT", Entry { name: "LINK_LEFT", min: 3, max: Some(5), lazy: true, binds: true, arity_error: Some(arity_LINK_LEFT) }),
    ("LIST", Entry { name: "LIST", min: 0, max: None, lazy: false, binds: false, arity_error: None }),
    ("LOWER", Entry { name: "LOWER", min: 1, max: Some(1), lazy: false, binds: false, arity_error: None }),
    ("LTB", Entry { name: "LTB", min: 1, max: Some(1), lazy: false, binds: false, arity_error: None }),
    ("LTRIM", Entry { name: "LTRIM", min: 1, max: Some(1), lazy: false, binds: false, arity_error: None }),
    ("MAP", Entry { name: "MAP", min: 2, max: Some(3), lazy: true, binds: true, arity_error: None }),
    ("MAX", Entry { name: "MAX", min: 1, max: None, lazy: false, binds: false, arity_error: None }),
    ("MIN", Entry { name: "MIN", min: 1, max: None, lazy: false, binds: false, arity_error: None }),
    ("PADL", Entry { name: "PADL", min: 3, max: Some(3), lazy: false, binds: false, arity_error: None }),
    ("PADR", Entry { name: "PADR", min: 3, max: Some(3), lazy: false, binds: false, arity_error: None }),
    ("PATH", Entry { name: "PATH", min: 2, max: Some(3), lazy: true, binds: false, arity_error: None }),
    ("POWER", Entry { name: "POWER", min: 2, max: Some(2), lazy: false, binds: false, arity_error: None }),
    ("RECORD", Entry { name: "RECORD", min: 0, max: None, lazy: false, binds: false, arity_error: Some(arity_RECORD) }),
    ("REPEAT", Entry { name: "REPEAT", min: 2, max: Some(2), lazy: false, binds: false, arity_error: None }),
    ("REPLACE", Entry { name: "REPLACE", min: 3, max: Some(3), lazy: false, binds: false, arity_error: None }),
    ("RFIND", Entry { name: "RFIND", min: 2, max: Some(3), lazy: false, binds: false, arity_error: None }),
    ("RGROUPS", Entry { name: "RGROUPS", min: 2, max: Some(3), lazy: false, binds: false, arity_error: None }),
    ("RIGHT", Entry { name: "RIGHT", min: 2, max: Some(2), lazy: false, binds: false, arity_error: None }),
    ("RMATCH", Entry { name: "RMATCH", min: 2, max: Some(3), lazy: false, binds: false, arity_error: None }),
    ("ROUND", Entry { name: "ROUND", min: 2, max: Some(2), lazy: false, binds: false, arity_error: None }),
    ("RREPLACE", Entry { name: "RREPLACE", min: 3, max: Some(4), lazy: false, binds: false, arity_error: None }),
    ("RTRIM", Entry { name: "RTRIM", min: 1, max: Some(1), lazy: false, binds: false, arity_error: None }),
    ("SELECT_COLS", Entry { name: "SELECT_COLS", min: 2, max: None, lazy: false, binds: false, arity_error: None }),
    ("SIGN", Entry { name: "SIGN", min: 1, max: Some(1), lazy: false, binds: false, arity_error: None }),
    ("SORT", Entry { name: "SORT", min: 1, max: Some(3), lazy: true, binds: true, arity_error: None }),
    ("SORT_BY", Entry { name: "SORT_BY", min: 2, max: Some(4), lazy: true, binds: true, arity_error: None }),
    ("SORT_DESC", Entry { name: "SORT_DESC", min: 1, max: Some(3), lazy: true, binds: true, arity_error: None }),
    ("SPLIT", Entry { name: "SPLIT", min: 2, max: Some(2), lazy: false, binds: false, arity_error: None }),
    ("SUBSTR", Entry { name: "SUBSTR", min: 2, max: Some(3), lazy: false, binds: false, arity_error: None }),
    ("SUM", Entry { name: "SUM", min: 2, max: Some(3), lazy: true, binds: true, arity_error: None }),
    ("TAKE", Entry { name: "TAKE", min: 2, max: Some(2), lazy: false, binds: false, arity_error: None }),
    ("TOP", Entry { name: "TOP", min: 2, max: Some(4), lazy: true, binds: true, arity_error: None }),
    ("TOP_BY", Entry { name: "TOP_BY", min: 3, max: Some(5), lazy: true, binds: true, arity_error: None }),
    ("TOP_DESC", Entry { name: "TOP_DESC", min: 2, max: Some(4), lazy: true, binds: true, arity_error: None }),
    ("TO_HEX", Entry { name: "TO_HEX", min: 1, max: Some(1), lazy: false, binds: false, arity_error: None }),
    ("TO_UTF8", Entry { name: "TO_UTF8", min: 1, max: Some(1), lazy: false, binds: false, arity_error: None }),
    ("TRIM", Entry { name: "TRIM", min: 1, max: Some(1), lazy: false, binds: false, arity_error: None }),
    ("TRUNC", Entry { name: "TRUNC", min: 1, max: Some(1), lazy: false, binds: false, arity_error: None }),
    ("UPPER", Entry { name: "UPPER", min: 1, max: Some(1), lazy: false, binds: false, arity_error: None }),
];

pub const BINDING_FORMS: &[(&str, &[Form])] = &[
    ("ALL", &[
        Form { name: "ALL", count: 2, scopes: &[Scope::Outer, Scope::Inner], when_arg: None, when_kind: WhenKind::None, binds: &["_", "_K"] },
        Form { name: "ALL", count: 3, scopes: &[Scope::Outer, Scope::Binder, Scope::Inner], when_arg: None, when_kind: WhenKind::None, binds: &["_K"] },
    ]),
    ("ANY", &[
        Form { name: "ANY", count: 2, scopes: &[Scope::Outer, Scope::Inner], when_arg: None, when_kind: WhenKind::None, binds: &["_", "_K"] },
        Form { name: "ANY", count: 3, scopes: &[Scope::Outer, Scope::Binder, Scope::Inner], when_arg: None, when_kind: WhenKind::None, binds: &["_K"] },
    ]),
    ("BUCKET", &[
        Form { name: "BUCKET", count: 2, scopes: &[Scope::Outer, Scope::Inner], when_arg: None, when_kind: WhenKind::None, binds: &["_", "_K"] },
        Form { name: "BUCKET", count: 3, scopes: &[Scope::Outer, Scope::Inner, Scope::Inner], when_arg: None, when_kind: WhenKind::None, binds: &["_", "_K"] },
        Form { name: "BUCKET", count: 4, scopes: &[Scope::Outer, Scope::Binder, Scope::Inner, Scope::Inner], when_arg: None, when_kind: WhenKind::None, binds: &["_K"] },
    ]),
    ("FILTER", &[
        Form { name: "FILTER", count: 2, scopes: &[Scope::Outer, Scope::Inner], when_arg: None, when_kind: WhenKind::None, binds: &["_", "_K"] },
        Form { name: "FILTER", count: 3, scopes: &[Scope::Outer, Scope::Binder, Scope::Inner], when_arg: None, when_kind: WhenKind::None, binds: &["_K"] },
    ]),
    ("LINK", &[
        Form { name: "LINK", count: 3, scopes: &[Scope::Outer, Scope::Outer, Scope::Inner], when_arg: None, when_kind: WhenKind::None, binds: &["_", "_1", "_2", "_K"] },
        Form { name: "LINK", count: 5, scopes: &[Scope::Outer, Scope::Outer, Scope::Binder, Scope::Binder, Scope::Inner], when_arg: None, when_kind: WhenKind::None, binds: &["_", "_1", "_2", "_K"] },
    ]),
    ("LINK_LEFT", &[
        Form { name: "LINK_LEFT", count: 3, scopes: &[Scope::Outer, Scope::Outer, Scope::Inner], when_arg: None, when_kind: WhenKind::None, binds: &["_", "_1", "_2", "_K"] },
        Form { name: "LINK_LEFT", count: 5, scopes: &[Scope::Outer, Scope::Outer, Scope::Binder, Scope::Binder, Scope::Inner], when_arg: None, when_kind: WhenKind::None, binds: &["_", "_1", "_2", "_K"] },
    ]),
    ("MAP", &[
        Form { name: "MAP", count: 2, scopes: &[Scope::Outer, Scope::Inner], when_arg: None, when_kind: WhenKind::None, binds: &["_", "_K"] },
        Form { name: "MAP", count: 3, scopes: &[Scope::Outer, Scope::Binder, Scope::Inner], when_arg: None, when_kind: WhenKind::None, binds: &["_K"] },
    ]),
    ("SORT", &[
        Form { name: "SORT", count: 1, scopes: &[Scope::Outer], when_arg: None, when_kind: WhenKind::None, binds: &["_", "_K"] },
        Form { name: "SORT", count: 2, scopes: &[Scope::Outer, Scope::Inner], when_arg: None, when_kind: WhenKind::None, binds: &["_", "_K"] },
        Form { name: "SORT", count: 3, scopes: &[Scope::Outer, Scope::Binder, Scope::Inner], when_arg: None, when_kind: WhenKind::None, binds: &["_K"] },
    ]),
    ("SORT_BY", &[
        Form { name: "SORT_BY", count: 2, scopes: &[Scope::Outer, Scope::Inner], when_arg: None, when_kind: WhenKind::None, binds: &["_", "_K"] },
        Form { name: "SORT_BY", count: 3, scopes: &[Scope::Outer, Scope::Inner, Scope::Outer], when_arg: Some(2), when_kind: WhenKind::Text, binds: &["_", "_K"] },
        Form { name: "SORT_BY", count: 3, scopes: &[Scope::Outer, Scope::Binder, Scope::Inner], when_arg: Some(1), when_kind: WhenKind::Name, binds: &["_K"] },
        Form { name: "SORT_BY", count: 3, scopes: &[Scope::Outer, Scope::Inner, Scope::Outer], when_arg: None, when_kind: WhenKind::None, binds: &["_", "_K"] },
        Form { name: "SORT_BY", count: 4, scopes: &[Scope::Outer, Scope::Binder, Scope::Inner, Scope::Outer], when_arg: None, when_kind: WhenKind::None, binds: &["_K"] },
    ]),
    ("SORT_DESC", &[
        Form { name: "SORT_DESC", count: 1, scopes: &[Scope::Outer], when_arg: None, when_kind: WhenKind::None, binds: &["_", "_K"] },
        Form { name: "SORT_DESC", count: 2, scopes: &[Scope::Outer, Scope::Inner], when_arg: None, when_kind: WhenKind::None, binds: &["_", "_K"] },
        Form { name: "SORT_DESC", count: 3, scopes: &[Scope::Outer, Scope::Binder, Scope::Inner], when_arg: None, when_kind: WhenKind::None, binds: &["_K"] },
    ]),
    ("SUM", &[
        Form { name: "SUM", count: 2, scopes: &[Scope::Outer, Scope::Inner], when_arg: None, when_kind: WhenKind::None, binds: &["_", "_K"] },
        Form { name: "SUM", count: 3, scopes: &[Scope::Outer, Scope::Binder, Scope::Inner], when_arg: None, when_kind: WhenKind::None, binds: &["_K"] },
    ]),
    ("TOP", &[
        Form { name: "TOP", count: 2, scopes: &[Scope::Outer, Scope::Outer], when_arg: None, when_kind: WhenKind::None, binds: &["_", "_K"] },
        Form { name: "TOP", count: 3, scopes: &[Scope::Outer, Scope::Inner, Scope::Outer], when_arg: None, when_kind: WhenKind::None, binds: &["_", "_K"] },
        Form { name: "TOP", count: 4, scopes: &[Scope::Outer, Scope::Binder, Scope::Inner, Scope::Outer], when_arg: None, when_kind: WhenKind::None, binds: &["_K"] },
    ]),
    ("TOP_BY", &[
        Form { name: "TOP_BY", count: 3, scopes: &[Scope::Outer, Scope::Inner, Scope::Outer], when_arg: None, when_kind: WhenKind::None, binds: &["_", "_K"] },
        Form { name: "TOP_BY", count: 4, scopes: &[Scope::Outer, Scope::Inner, Scope::Outer, Scope::Outer], when_arg: Some(2), when_kind: WhenKind::Text, binds: &["_", "_K"] },
        Form { name: "TOP_BY", count: 4, scopes: &[Scope::Outer, Scope::Binder, Scope::Inner, Scope::Outer], when_arg: Some(1), when_kind: WhenKind::Name, binds: &["_K"] },
        Form { name: "TOP_BY", count: 4, scopes: &[Scope::Outer, Scope::Inner, Scope::Outer, Scope::Outer], when_arg: None, when_kind: WhenKind::None, binds: &["_", "_K"] },
        Form { name: "TOP_BY", count: 5, scopes: &[Scope::Outer, Scope::Binder, Scope::Inner, Scope::Outer, Scope::Outer], when_arg: None, when_kind: WhenKind::None, binds: &["_K"] },
    ]),
    ("TOP_DESC", &[
        Form { name: "TOP_DESC", count: 2, scopes: &[Scope::Outer, Scope::Outer], when_arg: None, when_kind: WhenKind::None, binds: &["_", "_K"] },
        Form { name: "TOP_DESC", count: 3, scopes: &[Scope::Outer, Scope::Inner, Scope::Outer], when_arg: None, when_kind: WhenKind::None, binds: &["_", "_K"] },
        Form { name: "TOP_DESC", count: 4, scopes: &[Scope::Outer, Scope::Binder, Scope::Inner, Scope::Outer], when_arg: None, when_kind: WhenKind::None, binds: &["_K"] },
    ]),
];
