"""GENERATED by tools/gen-sql-map.mjs from sql/dialects/*.json — do not edit.
Regenerate with: node tools/gen-sql-map.mjs
The format is normative in sql/MAP.md; the design is in docs/SQL-TRANSLATION.md.

Every dialect, with its chain already flattened, so a lookup is a dict access
and nothing else. Runtime registration is what re-introduces the chain, and it
is the only thing that does.
"""

from __future__ import annotations

from typing import Any

DIALECTS: dict[str, dict[str, Any]] = {
    "ansi": {
        "dialect": "ansi",
        "extends": None,
        "version": "1999",
        "target": False,
        "lexical": {
            "identQuote": "\"",
            "identEscape": "\"\"",
            "textQuote": "'",
            "textEscape": {
                "'": "''",
            },
            "true": "TRUE",
            "false": "FALSE",
            "binaryLiteral": "X'{hex}'",
            "numericLiteral": "{0}",
            "textCollate": "",
            "numericCast": "CAST({0} AS DECIMAL(38,10))",
            "binaryCast": "CAST({0} AS BINARY)",
            "isTrue": "({0}) IS TRUE",
            "isNotTrue": "({0}) IS NOT TRUE",
            "placeholder": "?",
            "textCast": "CAST({0} AS CHAR)",
        },
        "ops": {
            "+": {
                "tpl": "({0} + {1})",
                "ret": "NUM",
            },
            "-": {
                "tpl": "({0} - {1})",
                "ret": "NUM",
            },
            "*": {
                "tpl": "({0} * {1})",
                "ret": "NUM",
            },
            "/": {
                "tpl": "({0} / {1})",
                "ret": "NUM",
                "caveat": "division-scale",
            },
            "%": {
                "tpl": "MOD({0}, {1})",
                "ret": "NUM",
            },
            "NEG": {
                "tpl": "(-{0})",
                "ret": "NUM",
            },
            "&": {
                "variants": {
                    "text": "({0} || {1})",
                },
                "ret": "@concat",
                "caveat": "concat-null",
            },
            "AND": {
                "tpl": "({0} AND {1})",
                "ret": "BOOL",
            },
            "OR": {
                "tpl": "({0} OR {1})",
                "ret": "BOOL",
            },
            "NOT": {
                "tpl": "(NOT {0})",
                "ret": "BOOL",
            },
            "XOR": {
                "tpl": "(({0}) <> ({1}))",
                "ret": "BOOL",
            },
            "==": {
                "variants": {
                    "num": "({0} = {1})",
                    "coerce": "({numericCast:0} = {numericCast:1})",
                },
                "ret": "BOOL",
            },
            "!=": {
                "variants": {
                    "num": "({0} <> {1})",
                    "coerce": "({numericCast:0} <> {numericCast:1})",
                },
                "ret": "BOOL",
            },
            "<": {
                "variants": {
                    "num": "({0} < {1})",
                    "coerce": "({numericCast:0} < {numericCast:1})",
                },
                "ret": "BOOL",
            },
            "<=": {
                "variants": {
                    "num": "({0} <= {1})",
                    "coerce": "({numericCast:0} <= {numericCast:1})",
                },
                "ret": "BOOL",
            },
            ">": {
                "variants": {
                    "num": "({0} > {1})",
                    "coerce": "({numericCast:0} > {numericCast:1})",
                },
                "ret": "BOOL",
            },
            ">=": {
                "variants": {
                    "num": "({0} >= {1})",
                    "coerce": "({numericCast:0} >= {numericCast:1})",
                },
                "ret": "BOOL",
            },
            "$==": {
                "variants": {
                    "text": "({0} = {1})",
                },
                "ret": "BOOL",
            },
            "$!=": {
                "variants": {
                    "text": "({0} <> {1})",
                },
                "ret": "BOOL",
            },
            "$<": {
                "variants": {
                    "text": "({0} < {1})",
                },
                "ret": "BOOL",
            },
            "$<=": {
                "variants": {
                    "text": "({0} <= {1})",
                },
                "ret": "BOOL",
            },
            "$>": {
                "variants": {
                    "text": "({0} > {1})",
                },
                "ret": "BOOL",
            },
            "$>=": {
                "variants": {
                    "text": "({0} >= {1})",
                },
                "ret": "BOOL",
            },
            "EQL": {
                "variants": {
                    "text": "({0} = {1})",
                },
                "ret": "BOOL",
            },
            "IN": {
                "variants": {
                    "scalar": "({0} = {1})",
                },
                "ret": "BOOL",
            },
            "BAND": "SQL's & is an integer operator; SEL's BAND is a byte-string operator over BIN of equal length, and no portable spelling of that exists",
            "BOR": "SQL's | is an integer operator; SEL's BOR is a byte-string operator over BIN of equal length, and no portable spelling of that exists",
            "BXOR": "SQL's ^ is an integer operator; SEL's BXOR is a byte-string operator over BIN of equal length, and no portable spelling of that exists",
        },
        "funcs": {
            "LEN": {
                "tpl": "CHAR_LENGTH({0})",
                "ret": "NUM",
            },
            "SUBSTR": {
                "tpl": {
                    "2": "SUBSTRING({0} FROM {1})",
                    "3": "SUBSTRING({0} FROM {1} FOR {2})",
                },
                "ret": "TEXT",
            },
            "UPPER": {
                "tpl": "UPPER({0})",
                "ret": "TEXT",
                "caveat": "unicode-case",
            },
            "LOWER": {
                "tpl": "LOWER({0})",
                "ret": "TEXT",
                "caveat": "unicode-case",
            },
            "TRIM": {
                "tpl": "TRIM(BOTH FROM {0})",
                "ret": "TEXT",
                "caveat": "trim-charset",
            },
            "LTRIM": {
                "tpl": "TRIM(LEADING FROM {0})",
                "ret": "TEXT",
                "caveat": "trim-charset",
            },
            "RTRIM": {
                "tpl": "TRIM(TRAILING FROM {0})",
                "ret": "TEXT",
                "caveat": "trim-charset",
            },
            "ABS": {
                "tpl": "ABS({0})",
                "ret": "NUM",
            },
            "CEIL": {
                "tpl": "CEIL({0})",
                "ret": "NUM",
            },
            "FLOOR": {
                "tpl": "FLOOR({0})",
                "ret": "NUM",
            },
            "POWER": {
                "tpl": "POWER({0}, {1})",
                "ret": "NUM",
                "caveat": "power-float",
            },
            "LEFT": "no ANSI spelling; each server has its own, so this is set per dialect",
            "RIGHT": "no ANSI spelling; each server has its own, so this is set per dialect",
            "FIND": "ANSI POSITION exists but takes no start offset and spells its arguments differently in every server",
            "REPLACE": "not ANSI; set per dialect",
            "SPLIT": "yields a list, and a SQL expression is a scalar",
            "BACKWARDS": "no ANSI spelling; set per dialect",
            "REPEAT": "not ANSI; set per dialect",
            "PADL": "not ANSI; set per dialect",
            "PADR": "not ANSI; set per dialect",
            "CHAR": "not ANSI; the code-point-to-character spelling differs per server and per charset",
            "CODE": "not ANSI; set per dialect",
            "SIGN": "not ANSI; set per dialect",
            "TRUNC": "not ANSI; ROUND-toward-zero is spelled differently in every server",
            "ROUND": "not ANSI as a two-argument scale function; set per dialect",
            "MIN": "SEL's MIN is a scalar over its arguments, not a column aggregate; the scalar form is LEAST or GREATEST and is not ANSI",
            "MAX": "SEL's MAX is a scalar over its arguments, not a column aggregate; the scalar form is LEAST or GREATEST and is not ANSI",
            "ISNUM": "would need a regex or a failure-tolerant cast, and neither is ANSI",
            "BLEN": "not ANSI; octet length of a text value depends on the server's charset handling",
            "TO_UTF8": "SEL's TEXT/BIN distinction has no SQL counterpart; a cast to a binary type is per dialect",
            "FROM_UTF8": "SEL's TEXT/BIN distinction has no SQL counterpart; a cast from a binary type is per dialect",
            "TO_HEX": "not ANSI; set per dialect",
            "FROM_HEX": "not ANSI; set per dialect",
            "ENCODE_BASE64": "not ANSI; set per dialect",
            "DECODE_BASE64": "not ANSI; set per dialect",
            "CRC32": "not ANSI; set per dialect",
            "BTL": "yields a list, and a SQL expression is a scalar",
            "LTB": "takes a list, and a SQL expression is a scalar",
            "RMATCH": "regular expressions are not ANSI; set per dialect",
            "RFIND": "regular expressions are not ANSI; set per dialect",
            "RREPLACE": "regular expressions are not ANSI; set per dialect",
            "RGROUPS": "yields a list, and a SQL expression is a scalar",
        },
        "skel": {
            "case": {
                "tpl": "CASE {branches} ELSE {else} END",
            },
            "caseBranch": {
                "tpl": "WHEN {cond} THEN {then}",
            },
            "all": {
                "tpl": "NOT EXISTS (SELECT 1 FROM {from} WHERE {corr} AND ({body}) IS NOT TRUE)",
            },
            "any": {
                "tpl": "EXISTS (SELECT 1 FROM {from} WHERE {corr} AND ({body}) IS TRUE)",
            },
            "sum": {
                "tpl": "(SELECT COALESCE(SUM({body}), 0) FROM {from} WHERE {corr})",
            },
            "count": {
                "tpl": "(SELECT COUNT(*) FROM {from} WHERE {corr})",
            },
            "inRelation": {
                "tpl": "({needle} IN (SELECT {body} FROM {from} WHERE {corr}))",
            },
            "join": "LISTAGG is SQL:2016 and is spelled differently by every server that has it",
        },
    },
    "mariadb": {
        "dialect": "mariadb",
        "extends": "mysql-family",
        "version": "10.5",
        "target": True,
        "lexical": {
            "identQuote": "`",
            "identEscape": "``",
            "textQuote": "'",
            "textEscape": {
                "'": "''",
                "\\": "\\\\",
            },
            "true": "TRUE",
            "false": "FALSE",
            "binaryLiteral": "X'{hex}'",
            "numericLiteral": "{0}",
            "textCollate": " COLLATE utf8mb4_bin",
            "numericCast": "CAST({0} AS DECIMAL(65,10))",
            "binaryCast": "CAST({0} AS BINARY)",
            "isTrue": "({0}) IS TRUE",
            "isNotTrue": "({0}) IS NOT TRUE",
            "placeholder": "?",
            "textCast": "CAST({0} AS CHAR)",
        },
        "ops": {
            "+": {
                "tpl": "({0} + {1})",
                "ret": "NUM",
            },
            "-": {
                "tpl": "({0} - {1})",
                "ret": "NUM",
            },
            "*": {
                "tpl": "({0} * {1})",
                "ret": "NUM",
                "caveat": "scale-limit",
            },
            "/": {
                "tpl": "({0} / {1})",
                "ret": "NUM",
                "caveat": "division-scale",
            },
            "%": {
                "tpl": "MOD({0}, {1})",
                "ret": "NUM",
            },
            "NEG": {
                "tpl": "(-{0})",
                "ret": "NUM",
            },
            "&": {
                "variants": {
                    "text": "CONCAT({0}, {1})",
                    "bin": "CONCAT({0}, {1})",
                },
                "ret": "@concat",
                "caveat": "concat-null",
            },
            "AND": {
                "tpl": "({0} AND {1})",
                "ret": "BOOL",
            },
            "OR": {
                "tpl": "({0} OR {1})",
                "ret": "BOOL",
            },
            "NOT": {
                "tpl": "(NOT {0})",
                "ret": "BOOL",
            },
            "XOR": {
                "tpl": "({0} XOR {1})",
                "ret": "BOOL",
            },
            "==": {
                "variants": {
                    "num": "({0} = {1})",
                    "coerce": "({numericCast:0} = {numericCast:1})",
                },
                "ret": "BOOL",
            },
            "!=": {
                "variants": {
                    "num": "({0} <> {1})",
                    "coerce": "({numericCast:0} <> {numericCast:1})",
                },
                "ret": "BOOL",
            },
            "<": {
                "variants": {
                    "num": "({0} < {1})",
                    "coerce": "({numericCast:0} < {numericCast:1})",
                },
                "ret": "BOOL",
            },
            "<=": {
                "variants": {
                    "num": "({0} <= {1})",
                    "coerce": "({numericCast:0} <= {numericCast:1})",
                },
                "ret": "BOOL",
            },
            ">": {
                "variants": {
                    "num": "({0} > {1})",
                    "coerce": "({numericCast:0} > {numericCast:1})",
                },
                "ret": "BOOL",
            },
            ">=": {
                "variants": {
                    "num": "({0} >= {1})",
                    "coerce": "({numericCast:0} >= {numericCast:1})",
                },
                "ret": "BOOL",
            },
            "$==": {
                "variants": {
                    "text": "({0} = {1})",
                },
                "ret": "BOOL",
            },
            "$!=": {
                "variants": {
                    "text": "({0} <> {1})",
                },
                "ret": "BOOL",
            },
            "$<": {
                "variants": {
                    "text": "({0} < {1})",
                },
                "ret": "BOOL",
            },
            "$<=": {
                "variants": {
                    "text": "({0} <= {1})",
                },
                "ret": "BOOL",
            },
            "$>": {
                "variants": {
                    "text": "({0} > {1})",
                },
                "ret": "BOOL",
            },
            "$>=": {
                "variants": {
                    "text": "({0} >= {1})",
                },
                "ret": "BOOL",
            },
            "EQL": {
                "variants": {
                    "text": "({0} = {1})",
                },
                "ret": "BOOL",
            },
            "IN": {
                "variants": {
                    "scalar": "({0} = {1})",
                },
                "ret": "BOOL",
            },
            "BAND": "SQL's & is an integer operator; SEL's BAND is a byte-string operator over BIN of equal length, and no portable spelling of that exists",
            "BOR": "SQL's | is an integer operator; SEL's BOR is a byte-string operator over BIN of equal length, and no portable spelling of that exists",
            "BXOR": "SQL's ^ is an integer operator; SEL's BXOR is a byte-string operator over BIN of equal length, and no portable spelling of that exists",
        },
        "funcs": {
            "LEN": {
                "tpl": "CHAR_LENGTH({0})",
                "ret": "NUM",
            },
            "SUBSTR": {
                "tpl": {
                    "2": "SUBSTRING({0}, {1})",
                    "3": "SUBSTRING({0}, {1}, {2})",
                },
                "ret": "TEXT",
            },
            "UPPER": {
                "tpl": "UPPER({0})",
                "ret": "TEXT",
                "caveat": "unicode-case",
            },
            "LOWER": {
                "tpl": "LOWER({0})",
                "ret": "TEXT",
                "caveat": "unicode-case",
            },
            "TRIM": {
                "tpl": "REGEXP_REPLACE({0}, '^[ \\\\t\\\\r\\\\n]+|[ \\\\t\\\\r\\\\n]+$', '')",
                "ret": "TEXT",
            },
            "LTRIM": {
                "tpl": "REGEXP_REPLACE({0}, '^[ \\\\t\\\\r\\\\n]+', '')",
                "ret": "TEXT",
            },
            "RTRIM": {
                "tpl": "REGEXP_REPLACE({0}, '[ \\\\t\\\\r\\\\n]+$', '')",
                "ret": "TEXT",
            },
            "ABS": {
                "tpl": "ABS({0})",
                "ret": "NUM",
            },
            "CEIL": {
                "tpl": "CEIL({0})",
                "ret": "NUM",
            },
            "FLOOR": {
                "tpl": "FLOOR({0})",
                "ret": "NUM",
            },
            "POWER": {
                "tpl": "POWER({0}, {1})",
                "ret": "NUM",
                "caveat": "power-float",
            },
            "LEFT": {
                "tpl": "LEFT({0}, {1})",
                "ret": "TEXT",
            },
            "RIGHT": {
                "tpl": "RIGHT({0}, {1})",
                "ret": "TEXT",
            },
            "FIND": {
                "tpl": {
                    "2": "INSTR({1}, {0})",
                    "3": "LOCATE({0}, {1}, {2})",
                },
                "ret": "NUM",
            },
            "REPLACE": {
                "tpl": "REPLACE({2}, {0}, {1})",
                "ret": "TEXT",
            },
            "SPLIT": "yields a list, and a SQL expression is a scalar",
            "BACKWARDS": {
                "tpl": "REVERSE({0})",
                "ret": "TEXT",
            },
            "REPEAT": {
                "tpl": "REPEAT({0}, {1})",
                "ret": "TEXT",
            },
            "PADL": {
                "tpl": "IF(CHAR_LENGTH({0}) >= {1}, {0}, LPAD({0}, {1}, {2}))",
                "ret": "TEXT",
            },
            "PADR": {
                "tpl": "IF(CHAR_LENGTH({0}) >= {1}, {0}, RPAD({0}, {1}, {2}))",
                "ret": "TEXT",
            },
            "CHAR": "CHAR(n USING utf8mb4) reads n as a byte sequence in that charset, not as a code point: CHAR(233 USING utf8mb4) is NULL because 0xE9 alone is not valid UTF-8, where SEL says the character is e-acute",
            "CODE": "ORD returns the first character's bytes read as an integer, not its code point; SEL's CODE is a code point",
            "SIGN": {
                "tpl": "SIGN({0})",
                "ret": "NUM",
            },
            "TRUNC": {
                "tpl": "TRUNCATE({0}, 0)",
                "ret": "NUM",
            },
            "ROUND": {
                "tpl": "ROUND({0}, {1})",
                "ret": "NUM",
                "caveat": "rounding-mode",
            },
            "MIN": {
                "tpl": {
                    "1": "{0}",
                    "*": "LEAST({*})",
                },
                "ret": "NUM",
                "caveat": "numeric-scale",
            },
            "MAX": {
                "tpl": {
                    "1": "{0}",
                    "*": "GREATEST({*})",
                },
                "ret": "NUM",
                "caveat": "numeric-scale",
            },
            "ISNUM": {
                "tpl": "({0} REGEXP '\\\\A-?[0-9]+(\\\\.[0-9]+)?\\\\z')",
                "ret": "BOOL",
            },
            "BLEN": {
                "tpl": "LENGTH({binaryCast:0})",
                "ret": "NUM",
            },
            "TO_UTF8": {
                "tpl": "CAST({0} AS BINARY)",
                "ret": "BIN",
            },
            "FROM_UTF8": {
                "tpl": "CONVERT({binaryCast:0} USING utf8mb4)",
                "ret": "TEXT",
            },
            "TO_HEX": {
                "tpl": "LOWER(HEX({binaryCast:0}))",
                "ret": "TEXT",
            },
            "FROM_HEX": {
                "tpl": "UNHEX({0})",
                "ret": "BIN",
            },
            "ENCODE_BASE64": {
                "tpl": "REPLACE(REPLACE(TO_BASE64({binaryCast:0}), CHAR(10), ''), CHAR(13), '')",
                "ret": "TEXT",
            },
            "DECODE_BASE64": {
                "tpl": "FROM_BASE64({0})",
                "ret": "BIN",
                "caveat": "input-laxity",
            },
            "CRC32": {
                "tpl": "LPAD(LOWER(HEX(CRC32({binaryCast:0}))), 8, '0')",
                "ret": "TEXT",
            },
            "BTL": "yields a list, and a SQL expression is a scalar",
            "LTB": "takes a list, and a SQL expression is a scalar",
            "RMATCH": {
                "tpl": "({1}{textCollate} REGEXP {0})",
                "arity": [2, 2],
                "ret": "BOOL",
                "caveat": "regex-engine",
            },
            "RFIND": {
                "tpl": "REGEXP_INSTR({1}{textCollate}, {0})",
                "arity": [2, 2],
                "ret": "NUM",
                "caveat": "regex-engine",
            },
            "RREPLACE": "SEL replacement syntax is $0-$9 and MariaDB's is \\1; rewriting one into the other is only possible when the replacement is a literal, which the map cannot express",
            "RGROUPS": "yields a list, and a SQL expression is a scalar",
        },
        "skel": {
            "case": {
                "tpl": "CASE {branches} ELSE {else} END",
            },
            "caseBranch": {
                "tpl": "WHEN {cond} THEN {then}",
            },
            "all": {
                "tpl": "NOT EXISTS (SELECT 1 FROM {from} WHERE {corr} AND ({body}) IS NOT TRUE)",
            },
            "any": {
                "tpl": "EXISTS (SELECT 1 FROM {from} WHERE {corr} AND ({body}) IS TRUE)",
            },
            "sum": {
                "tpl": "(SELECT COALESCE(SUM({body}), 0) FROM {from} WHERE {corr})",
            },
            "count": {
                "tpl": "(SELECT COUNT(*) FROM {from} WHERE {corr})",
            },
            "inRelation": {
                "tpl": "({needle} IN (SELECT {body} FROM {from} WHERE {corr}))",
            },
            "join": "GROUP_CONCAT does not specify an order without an ORDER BY, and a relation binding has no key to order by; SEL's JOIN concatenates in insertion order",
        },
    },
    "mysql": {
        "dialect": "mysql",
        "extends": "mysql-family",
        "version": "8.4",
        "target": True,
        "lexical": {
            "identQuote": "`",
            "identEscape": "``",
            "textQuote": "'",
            "textEscape": {
                "'": "''",
                "\\": "\\\\",
            },
            "true": "TRUE",
            "false": "FALSE",
            "binaryLiteral": "X'{hex}'",
            "numericLiteral": "{0}",
            "textCollate": " COLLATE utf8mb4_bin",
            "numericCast": "CAST({0} AS DECIMAL(65,10))",
            "binaryCast": "CAST({0} AS BINARY)",
            "isTrue": "({0}) IS TRUE",
            "isNotTrue": "({0}) IS NOT TRUE",
            "placeholder": "?",
            "textCast": "CAST({0} AS CHAR)",
        },
        "ops": {
            "+": {
                "tpl": "({0} + {1})",
                "ret": "NUM",
            },
            "-": {
                "tpl": "({0} - {1})",
                "ret": "NUM",
            },
            "*": {
                "tpl": "({0} * {1})",
                "ret": "NUM",
                "caveat": "scale-limit",
            },
            "/": {
                "tpl": "({0} / {1})",
                "ret": "NUM",
                "caveat": "division-scale",
            },
            "%": {
                "tpl": "MOD({0}, {1})",
                "ret": "NUM",
            },
            "NEG": {
                "tpl": "(-{0})",
                "ret": "NUM",
            },
            "&": {
                "variants": {
                    "text": "CONCAT({0}, {1})",
                    "bin": "CONCAT({0}, {1})",
                },
                "ret": "@concat",
                "caveat": "concat-null",
            },
            "AND": {
                "tpl": "({0} AND {1})",
                "ret": "BOOL",
            },
            "OR": {
                "tpl": "({0} OR {1})",
                "ret": "BOOL",
            },
            "NOT": {
                "tpl": "(NOT {0})",
                "ret": "BOOL",
            },
            "XOR": {
                "tpl": "({0} XOR {1})",
                "ret": "BOOL",
            },
            "==": {
                "variants": {
                    "num": "({0} = {1})",
                    "coerce": "({numericCast:0} = {numericCast:1})",
                },
                "ret": "BOOL",
            },
            "!=": {
                "variants": {
                    "num": "({0} <> {1})",
                    "coerce": "({numericCast:0} <> {numericCast:1})",
                },
                "ret": "BOOL",
            },
            "<": {
                "variants": {
                    "num": "({0} < {1})",
                    "coerce": "({numericCast:0} < {numericCast:1})",
                },
                "ret": "BOOL",
            },
            "<=": {
                "variants": {
                    "num": "({0} <= {1})",
                    "coerce": "({numericCast:0} <= {numericCast:1})",
                },
                "ret": "BOOL",
            },
            ">": {
                "variants": {
                    "num": "({0} > {1})",
                    "coerce": "({numericCast:0} > {numericCast:1})",
                },
                "ret": "BOOL",
            },
            ">=": {
                "variants": {
                    "num": "({0} >= {1})",
                    "coerce": "({numericCast:0} >= {numericCast:1})",
                },
                "ret": "BOOL",
            },
            "$==": {
                "variants": {
                    "text": "({0} = {1})",
                },
                "ret": "BOOL",
            },
            "$!=": {
                "variants": {
                    "text": "({0} <> {1})",
                },
                "ret": "BOOL",
            },
            "$<": {
                "variants": {
                    "text": "({0} < {1})",
                },
                "ret": "BOOL",
            },
            "$<=": {
                "variants": {
                    "text": "({0} <= {1})",
                },
                "ret": "BOOL",
            },
            "$>": {
                "variants": {
                    "text": "({0} > {1})",
                },
                "ret": "BOOL",
            },
            "$>=": {
                "variants": {
                    "text": "({0} >= {1})",
                },
                "ret": "BOOL",
            },
            "EQL": {
                "variants": {
                    "text": "({0} = {1})",
                },
                "ret": "BOOL",
            },
            "IN": {
                "variants": {
                    "scalar": "({0} = {1})",
                },
                "ret": "BOOL",
            },
            "BAND": "SQL's & is an integer operator; SEL's BAND is a byte-string operator over BIN of equal length, and no portable spelling of that exists",
            "BOR": "SQL's | is an integer operator; SEL's BOR is a byte-string operator over BIN of equal length, and no portable spelling of that exists",
            "BXOR": "SQL's ^ is an integer operator; SEL's BXOR is a byte-string operator over BIN of equal length, and no portable spelling of that exists",
        },
        "funcs": {
            "LEN": {
                "tpl": "CHAR_LENGTH({0})",
                "ret": "NUM",
            },
            "SUBSTR": {
                "tpl": {
                    "2": "SUBSTRING({0}, {1})",
                    "3": "SUBSTRING({0}, {1}, {2})",
                },
                "ret": "TEXT",
            },
            "UPPER": {
                "tpl": "UPPER({0})",
                "ret": "TEXT",
                "caveat": "unicode-case",
            },
            "LOWER": {
                "tpl": "LOWER({0})",
                "ret": "TEXT",
                "caveat": "unicode-case",
            },
            "TRIM": {
                "tpl": "REGEXP_REPLACE({0}, '^[ \\\\t\\\\r\\\\n]+|[ \\\\t\\\\r\\\\n]+$', '')",
                "ret": "TEXT",
            },
            "LTRIM": {
                "tpl": "REGEXP_REPLACE({0}, '^[ \\\\t\\\\r\\\\n]+', '')",
                "ret": "TEXT",
            },
            "RTRIM": {
                "tpl": "REGEXP_REPLACE({0}, '[ \\\\t\\\\r\\\\n]+$', '')",
                "ret": "TEXT",
            },
            "ABS": {
                "tpl": "ABS({0})",
                "ret": "NUM",
            },
            "CEIL": {
                "tpl": "CEIL({0})",
                "ret": "NUM",
            },
            "FLOOR": {
                "tpl": "FLOOR({0})",
                "ret": "NUM",
            },
            "POWER": {
                "tpl": "POWER({0}, {1})",
                "ret": "NUM",
                "caveat": "power-float",
            },
            "LEFT": {
                "tpl": "LEFT({0}, {1})",
                "ret": "TEXT",
            },
            "RIGHT": {
                "tpl": "RIGHT({0}, {1})",
                "ret": "TEXT",
            },
            "FIND": {
                "tpl": {
                    "2": "INSTR({1}, {0})",
                    "3": "LOCATE({0}, {1}, {2})",
                },
                "ret": "NUM",
            },
            "REPLACE": {
                "tpl": "REPLACE({2}, {0}, {1})",
                "ret": "TEXT",
            },
            "SPLIT": "yields a list, and a SQL expression is a scalar",
            "BACKWARDS": {
                "tpl": "REVERSE({0})",
                "ret": "TEXT",
            },
            "REPEAT": {
                "tpl": "REPEAT({0}, {1})",
                "ret": "TEXT",
            },
            "PADL": {
                "tpl": "IF(CHAR_LENGTH({0}) >= {1}, {0}, LPAD({0}, {1}, {2}))",
                "ret": "TEXT",
            },
            "PADR": {
                "tpl": "IF(CHAR_LENGTH({0}) >= {1}, {0}, RPAD({0}, {1}, {2}))",
                "ret": "TEXT",
            },
            "CHAR": "CHAR(n USING utf8mb4) reads n as a byte sequence in that charset, not as a code point: CHAR(233 USING utf8mb4) is NULL because 0xE9 alone is not valid UTF-8, where SEL says the character is e-acute",
            "CODE": "ORD returns the first character's bytes read as an integer, not its code point; SEL's CODE is a code point",
            "SIGN": {
                "tpl": "SIGN({0})",
                "ret": "NUM",
            },
            "TRUNC": {
                "tpl": "TRUNCATE({0}, 0)",
                "ret": "NUM",
            },
            "ROUND": {
                "tpl": "ROUND({0}, {1})",
                "ret": "NUM",
                "caveat": "rounding-mode",
            },
            "MIN": {
                "tpl": {
                    "1": "{0}",
                    "*": "LEAST({*})",
                },
                "ret": "NUM",
                "caveat": "numeric-scale",
            },
            "MAX": {
                "tpl": {
                    "1": "{0}",
                    "*": "GREATEST({*})",
                },
                "ret": "NUM",
                "caveat": "numeric-scale",
            },
            "ISNUM": {
                "tpl": "({0} REGEXP '\\\\A-?[0-9]+(\\\\.[0-9]+)?\\\\z')",
                "ret": "BOOL",
            },
            "BLEN": {
                "tpl": "LENGTH({binaryCast:0})",
                "ret": "NUM",
            },
            "TO_UTF8": {
                "tpl": "CAST({0} AS BINARY)",
                "ret": "BIN",
            },
            "FROM_UTF8": {
                "tpl": "CONVERT({binaryCast:0} USING utf8mb4)",
                "ret": "TEXT",
            },
            "TO_HEX": {
                "tpl": "LOWER(HEX({binaryCast:0}))",
                "ret": "TEXT",
            },
            "FROM_HEX": {
                "tpl": "UNHEX({0})",
                "ret": "BIN",
            },
            "ENCODE_BASE64": {
                "tpl": "REPLACE(REPLACE(TO_BASE64({binaryCast:0}), CHAR(10), ''), CHAR(13), '')",
                "ret": "TEXT",
            },
            "DECODE_BASE64": {
                "tpl": "FROM_BASE64({0})",
                "ret": "BIN",
                "caveat": "input-laxity",
            },
            "CRC32": {
                "tpl": "LPAD(LOWER(HEX(CRC32({binaryCast:0}))), 8, '0')",
                "ret": "TEXT",
            },
            "BTL": "yields a list, and a SQL expression is a scalar",
            "LTB": "takes a list, and a SQL expression is a scalar",
            "RMATCH": {
                "tpl": "({1}{textCollate} REGEXP {0})",
                "arity": [2, 2],
                "ret": "BOOL",
                "caveat": "regex-engine",
            },
            "RFIND": {
                "tpl": "REGEXP_INSTR({1}{textCollate}, {0})",
                "arity": [2, 2],
                "ret": "NUM",
                "caveat": "regex-engine",
            },
            "RREPLACE": "SEL replacement syntax is $0-$9 and MariaDB's is \\1; rewriting one into the other is only possible when the replacement is a literal, which the map cannot express",
            "RGROUPS": "yields a list, and a SQL expression is a scalar",
        },
        "skel": {
            "case": {
                "tpl": "CASE {branches} ELSE {else} END",
            },
            "caseBranch": {
                "tpl": "WHEN {cond} THEN {then}",
            },
            "all": {
                "tpl": "NOT EXISTS (SELECT 1 FROM {from} WHERE {corr} AND ({body}) IS NOT TRUE)",
            },
            "any": {
                "tpl": "EXISTS (SELECT 1 FROM {from} WHERE {corr} AND ({body}) IS TRUE)",
            },
            "sum": {
                "tpl": "(SELECT COALESCE(SUM({body}), 0) FROM {from} WHERE {corr})",
            },
            "count": {
                "tpl": "(SELECT COUNT(*) FROM {from} WHERE {corr})",
            },
            "inRelation": {
                "tpl": "({needle} IN (SELECT {body} FROM {from} WHERE {corr}))",
            },
            "join": "GROUP_CONCAT does not specify an order without an ORDER BY, and a relation binding has no key to order by; SEL's JOIN concatenates in insertion order",
        },
    },
    "mysql-family": {
        "dialect": "mysql-family",
        "extends": "ansi",
        "version": "0",
        "target": False,
        "lexical": {
            "identQuote": "`",
            "identEscape": "``",
            "textQuote": "'",
            "textEscape": {
                "'": "''",
                "\\": "\\\\",
            },
            "true": "TRUE",
            "false": "FALSE",
            "binaryLiteral": "X'{hex}'",
            "numericLiteral": "{0}",
            "textCollate": " COLLATE utf8mb4_bin",
            "numericCast": "CAST({0} AS DECIMAL(65,10))",
            "binaryCast": "CAST({0} AS BINARY)",
            "isTrue": "({0}) IS TRUE",
            "isNotTrue": "({0}) IS NOT TRUE",
            "placeholder": "?",
            "textCast": "CAST({0} AS CHAR)",
        },
        "ops": {
            "+": {
                "tpl": "({0} + {1})",
                "ret": "NUM",
            },
            "-": {
                "tpl": "({0} - {1})",
                "ret": "NUM",
            },
            "*": {
                "tpl": "({0} * {1})",
                "ret": "NUM",
                "caveat": "scale-limit",
            },
            "/": {
                "tpl": "({0} / {1})",
                "ret": "NUM",
                "caveat": "division-scale",
            },
            "%": {
                "tpl": "MOD({0}, {1})",
                "ret": "NUM",
            },
            "NEG": {
                "tpl": "(-{0})",
                "ret": "NUM",
            },
            "&": {
                "variants": {
                    "text": "CONCAT({0}, {1})",
                    "bin": "CONCAT({0}, {1})",
                },
                "ret": "@concat",
                "caveat": "concat-null",
            },
            "AND": {
                "tpl": "({0} AND {1})",
                "ret": "BOOL",
            },
            "OR": {
                "tpl": "({0} OR {1})",
                "ret": "BOOL",
            },
            "NOT": {
                "tpl": "(NOT {0})",
                "ret": "BOOL",
            },
            "XOR": {
                "tpl": "({0} XOR {1})",
                "ret": "BOOL",
            },
            "==": {
                "variants": {
                    "num": "({0} = {1})",
                    "coerce": "({numericCast:0} = {numericCast:1})",
                },
                "ret": "BOOL",
            },
            "!=": {
                "variants": {
                    "num": "({0} <> {1})",
                    "coerce": "({numericCast:0} <> {numericCast:1})",
                },
                "ret": "BOOL",
            },
            "<": {
                "variants": {
                    "num": "({0} < {1})",
                    "coerce": "({numericCast:0} < {numericCast:1})",
                },
                "ret": "BOOL",
            },
            "<=": {
                "variants": {
                    "num": "({0} <= {1})",
                    "coerce": "({numericCast:0} <= {numericCast:1})",
                },
                "ret": "BOOL",
            },
            ">": {
                "variants": {
                    "num": "({0} > {1})",
                    "coerce": "({numericCast:0} > {numericCast:1})",
                },
                "ret": "BOOL",
            },
            ">=": {
                "variants": {
                    "num": "({0} >= {1})",
                    "coerce": "({numericCast:0} >= {numericCast:1})",
                },
                "ret": "BOOL",
            },
            "$==": {
                "variants": {
                    "text": "({0} = {1})",
                },
                "ret": "BOOL",
            },
            "$!=": {
                "variants": {
                    "text": "({0} <> {1})",
                },
                "ret": "BOOL",
            },
            "$<": {
                "variants": {
                    "text": "({0} < {1})",
                },
                "ret": "BOOL",
            },
            "$<=": {
                "variants": {
                    "text": "({0} <= {1})",
                },
                "ret": "BOOL",
            },
            "$>": {
                "variants": {
                    "text": "({0} > {1})",
                },
                "ret": "BOOL",
            },
            "$>=": {
                "variants": {
                    "text": "({0} >= {1})",
                },
                "ret": "BOOL",
            },
            "EQL": {
                "variants": {
                    "text": "({0} = {1})",
                },
                "ret": "BOOL",
            },
            "IN": {
                "variants": {
                    "scalar": "({0} = {1})",
                },
                "ret": "BOOL",
            },
            "BAND": "SQL's & is an integer operator; SEL's BAND is a byte-string operator over BIN of equal length, and no portable spelling of that exists",
            "BOR": "SQL's | is an integer operator; SEL's BOR is a byte-string operator over BIN of equal length, and no portable spelling of that exists",
            "BXOR": "SQL's ^ is an integer operator; SEL's BXOR is a byte-string operator over BIN of equal length, and no portable spelling of that exists",
        },
        "funcs": {
            "LEN": {
                "tpl": "CHAR_LENGTH({0})",
                "ret": "NUM",
            },
            "SUBSTR": {
                "tpl": {
                    "2": "SUBSTRING({0}, {1})",
                    "3": "SUBSTRING({0}, {1}, {2})",
                },
                "ret": "TEXT",
            },
            "UPPER": {
                "tpl": "UPPER({0})",
                "ret": "TEXT",
                "caveat": "unicode-case",
            },
            "LOWER": {
                "tpl": "LOWER({0})",
                "ret": "TEXT",
                "caveat": "unicode-case",
            },
            "TRIM": {
                "tpl": "REGEXP_REPLACE({0}, '^[ \\\\t\\\\r\\\\n]+|[ \\\\t\\\\r\\\\n]+$', '')",
                "ret": "TEXT",
            },
            "LTRIM": {
                "tpl": "REGEXP_REPLACE({0}, '^[ \\\\t\\\\r\\\\n]+', '')",
                "ret": "TEXT",
            },
            "RTRIM": {
                "tpl": "REGEXP_REPLACE({0}, '[ \\\\t\\\\r\\\\n]+$', '')",
                "ret": "TEXT",
            },
            "ABS": {
                "tpl": "ABS({0})",
                "ret": "NUM",
            },
            "CEIL": {
                "tpl": "CEIL({0})",
                "ret": "NUM",
            },
            "FLOOR": {
                "tpl": "FLOOR({0})",
                "ret": "NUM",
            },
            "POWER": {
                "tpl": "POWER({0}, {1})",
                "ret": "NUM",
                "caveat": "power-float",
            },
            "LEFT": {
                "tpl": "LEFT({0}, {1})",
                "ret": "TEXT",
            },
            "RIGHT": {
                "tpl": "RIGHT({0}, {1})",
                "ret": "TEXT",
            },
            "FIND": {
                "tpl": {
                    "2": "INSTR({1}, {0})",
                    "3": "LOCATE({0}, {1}, {2})",
                },
                "ret": "NUM",
            },
            "REPLACE": {
                "tpl": "REPLACE({2}, {0}, {1})",
                "ret": "TEXT",
            },
            "SPLIT": "yields a list, and a SQL expression is a scalar",
            "BACKWARDS": {
                "tpl": "REVERSE({0})",
                "ret": "TEXT",
            },
            "REPEAT": {
                "tpl": "REPEAT({0}, {1})",
                "ret": "TEXT",
            },
            "PADL": {
                "tpl": "IF(CHAR_LENGTH({0}) >= {1}, {0}, LPAD({0}, {1}, {2}))",
                "ret": "TEXT",
            },
            "PADR": {
                "tpl": "IF(CHAR_LENGTH({0}) >= {1}, {0}, RPAD({0}, {1}, {2}))",
                "ret": "TEXT",
            },
            "CHAR": "CHAR(n USING utf8mb4) reads n as a byte sequence in that charset, not as a code point: CHAR(233 USING utf8mb4) is NULL because 0xE9 alone is not valid UTF-8, where SEL says the character is e-acute",
            "CODE": "ORD returns the first character's bytes read as an integer, not its code point; SEL's CODE is a code point",
            "SIGN": {
                "tpl": "SIGN({0})",
                "ret": "NUM",
            },
            "TRUNC": {
                "tpl": "TRUNCATE({0}, 0)",
                "ret": "NUM",
            },
            "ROUND": {
                "tpl": "ROUND({0}, {1})",
                "ret": "NUM",
                "caveat": "rounding-mode",
            },
            "MIN": {
                "tpl": {
                    "1": "{0}",
                    "*": "LEAST({*})",
                },
                "ret": "NUM",
                "caveat": "numeric-scale",
            },
            "MAX": {
                "tpl": {
                    "1": "{0}",
                    "*": "GREATEST({*})",
                },
                "ret": "NUM",
                "caveat": "numeric-scale",
            },
            "ISNUM": {
                "tpl": "({0} REGEXP '\\\\A-?[0-9]+(\\\\.[0-9]+)?\\\\z')",
                "ret": "BOOL",
            },
            "BLEN": {
                "tpl": "LENGTH({binaryCast:0})",
                "ret": "NUM",
            },
            "TO_UTF8": {
                "tpl": "CAST({0} AS BINARY)",
                "ret": "BIN",
            },
            "FROM_UTF8": {
                "tpl": "CONVERT({binaryCast:0} USING utf8mb4)",
                "ret": "TEXT",
            },
            "TO_HEX": {
                "tpl": "LOWER(HEX({binaryCast:0}))",
                "ret": "TEXT",
            },
            "FROM_HEX": {
                "tpl": "UNHEX({0})",
                "ret": "BIN",
            },
            "ENCODE_BASE64": {
                "tpl": "REPLACE(REPLACE(TO_BASE64({binaryCast:0}), CHAR(10), ''), CHAR(13), '')",
                "ret": "TEXT",
            },
            "DECODE_BASE64": {
                "tpl": "FROM_BASE64({0})",
                "ret": "BIN",
                "caveat": "input-laxity",
            },
            "CRC32": {
                "tpl": "LPAD(LOWER(HEX(CRC32({binaryCast:0}))), 8, '0')",
                "ret": "TEXT",
            },
            "BTL": "yields a list, and a SQL expression is a scalar",
            "LTB": "takes a list, and a SQL expression is a scalar",
            "RMATCH": {
                "tpl": "({1}{textCollate} REGEXP {0})",
                "arity": [2, 2],
                "ret": "BOOL",
                "caveat": "regex-engine",
            },
            "RFIND": {
                "tpl": "REGEXP_INSTR({1}{textCollate}, {0})",
                "arity": [2, 2],
                "ret": "NUM",
                "caveat": "regex-engine",
            },
            "RREPLACE": "SEL replacement syntax is $0-$9 and MariaDB's is \\1; rewriting one into the other is only possible when the replacement is a literal, which the map cannot express",
            "RGROUPS": "yields a list, and a SQL expression is a scalar",
        },
        "skel": {
            "case": {
                "tpl": "CASE {branches} ELSE {else} END",
            },
            "caseBranch": {
                "tpl": "WHEN {cond} THEN {then}",
            },
            "all": {
                "tpl": "NOT EXISTS (SELECT 1 FROM {from} WHERE {corr} AND ({body}) IS NOT TRUE)",
            },
            "any": {
                "tpl": "EXISTS (SELECT 1 FROM {from} WHERE {corr} AND ({body}) IS TRUE)",
            },
            "sum": {
                "tpl": "(SELECT COALESCE(SUM({body}), 0) FROM {from} WHERE {corr})",
            },
            "count": {
                "tpl": "(SELECT COUNT(*) FROM {from} WHERE {corr})",
            },
            "inRelation": {
                "tpl": "({needle} IN (SELECT {body} FROM {from} WHERE {corr}))",
            },
            "join": "GROUP_CONCAT does not specify an order without an ORDER BY, and a relation binding has no key to order by; SEL's JOIN concatenates in insertion order",
        },
    },
    "postgresql": {
        "dialect": "postgresql",
        "extends": "ansi",
        "version": "15",
        "target": True,
        "lexical": {
            "identQuote": "\"",
            "identEscape": "\"\"",
            "textQuote": "'",
            "textEscape": {
                "'": "''",
            },
            "true": "TRUE",
            "false": "FALSE",
            "binaryLiteral": "'\\x{hex}'::bytea",
            "numericLiteral": "{0}",
            "textCollate": " COLLATE \"C\"",
            "numericCast": "CAST({0} AS NUMERIC)",
            "binaryCast": "convert_to(CAST({0} AS TEXT), 'UTF8')",
            "isTrue": "(({0}) IS TRUE)",
            "isNotTrue": "(({0}) IS NOT TRUE)",
            "placeholder": "?",
            "textCast": "CAST({0} AS TEXT)",
        },
        "ops": {
            "+": {
                "tpl": "({numericCast:0} + {numericCast:1})",
                "ret": "NUM",
            },
            "-": {
                "tpl": "({numericCast:0} - {numericCast:1})",
                "ret": "NUM",
            },
            "*": {
                "tpl": "({numericCast:0} * {numericCast:1})",
                "ret": "NUM",
            },
            "/": {
                "tpl": "({numericCast:0} / {numericCast:1})",
                "ret": "NUM",
                "caveat": "division-scale",
            },
            "%": {
                "tpl": "MOD({numericCast:0}, {numericCast:1})",
                "ret": "NUM",
            },
            "NEG": {
                "tpl": "(-{numericCast:0})",
                "ret": "NUM",
            },
            "&": {
                "variants": {
                    "text": "({textCast:0} || {textCast:1})",
                    "bin": "({0} || {1})",
                },
                "ret": "@concat",
                "caveat": "concat-null",
            },
            "AND": {
                "tpl": "({0} AND {1})",
                "ret": "BOOL",
            },
            "OR": {
                "tpl": "({0} OR {1})",
                "ret": "BOOL",
            },
            "NOT": {
                "tpl": "(NOT {0})",
                "ret": "BOOL",
            },
            "XOR": {
                "tpl": "(({0}) <> ({1}))",
                "ret": "BOOL",
            },
            "==": {
                "variants": {
                    "num": "({0} = {1})",
                    "coerce": "({numericCast:0} = {numericCast:1})",
                },
                "ret": "BOOL",
            },
            "!=": {
                "variants": {
                    "num": "({0} <> {1})",
                    "coerce": "({numericCast:0} <> {numericCast:1})",
                },
                "ret": "BOOL",
            },
            "<": {
                "variants": {
                    "num": "({0} < {1})",
                    "coerce": "({numericCast:0} < {numericCast:1})",
                },
                "ret": "BOOL",
            },
            "<=": {
                "variants": {
                    "num": "({0} <= {1})",
                    "coerce": "({numericCast:0} <= {numericCast:1})",
                },
                "ret": "BOOL",
            },
            ">": {
                "variants": {
                    "num": "({0} > {1})",
                    "coerce": "({numericCast:0} > {numericCast:1})",
                },
                "ret": "BOOL",
            },
            ">=": {
                "variants": {
                    "num": "({0} >= {1})",
                    "coerce": "({numericCast:0} >= {numericCast:1})",
                },
                "ret": "BOOL",
            },
            "$==": {
                "variants": {
                    "text": "({0} = {1})",
                },
                "ret": "BOOL",
            },
            "$!=": {
                "variants": {
                    "text": "({0} <> {1})",
                },
                "ret": "BOOL",
            },
            "$<": {
                "variants": {
                    "text": "({0} < {1})",
                },
                "ret": "BOOL",
            },
            "$<=": {
                "variants": {
                    "text": "({0} <= {1})",
                },
                "ret": "BOOL",
            },
            "$>": {
                "variants": {
                    "text": "({0} > {1})",
                },
                "ret": "BOOL",
            },
            "$>=": {
                "variants": {
                    "text": "({0} >= {1})",
                },
                "ret": "BOOL",
            },
            "EQL": {
                "variants": {
                    "text": "({0} = {1})",
                },
                "ret": "BOOL",
            },
            "IN": {
                "variants": {
                    "scalar": "({0} = {1})",
                },
                "ret": "BOOL",
            },
            "BAND": "SQL's & is an integer operator; SEL's BAND is a byte-string operator over BIN of equal length, and no portable spelling of that exists",
            "BOR": "SQL's | is an integer operator; SEL's BOR is a byte-string operator over BIN of equal length, and no portable spelling of that exists",
            "BXOR": "SQL's ^ is an integer operator; SEL's BXOR is a byte-string operator over BIN of equal length, and no portable spelling of that exists",
        },
        "funcs": {
            "LEN": {
                "tpl": "length({textCast:0})",
                "ret": "NUM",
            },
            "SUBSTR": {
                "tpl": {
                    "2": "SUBSTRING({textCast:0} FROM CAST({1} AS INTEGER))",
                    "3": "SUBSTRING({textCast:0} FROM CAST({1} AS INTEGER) FOR CAST({2} AS INTEGER))",
                },
                "ret": "TEXT",
            },
            "UPPER": {
                "tpl": "upper({textCast:0})",
                "ret": "TEXT",
                "caveat": "unicode-case",
            },
            "LOWER": {
                "tpl": "lower({textCast:0})",
                "ret": "TEXT",
                "caveat": "unicode-case",
            },
            "TRIM": {
                "tpl": "btrim({textCast:0}, E' \\t\\r\\n')",
                "ret": "TEXT",
            },
            "LTRIM": {
                "tpl": "ltrim({textCast:0}, E' \\t\\r\\n')",
                "ret": "TEXT",
            },
            "RTRIM": {
                "tpl": "rtrim({textCast:0}, E' \\t\\r\\n')",
                "ret": "TEXT",
            },
            "ABS": {
                "tpl": "abs({numericCast:0})",
                "ret": "NUM",
            },
            "CEIL": {
                "tpl": "ceil({numericCast:0})",
                "ret": "NUM",
            },
            "FLOOR": {
                "tpl": "floor({numericCast:0})",
                "ret": "NUM",
            },
            "POWER": {
                "tpl": "power({numericCast:0}, {numericCast:1})",
                "ret": "NUM",
                "caveat": "numeric-scale",
            },
            "LEFT": {
                "tpl": "left({textCast:0}, CAST({1} AS INTEGER))",
                "ret": "TEXT",
            },
            "RIGHT": {
                "tpl": "right({textCast:0}, CAST({1} AS INTEGER))",
                "ret": "TEXT",
            },
            "FIND": {
                "tpl": "strpos({textCast:1}, {textCast:0})",
                "ret": "NUM",
                "arity": [2, 2],
            },
            "REPLACE": {
                "tpl": "replace({textCast:2}, {textCast:0}, {textCast:1})",
                "ret": "TEXT",
            },
            "SPLIT": "yields a list, and a SQL expression is a scalar",
            "BACKWARDS": {
                "tpl": "reverse({textCast:0})",
                "ret": "TEXT",
            },
            "REPEAT": {
                "tpl": "repeat({textCast:0}, CAST({1} AS INTEGER))",
                "ret": "TEXT",
            },
            "PADL": {
                "tpl": "CASE WHEN length({textCast:0}) >= {1} THEN {textCast:0} ELSE lpad({textCast:0}, CAST({1} AS INTEGER), {textCast:2}) END",
                "ret": "TEXT",
            },
            "PADR": {
                "tpl": "CASE WHEN length({textCast:0}) >= {1} THEN {textCast:0} ELSE rpad({textCast:0}, CAST({1} AS INTEGER), {textCast:2}) END",
                "ret": "TEXT",
            },
            "CHAR": {
                "tpl": "chr(CAST({0} AS INTEGER))",
                "ret": "TEXT",
            },
            "CODE": {
                "tpl": "ascii({textCast:0})",
                "ret": "NUM",
            },
            "SIGN": {
                "tpl": "sign({numericCast:0})",
                "ret": "NUM",
            },
            "TRUNC": {
                "tpl": "trunc({numericCast:0})",
                "ret": "NUM",
            },
            "ROUND": {
                "tpl": "round({numericCast:0}, CAST({1} AS INTEGER))",
                "ret": "NUM",
            },
            "MIN": {
                "tpl": "least({*})",
                "ret": "NUM",
            },
            "MAX": {
                "tpl": "greatest({*})",
                "ret": "NUM",
            },
            "ISNUM": {
                "tpl": "({textCast:0} ~ '^-?[0-9]+(\\.[0-9]+)?$')",
                "ret": "BOOL",
            },
            "BLEN": {
                "tpl": "octet_length({binaryCast:0})",
                "ret": "NUM",
            },
            "TO_UTF8": {
                "tpl": "{binaryCast:0}",
                "ret": "BIN",
            },
            "FROM_UTF8": {
                "tpl": "convert_from({binaryCast:0}, 'UTF8')",
                "ret": "TEXT",
            },
            "TO_HEX": {
                "tpl": "encode({binaryCast:0}, 'hex')",
                "ret": "TEXT",
            },
            "FROM_HEX": {
                "tpl": "decode({0}, 'hex')",
                "ret": "BIN",
            },
            "ENCODE_BASE64": {
                "tpl": "replace(replace(encode({binaryCast:0}, 'base64'), chr(10), ''), chr(13), '')",
                "ret": "TEXT",
            },
            "DECODE_BASE64": {
                "tpl": "decode({0}, 'base64')",
                "ret": "BIN",
                "caveat": "input-laxity",
            },
            "CRC32": "PostgreSQL has no CRC32 in core; pgcrypto supplies digests but not CRC32",
            "BTL": "yields a list, and a SQL expression is a scalar",
            "LTB": "takes a list, and a SQL expression is a scalar",
            "RMATCH": {
                "tpl": "({textCast:1}{textCollate} ~ {0})",
                "arity": [2, 2],
                "ret": "BOOL",
                "caveat": "regex-engine",
            },
            "RFIND": {
                "tpl": "regexp_instr({textCast:1}{textCollate}, {0})",
                "arity": [2, 2],
                "ret": "NUM",
                "caveat": "regex-engine",
            },
            "RREPLACE": "regular expressions are not ANSI; set per dialect",
            "RGROUPS": "yields a list, and a SQL expression is a scalar",
        },
        "skel": {
            "case": {
                "tpl": "CASE {branches} ELSE {else} END",
            },
            "caseBranch": {
                "tpl": "WHEN {cond} THEN {then}",
            },
            "all": {
                "tpl": "NOT EXISTS (SELECT 1 FROM {from} WHERE {corr} AND ({body}) IS NOT TRUE)",
            },
            "any": {
                "tpl": "EXISTS (SELECT 1 FROM {from} WHERE {corr} AND ({body}) IS TRUE)",
            },
            "sum": {
                "tpl": "(SELECT COALESCE(SUM({body}), 0) FROM {from} WHERE {corr})",
            },
            "count": {
                "tpl": "(SELECT COUNT(*) FROM {from} WHERE {corr})",
            },
            "inRelation": {
                "tpl": "({needle} IN (SELECT {body} FROM {from} WHERE {corr}))",
            },
            "join": "LISTAGG is SQL:2016 and is spelled differently by every server that has it",
        },
    },
    "sqlite": {
        "dialect": "sqlite",
        "extends": "ansi",
        "version": "3.35",
        "target": True,
        "lexical": {
            "identQuote": "\"",
            "identEscape": "\"\"",
            "textQuote": "'",
            "textEscape": {
                "'": "''",
            },
            "true": "1",
            "false": "0",
            "binaryLiteral": "x'{hex}'",
            "numericLiteral": "'{0}'",
            "textCollate": "",
            "numericCast": "CAST({0} AS NUMERIC)",
            "binaryCast": "CAST({0} AS BLOB)",
            "isTrue": "(({0}) IS TRUE)",
            "isNotTrue": "(({0}) IS NOT TRUE)",
            "placeholder": "?",
            "textCast": "CAST({0} AS TEXT)",
        },
        "ops": {
            "+": {
                "tpl": "({0} + {1})",
                "ret": "NUM",
                "caveat": "decimal-float",
            },
            "-": {
                "tpl": "({0} - {1})",
                "ret": "NUM",
                "caveat": "decimal-float",
            },
            "*": {
                "tpl": "({0} * {1})",
                "ret": "NUM",
                "caveat": "decimal-float",
            },
            "/": {
                "tpl": "({0} * 1.0 / {1})",
                "ret": "NUM",
                "caveat": "decimal-float",
            },
            "%": {
                "tpl": "({0} % {1})",
                "ret": "NUM",
                "caveat": "modulo-integer",
            },
            "NEG": {
                "tpl": "(-{0})",
                "ret": "NUM",
                "caveat": "decimal-float",
            },
            "&": {
                "variants": {
                    "text": "({0} || {1})",
                    "bin": "({0} || {1})",
                },
                "ret": "@concat",
            },
            "AND": {
                "tpl": "({0} AND {1})",
                "ret": "BOOL",
            },
            "OR": {
                "tpl": "({0} OR {1})",
                "ret": "BOOL",
            },
            "NOT": {
                "tpl": "(NOT {0})",
                "ret": "BOOL",
            },
            "XOR": {
                "tpl": "(({0}) <> ({1}))",
                "ret": "BOOL",
            },
            "==": {
                "variants": {
                    "num": "({numericCast:0} = {numericCast:1})",
                    "coerce": "({numericCast:0} = {numericCast:1})",
                },
                "ret": "BOOL",
                "caveat": "decimal-float",
            },
            "!=": {
                "variants": {
                    "num": "({numericCast:0} <> {numericCast:1})",
                    "coerce": "({numericCast:0} <> {numericCast:1})",
                },
                "ret": "BOOL",
                "caveat": "decimal-float",
            },
            "<": {
                "variants": {
                    "num": "({numericCast:0} < {numericCast:1})",
                    "coerce": "({numericCast:0} < {numericCast:1})",
                },
                "ret": "BOOL",
                "caveat": "decimal-float",
            },
            "<=": {
                "variants": {
                    "num": "({numericCast:0} <= {numericCast:1})",
                    "coerce": "({numericCast:0} <= {numericCast:1})",
                },
                "ret": "BOOL",
                "caveat": "decimal-float",
            },
            ">": {
                "variants": {
                    "num": "({numericCast:0} > {numericCast:1})",
                    "coerce": "({numericCast:0} > {numericCast:1})",
                },
                "ret": "BOOL",
                "caveat": "decimal-float",
            },
            ">=": {
                "variants": {
                    "num": "({numericCast:0} >= {numericCast:1})",
                    "coerce": "({numericCast:0} >= {numericCast:1})",
                },
                "ret": "BOOL",
                "caveat": "decimal-float",
            },
            "$==": {
                "variants": {
                    "text": "({0} = {1})",
                },
                "ret": "BOOL",
            },
            "$!=": {
                "variants": {
                    "text": "({0} <> {1})",
                },
                "ret": "BOOL",
            },
            "$<": {
                "variants": {
                    "text": "({0} < {1})",
                },
                "ret": "BOOL",
            },
            "$<=": {
                "variants": {
                    "text": "({0} <= {1})",
                },
                "ret": "BOOL",
            },
            "$>": {
                "variants": {
                    "text": "({0} > {1})",
                },
                "ret": "BOOL",
            },
            "$>=": {
                "variants": {
                    "text": "({0} >= {1})",
                },
                "ret": "BOOL",
            },
            "EQL": {
                "variants": {
                    "text": "({0} = {1})",
                },
                "ret": "BOOL",
            },
            "IN": {
                "variants": {
                    "scalar": "({0} = {1})",
                },
                "ret": "BOOL",
            },
            "BAND": "SQLite's & is integer-only and has no meaning over blobs",
            "BOR": "SQLite's | is integer-only and has no meaning over blobs",
            "BXOR": "SQLite has no XOR operator at all, over integers or blobs",
        },
        "funcs": {
            "LEN": {
                "tpl": "length({0})",
                "ret": "NUM",
            },
            "SUBSTR": {
                "tpl": {
                    "2": "substr({0}, {1})",
                    "3": "substr({0}, {1}, {2})",
                },
                "ret": "TEXT",
            },
            "UPPER": {
                "tpl": "upper({0})",
                "ret": "TEXT",
            },
            "LOWER": {
                "tpl": "lower({0})",
                "ret": "TEXT",
            },
            "TRIM": {
                "tpl": "trim({0}, ' \t\r\n')",
                "ret": "TEXT",
            },
            "LTRIM": {
                "tpl": "ltrim({0}, ' \t\r\n')",
                "ret": "TEXT",
            },
            "RTRIM": {
                "tpl": "rtrim({0}, ' \t\r\n')",
                "ret": "TEXT",
            },
            "ABS": {
                "tpl": "abs({0})",
                "ret": "NUM",
                "caveat": "decimal-float",
            },
            "CEIL": {
                "tpl": "ceil({0})",
                "ret": "NUM",
                "caveat": "decimal-float",
            },
            "FLOOR": {
                "tpl": "floor({0})",
                "ret": "NUM",
                "caveat": "decimal-float",
            },
            "POWER": {
                "tpl": "pow({0}, {1})",
                "ret": "NUM",
                "caveat": "power-float",
            },
            "LEFT": {
                "tpl": "substr({0}, 1, {1})",
                "ret": "TEXT",
            },
            "RIGHT": {
                "tpl": "substr({0}, -{1}, {1})",
                "ret": "TEXT",
            },
            "FIND": {
                "tpl": "instr({1}, {0})",
                "ret": "NUM",
                "arity": [2, 2],
            },
            "REPLACE": {
                "tpl": "replace({2}, {0}, {1})",
                "ret": "TEXT",
            },
            "SPLIT": "yields a list, and a SQL expression is a scalar",
            "BACKWARDS": "SQLite has no reverse(); reversing text needs a recursive CTE, which is a statement rather than an expression",
            "REPEAT": "SQLite has no repeat(); printf can pad with one character but cannot repeat a string",
            "PADL": "SQLite has no LPAD; printf('%*s') pads with spaces only and cannot take SEL's fill string",
            "PADR": "SQLite has no RPAD; printf('%-*s') pads with spaces only and cannot take SEL's fill string",
            "CHAR": {
                "tpl": "char({0})",
                "ret": "TEXT",
            },
            "CODE": {
                "tpl": "unicode({0})",
                "ret": "NUM",
            },
            "SIGN": {
                "tpl": "sign({0})",
                "ret": "NUM",
            },
            "TRUNC": {
                "tpl": "trunc({0})",
                "ret": "NUM",
                "caveat": "decimal-float",
            },
            "ROUND": {
                "tpl": "round({0}, {1})",
                "ret": "NUM",
                "caveat": "decimal-float",
            },
            "MIN": {
                "tpl": "min({*})",
                "ret": "NUM",
                "caveat": "decimal-float",
            },
            "MAX": {
                "tpl": "max({*})",
                "ret": "NUM",
                "caveat": "decimal-float",
            },
            "ISNUM": "SQLite has no REGEXP, and CAST answers 0 for 'abc' rather than saying it is not a number, so there is no expression that asks SEL's question",
            "BLEN": {
                "tpl": "length({binaryCast:0})",
                "ret": "NUM",
            },
            "TO_UTF8": {
                "tpl": "CAST({0} AS BLOB)",
                "ret": "BIN",
            },
            "FROM_UTF8": {
                "tpl": "CAST({binaryCast:0} AS TEXT)",
                "ret": "TEXT",
            },
            "TO_HEX": {
                "tpl": "lower(hex({binaryCast:0}))",
                "ret": "TEXT",
            },
            "FROM_HEX": "unhex() arrived in SQLite 3.41 and this document targets 3.35; there is no portable expression that builds a blob from hex text",
            "ENCODE_BASE64": "SQLite has no base64 function in a default build",
            "DECODE_BASE64": "SQLite has no base64 function in a default build",
            "CRC32": "SQLite has no CRC32 function in a default build",
            "BTL": "yields a list, and a SQL expression is a scalar",
            "LTB": "takes a list, and a SQL expression is a scalar",
            "RMATCH": "SQLite has no REGEXP function unless the application registers one; a default build raises \"no such function: REGEXP\"",
            "RFIND": "SQLite has no REGEXP function unless the application registers one; a default build raises \"no such function: REGEXP\"",
            "RREPLACE": "regular expressions are not ANSI; set per dialect",
            "RGROUPS": "yields a list, and a SQL expression is a scalar",
        },
        "skel": {
            "case": {
                "tpl": "CASE {branches} ELSE {else} END",
            },
            "caseBranch": {
                "tpl": "WHEN {cond} THEN {then}",
            },
            "all": {
                "tpl": "NOT EXISTS (SELECT 1 FROM {from} WHERE {corr} AND ({body}) IS NOT TRUE)",
            },
            "any": {
                "tpl": "EXISTS (SELECT 1 FROM {from} WHERE {corr} AND ({body}) IS TRUE)",
            },
            "sum": {
                "tpl": "(SELECT COALESCE(SUM({body}), 0) FROM {from} WHERE {corr})",
            },
            "count": {
                "tpl": "(SELECT COUNT(*) FROM {from} WHERE {corr})",
            },
            "inRelation": {
                "tpl": "({needle} IN (SELECT {body} FROM {from} WHERE {corr}))",
            },
            "join": "LISTAGG is SQL:2016 and is spelled differently by every server that has it",
        },
    },
}
