;;;; Retained heap for 5,000 live programs, before and after first execution.
(require :asdf)
(load (merge-pathnames "quicklisp/setup.lisp" (user-homedir-pathname)))
(let ((*standard-output* (make-broadcast-stream))
      (root (uiop:ensure-directory-pathname (or (uiop:getenv "SEL_LISP_RUNTIME_ROOT") "./"))))
  (asdf:load-asd (truename (merge-pathnames "lisp/sel-lang.asd" root)))
  (funcall (find-symbol "QUICKLOAD" "QL") '(:sel-lang :yason)))
(defun retained () (sb-ext:gc :full t) (sb-kernel:dynamic-usage))
(let* ((source "COALESCE(A, B, C, D, E, F, G, H, I, J)")
       (ctx (sel:make-none))
       (report (make-hash-table :test 'equal)))
  (dolist (name '("A" "B" "C" "D" "E" "F" "G" "H" "I" "J"))
    (sel:value-set ctx name (sel:make-none)))
  (dotimes (i 100) (sel:run (sel:compile-source source) ctx))
  (let* ((start (retained))
         (programs (make-array 5000)))
    (dotimes (i (length programs))
      (setf (aref programs i) (sel:compile-source source)))
    (setf (gethash "compiled_bytes" report) (- (retained) start))
    (dotimes (i (length programs)) (sel:run (aref programs i) ctx))
    (setf (gethash "executed_bytes" report) (- (retained) start)
          (gethash "programs" report) (length programs)
          ;; Keep the whole program graph live through the heap measurement.
          (gethash "source_characters" report)
          (loop for program across programs sum (length (sel::program-source program))))
    (yason:encode report *standard-output*)
    (terpri)))
