<?php
// GENERATED by tools/gen-lexicon.mjs from spec/lexicon.json — do not edit; edit the lexicon and regenerate.
//
// RESERVED: the reserved words. SYMBOLS: every symbol token, longest first.
// BP: each precedence level's binding power (higher binds tighter). OPS: one
// row per operator, tightest level first; see spec/lexicon.md for the fields.
// relation indexes RELATIONS (-1 when none); assoc is 'L', 'R', 'N' or null.

declare(strict_types=1);

namespace Sel;

final class Lexicon
{
    /** @var list<string> */
    public const RESERVED = ['TRUE', 'FALSE', 'NULL', 'AND', 'OR', 'NOT', 'XOR', 'EQL', 'IN', 'BAND', 'BOR', 'BXOR'];

    /** @var list<string> */
    public const SYMBOLS = ['???', '$==', '$!=', '$<=', '$>=', '.>', '??', '==', '!=', '<=', '>=', '$<', '$>', '+=', '-=', '*=', '/=', '%=', '&=', '[', '-', '*', '/', '%', '+', '&', '<', '>', '=', ',', ';', '(', ')', ']'];

    /** @var list<string> */
    public const RELATIONS = ['eq', 'ne', 'lt', 'le', 'gt', 'ge'];

    /** @var array<string,int> */
    public const BP = [
        'POSTFIX' => 17,
        'NEG' => 16,
        'MUL' => 15,
        'ADD' => 14,
        'CONCAT' => 13,
        'BAND' => 12,
        'BXOR' => 11,
        'BOR' => 10,
        'COALESCE' => 9,
        'COMPARE' => 8,
        'NOT' => 7,
        'AND' => 6,
        'XOR' => 5,
        'OR' => 4,
        'ASSIGN' => 3,
        'LIST' => 2,
        'SEQ' => 1,
    ];

    /** @var list<array{token:string,word:bool,fixity:string,level:string,bp:int,assoc:?string,family:string,node:string,name:?string,relation:int,compound:?string,shortCircuit:bool}> */
    public const OPS = [
        ['token' => '[', 'word' => false, 'fixity' => 'postfix', 'level' => 'POSTFIX', 'bp' => 17, 'assoc' => null, 'family' => 'postfix', 'node' => 'index', 'name' => null, 'relation' => -1, 'compound' => null, 'shortCircuit' => false],
        ['token' => '.>', 'word' => false, 'fixity' => 'postfix', 'level' => 'POSTFIX', 'bp' => 17, 'assoc' => null, 'family' => 'postfix', 'node' => 'pipe', 'name' => null, 'relation' => -1, 'compound' => null, 'shortCircuit' => false],
        ['token' => '-', 'word' => false, 'fixity' => 'prefix', 'level' => 'NEG', 'bp' => 16, 'assoc' => null, 'family' => 'arith', 'node' => 'un', 'name' => 'NEG', 'relation' => -1, 'compound' => null, 'shortCircuit' => false],
        ['token' => '*', 'word' => false, 'fixity' => 'infix', 'level' => 'MUL', 'bp' => 15, 'assoc' => 'L', 'family' => 'arith', 'node' => 'bin', 'name' => null, 'relation' => -1, 'compound' => null, 'shortCircuit' => false],
        ['token' => '/', 'word' => false, 'fixity' => 'infix', 'level' => 'MUL', 'bp' => 15, 'assoc' => 'L', 'family' => 'arith', 'node' => 'bin', 'name' => null, 'relation' => -1, 'compound' => null, 'shortCircuit' => false],
        ['token' => '%', 'word' => false, 'fixity' => 'infix', 'level' => 'MUL', 'bp' => 15, 'assoc' => 'L', 'family' => 'arith', 'node' => 'bin', 'name' => null, 'relation' => -1, 'compound' => null, 'shortCircuit' => false],
        ['token' => '+', 'word' => false, 'fixity' => 'infix', 'level' => 'ADD', 'bp' => 14, 'assoc' => 'L', 'family' => 'arith', 'node' => 'bin', 'name' => null, 'relation' => -1, 'compound' => null, 'shortCircuit' => false],
        ['token' => '-', 'word' => false, 'fixity' => 'infix', 'level' => 'ADD', 'bp' => 14, 'assoc' => 'L', 'family' => 'arith', 'node' => 'bin', 'name' => null, 'relation' => -1, 'compound' => null, 'shortCircuit' => false],
        ['token' => '&', 'word' => false, 'fixity' => 'infix', 'level' => 'CONCAT', 'bp' => 13, 'assoc' => 'L', 'family' => 'concat', 'node' => 'bin', 'name' => null, 'relation' => -1, 'compound' => null, 'shortCircuit' => false],
        ['token' => 'BAND', 'word' => true, 'fixity' => 'infix', 'level' => 'BAND', 'bp' => 12, 'assoc' => 'L', 'family' => 'bitwise', 'node' => 'bin', 'name' => null, 'relation' => -1, 'compound' => null, 'shortCircuit' => false],
        ['token' => 'BXOR', 'word' => true, 'fixity' => 'infix', 'level' => 'BXOR', 'bp' => 11, 'assoc' => 'L', 'family' => 'bitwise', 'node' => 'bin', 'name' => null, 'relation' => -1, 'compound' => null, 'shortCircuit' => false],
        ['token' => 'BOR', 'word' => true, 'fixity' => 'infix', 'level' => 'BOR', 'bp' => 10, 'assoc' => 'L', 'family' => 'bitwise', 'node' => 'bin', 'name' => null, 'relation' => -1, 'compound' => null, 'shortCircuit' => false],
        ['token' => '??', 'word' => false, 'fixity' => 'infix', 'level' => 'COALESCE', 'bp' => 9, 'assoc' => 'R', 'family' => 'coalesce', 'node' => 'bin', 'name' => null, 'relation' => -1, 'compound' => null, 'shortCircuit' => true],
        ['token' => '???', 'word' => false, 'fixity' => 'infix', 'level' => 'COALESCE', 'bp' => 9, 'assoc' => 'R', 'family' => 'coalesce', 'node' => 'bin', 'name' => null, 'relation' => -1, 'compound' => null, 'shortCircuit' => true],
        ['token' => '==', 'word' => false, 'fixity' => 'infix', 'level' => 'COMPARE', 'bp' => 8, 'assoc' => 'N', 'family' => 'compare', 'node' => 'bin', 'name' => null, 'relation' => 0, 'compound' => null, 'shortCircuit' => false],
        ['token' => '!=', 'word' => false, 'fixity' => 'infix', 'level' => 'COMPARE', 'bp' => 8, 'assoc' => 'N', 'family' => 'compare', 'node' => 'bin', 'name' => null, 'relation' => 1, 'compound' => null, 'shortCircuit' => false],
        ['token' => '<', 'word' => false, 'fixity' => 'infix', 'level' => 'COMPARE', 'bp' => 8, 'assoc' => 'N', 'family' => 'compare', 'node' => 'bin', 'name' => null, 'relation' => 2, 'compound' => null, 'shortCircuit' => false],
        ['token' => '<=', 'word' => false, 'fixity' => 'infix', 'level' => 'COMPARE', 'bp' => 8, 'assoc' => 'N', 'family' => 'compare', 'node' => 'bin', 'name' => null, 'relation' => 3, 'compound' => null, 'shortCircuit' => false],
        ['token' => '>', 'word' => false, 'fixity' => 'infix', 'level' => 'COMPARE', 'bp' => 8, 'assoc' => 'N', 'family' => 'compare', 'node' => 'bin', 'name' => null, 'relation' => 4, 'compound' => null, 'shortCircuit' => false],
        ['token' => '>=', 'word' => false, 'fixity' => 'infix', 'level' => 'COMPARE', 'bp' => 8, 'assoc' => 'N', 'family' => 'compare', 'node' => 'bin', 'name' => null, 'relation' => 5, 'compound' => null, 'shortCircuit' => false],
        ['token' => '$==', 'word' => false, 'fixity' => 'infix', 'level' => 'COMPARE', 'bp' => 8, 'assoc' => 'N', 'family' => 'text-compare', 'node' => 'bin', 'name' => null, 'relation' => 0, 'compound' => null, 'shortCircuit' => false],
        ['token' => '$!=', 'word' => false, 'fixity' => 'infix', 'level' => 'COMPARE', 'bp' => 8, 'assoc' => 'N', 'family' => 'text-compare', 'node' => 'bin', 'name' => null, 'relation' => 1, 'compound' => null, 'shortCircuit' => false],
        ['token' => '$<', 'word' => false, 'fixity' => 'infix', 'level' => 'COMPARE', 'bp' => 8, 'assoc' => 'N', 'family' => 'text-compare', 'node' => 'bin', 'name' => null, 'relation' => 2, 'compound' => null, 'shortCircuit' => false],
        ['token' => '$<=', 'word' => false, 'fixity' => 'infix', 'level' => 'COMPARE', 'bp' => 8, 'assoc' => 'N', 'family' => 'text-compare', 'node' => 'bin', 'name' => null, 'relation' => 3, 'compound' => null, 'shortCircuit' => false],
        ['token' => '$>', 'word' => false, 'fixity' => 'infix', 'level' => 'COMPARE', 'bp' => 8, 'assoc' => 'N', 'family' => 'text-compare', 'node' => 'bin', 'name' => null, 'relation' => 4, 'compound' => null, 'shortCircuit' => false],
        ['token' => '$>=', 'word' => false, 'fixity' => 'infix', 'level' => 'COMPARE', 'bp' => 8, 'assoc' => 'N', 'family' => 'text-compare', 'node' => 'bin', 'name' => null, 'relation' => 5, 'compound' => null, 'shortCircuit' => false],
        ['token' => 'EQL', 'word' => true, 'fixity' => 'infix', 'level' => 'COMPARE', 'bp' => 8, 'assoc' => 'N', 'family' => 'deep-compare', 'node' => 'bin', 'name' => null, 'relation' => -1, 'compound' => null, 'shortCircuit' => false],
        ['token' => 'IN', 'word' => true, 'fixity' => 'infix', 'level' => 'COMPARE', 'bp' => 8, 'assoc' => 'N', 'family' => 'deep-compare', 'node' => 'bin', 'name' => null, 'relation' => -1, 'compound' => null, 'shortCircuit' => false],
        ['token' => 'NOT', 'word' => true, 'fixity' => 'prefix', 'level' => 'NOT', 'bp' => 7, 'assoc' => null, 'family' => 'logic', 'node' => 'un', 'name' => 'NOT', 'relation' => -1, 'compound' => null, 'shortCircuit' => false],
        ['token' => 'AND', 'word' => true, 'fixity' => 'infix', 'level' => 'AND', 'bp' => 6, 'assoc' => 'L', 'family' => 'logic', 'node' => 'bin', 'name' => null, 'relation' => -1, 'compound' => null, 'shortCircuit' => true],
        ['token' => 'XOR', 'word' => true, 'fixity' => 'infix', 'level' => 'XOR', 'bp' => 5, 'assoc' => 'L', 'family' => 'logic', 'node' => 'bin', 'name' => null, 'relation' => -1, 'compound' => null, 'shortCircuit' => false],
        ['token' => 'OR', 'word' => true, 'fixity' => 'infix', 'level' => 'OR', 'bp' => 4, 'assoc' => 'L', 'family' => 'logic', 'node' => 'bin', 'name' => null, 'relation' => -1, 'compound' => null, 'shortCircuit' => true],
        ['token' => '=', 'word' => false, 'fixity' => 'infix', 'level' => 'ASSIGN', 'bp' => 3, 'assoc' => 'R', 'family' => 'assign', 'node' => 'assign', 'name' => null, 'relation' => -1, 'compound' => null, 'shortCircuit' => false],
        ['token' => '+=', 'word' => false, 'fixity' => 'infix', 'level' => 'ASSIGN', 'bp' => 3, 'assoc' => 'R', 'family' => 'assign', 'node' => 'assign', 'name' => null, 'relation' => -1, 'compound' => '+', 'shortCircuit' => false],
        ['token' => '-=', 'word' => false, 'fixity' => 'infix', 'level' => 'ASSIGN', 'bp' => 3, 'assoc' => 'R', 'family' => 'assign', 'node' => 'assign', 'name' => null, 'relation' => -1, 'compound' => '-', 'shortCircuit' => false],
        ['token' => '*=', 'word' => false, 'fixity' => 'infix', 'level' => 'ASSIGN', 'bp' => 3, 'assoc' => 'R', 'family' => 'assign', 'node' => 'assign', 'name' => null, 'relation' => -1, 'compound' => '*', 'shortCircuit' => false],
        ['token' => '/=', 'word' => false, 'fixity' => 'infix', 'level' => 'ASSIGN', 'bp' => 3, 'assoc' => 'R', 'family' => 'assign', 'node' => 'assign', 'name' => null, 'relation' => -1, 'compound' => '/', 'shortCircuit' => false],
        ['token' => '%=', 'word' => false, 'fixity' => 'infix', 'level' => 'ASSIGN', 'bp' => 3, 'assoc' => 'R', 'family' => 'assign', 'node' => 'assign', 'name' => null, 'relation' => -1, 'compound' => '%', 'shortCircuit' => false],
        ['token' => '&=', 'word' => false, 'fixity' => 'infix', 'level' => 'ASSIGN', 'bp' => 3, 'assoc' => 'R', 'family' => 'assign', 'node' => 'assign', 'name' => null, 'relation' => -1, 'compound' => '&', 'shortCircuit' => false],
        ['token' => ',', 'word' => false, 'fixity' => 'infix', 'level' => 'LIST', 'bp' => 2, 'assoc' => 'L', 'family' => 'list', 'node' => 'list', 'name' => null, 'relation' => -1, 'compound' => null, 'shortCircuit' => false],
        ['token' => ';', 'word' => false, 'fixity' => 'infix', 'level' => 'SEQ', 'bp' => 1, 'assoc' => 'L', 'family' => 'sequence', 'node' => 'seq', 'name' => null, 'relation' => -1, 'compound' => null, 'shortCircuit' => false],
    ];
}
