<?php
// GENERATED by tools/gen-limits.mjs from spec/limits.json — do not edit; edit the manifest and regenerate.

declare(strict_types=1);

namespace Sel;

final class Limits
{
    /** §6.4: parser nesting and evaluation nesting, each; exceeding either is E_DEPTH */
    public const MAX_DEPTH = 200;
    /** §6.4: integer digits of a number; beyond it E_RANGE */
    public const MAX_INT_DIGITS = 1000000;
    /** §6.4: fractional digits of a number; beyond it E_RANGE */
    public const MAX_FRAC_DIGITS = 1000000;
    /** §5.3: fractional digits long division runs to before rounding half away from zero */
    public const DIV_SCALE = 10;

    /** The language's error codes and the phase that raises each: 'compile', 'run' or 'both'. @var array<string,string> */
    public const ERROR_CODES = [
        'E_SYNTAX' => 'compile',
        'E_UNTERMINATED' => 'compile',
        'E_ESCAPE' => 'compile',
        'E_RESERVED' => 'compile',
        'E_BAD_ASSIGN' => 'compile',
        'E_UNKNOWN_FUNC' => 'compile',
        'E_ARITY' => 'compile',
        'E_DEPTH' => 'both',
        'E_REGEX_SYNTAX' => 'compile',
        'E_UNDEF_VAR' => 'run',
        'E_NO_KEY' => 'run',
        'E_NO_SCALAR' => 'run',
        'E_NOT_NUM' => 'run',
        'E_NOT_TEXT' => 'run',
        'E_NOT_BIN' => 'run',
        'E_NOT_BOOL' => 'run',
        'E_NOT_INT' => 'run',
        'E_NULL' => 'run',
        'E_EXPECT_SYMBOL' => 'run',
        'E_DIV_ZERO' => 'run',
        'E_UTF8' => 'run',
        'E_RANGE' => 'run',
        'E_BAD_ARG' => 'run',
        'E_LEN_MISMATCH' => 'run',
        'E_ABORT' => 'run',
    ];
}
