<?php
// GENERATED by tools/gen-math-ops.mjs from spec/math-ops.json — do not edit; edit the manifest and regenerate.
//
// What the math plan compiles: OPERATORS maps a binary operator token and
// PREFIX a prefix operator name to a symbolic operation; BUILTINS maps a
// builtin name to [op, arity 1 | 2 | 'fold', aux]. OPS lists every operation;
// MathPlan.php maps each to its own MathOpCode and refuses to load if one is
// missing.

declare(strict_types=1);

namespace Sel;

final class MathOps
{
    /** @var array<string,string> */
    public const OPERATORS = [
        '+' => 'ADD',
        '-' => 'SUB',
        '*' => 'MUL',
        '/' => 'DIV',
        '%' => 'MOD',
    ];

    /** @var array<string,string> */
    public const PREFIX = [
        'NEG' => 'NEG',
    ];

    /** @var array<string, array{0:string,1:int|string,2:int|null}> */
    public const BUILTINS = [
        'ABS' => ['ABS', 1, null],
        'SIGN' => ['SIGN', 1, null],
        'CEIL' => ['CEIL', 1, null],
        'FLOOR' => ['FLOOR', 1, null],
        'TRUNC' => ['TRUNC', 1, null],
        'ROUND' => ['ROUND', 2, 1],
        'POWER' => ['POWER', 2, 1],
        'MIN' => ['MIN', 'fold', null],
        'MAX' => ['MAX', 'fold', null],
    ];

    /** @var list<string> */
    public const OPS = ['ADD', 'SUB', 'MUL', 'DIV', 'MOD', 'NEG', 'ABS', 'SIGN', 'CEIL', 'FLOOR', 'TRUNC', 'ROUND', 'POWER', 'MIN', 'MAX'];
}
