;;;; sbcl --script tools/metadata/lisp.lisp [bench]; optional SEL_METADATA_ROOT.
(require :asdf)
(load (merge-pathnames "quicklisp/setup.lisp" (user-homedir-pathname)))
(let ((*standard-output* (make-broadcast-stream))
      (root (uiop:ensure-directory-pathname (or (uiop:getenv "SEL_METADATA_ROOT") "./"))))
  (asdf:load-asd (truename (merge-pathnames "lisp/sel-lang.asd" root)))
  (funcall (find-symbol "QUICKLOAD" "QL") :sel-lang))
(defparameter *leaf* (sel:make-text "1"))
(defun record (keys values)
  (sel::%make-shaped-value (sel::get-record-shape keys) (coerce values 'simple-vector)))
(defun churn (n)
  (dotimes (i n) (record (list (format nil "field_~d" i) "id") (list *leaf* *leaf*))))
(defun aliases (n)
  (let ((join (sel:compile-source "LINK(L, R, O, C, O[\"id\"] == C[\"id\"])") )
        (ctx (sel:make-none)))
    (sel:value-set ctx "R" (sel:make-list-value (list (record '("id") (list *leaf*)))))
    (dotimes (i n)
      (sel:value-set ctx "L" (sel:make-list-value
        (list (record (list "id" (format nil "alias_~d" i)) (list *leaf* *leaf*)))))
      (sel:run join ctx))))
(defun retained () (sb-ext:gc :full t) (sb-kernel:dynamic-usage))
(let* ((ctx (sel:make-none))
       (program (sel:compile-source "RECORD(\"id\", X, \"name\", Y)")))
  (sel:value-set ctx "X" *leaf*) (sel:value-set ctx "Y" (sel:make-text "two"))
  (sel:run program ctx)
  (if (member "bench" sb-ext:*posix-argv* :test #'string=)
      (let ((samples nil) (power-samples nil))
        (dotimes (r 5)
          (let ((start (get-internal-real-time)))
            (dotimes (i 20000) (sel:run program ctx))
            (push (/ (* 1000000d0 (- (get-internal-real-time) start))
                     (* 20000 internal-time-units-per-second)) samples)))
        (dolist (exponent '(100 10000))
          (sel::pow10 exponent)
          (let ((times nil))
            (dotimes (r 5)
              (let ((tick (get-internal-real-time)))
                (dotimes (i 100000) (sel::pow10 exponent))
                (push (/ (* 1000000d0 (- (get-internal-real-time) tick))
                         (* 100000 internal-time-units-per-second)) times)))
            (push (nreverse times) power-samples)))
        (let* ((start (retained))
               (shapes (progn (churn 20000) (- (retained) start)))
               (both (progn (aliases 5000) (- (retained) start)))
               (before-powers (retained)))
          (loop for n from 10000 below 12000 do (sel::pow10 n))
          (format t "{\"runtime\":\"SBCL ~a\",\"steady_us\":[~{~,6f~^,~}],\"shapes_retained\":~d,\"shapes_aliases_retained\":~d,\"powers_retained\":~d,\"power_us\":{\"100\":[~{~,6f~^,~}],\"10000\":[~{~,6f~^,~}]}}~%"
                  (lisp-implementation-version) (nreverse samples) shapes both (- (retained) before-powers)
                  (second power-samples) (first power-samples))))
      (let ((held (record '("held") (list *leaf*)))
            (prepared (sel::value-shape (sel:run program ctx))))
        (churn 2000)
        (let ((again (record '("held") (list *leaf*))))
          (assert (not (eq (sel::value-shape held) (sel::value-shape again))))
          (assert (sel:value-eql held again))
          (assert (= (sel::value-hash held) (sel::value-hash again))))
        (assert (eq prepared (sel::value-shape (sel:run program ctx))))
        (assert (<= (hash-table-count sel::*shape-cache*) 256))
        (dolist (keys (list (loop for i below 257 collect (format nil "wide_~d" i))
                           (list (make-string 16385 :initial-element #\x))))
          (let* ((values (make-list (length keys) :initial-element *leaf*))
                 (a (record keys values)) (b (record keys values)))
            (assert (not (eq (sel::value-shape a) (sel::value-shape b))))
            (assert (sel:value-eql a b))))
        (let ((dynamic (sel:compile-source "RECORD(K, X)")))
          (sel:value-set ctx "K" (sel:make-text "first"))
          (assert (sel:value-has (sel:run dynamic ctx) "first"))
          (sel:value-set ctx "K" (sel:make-text "second"))
          (assert (sel:value-has (sel:run dynamic ctx) "second")))
        (assert (string= "two" (sel::as-text (sel:value-get
          (sel:run (sel:compile-source "RECORD(\"id\", X, \"id\", Y)") ctx) "id"))))
        (aliases 1000)
        (assert (<= (hash-table-count (symbol-value 'sel::*alias-plan-cache*)) 256))
        (assert (<= sel::*alias-plan-cache-count* 256))
        (assert (= sel::*alias-plan-cache-count*
                   (loop for plans being the hash-values of sel::*alias-plan-cache*
                         sum (hash-table-count plans))))
        (loop for n from 65 below 300 do (assert (= (sel::pow10 n) (expt 10 n))))
        (assert (= (sel::pow10 10000) (expt 10 10000)))
        (loop for n from 100000 below 400000 by 20000
              do (assert (= (sel::pow10 n) (expt 10 n))))
        (assert (= (sel::pow10 1000001) (expt 10 1000001)))
        (assert (<= (hash-table-count sel::*pow10-cache*) 64))
        (assert (loop for k being the hash-keys of sel::*pow10-cache* always (<= k 1000000)))
        (assert (<= (loop for k being the hash-keys of sel::*pow10-cache* sum k) 1048576))
        (format t "Lisp metadata checks passed~%"))))
