#!/usr/bin/env node
// Renders spec/lexicon.json — the reserved words, operator tokens and the
// precedence table — into every host's source language and into
// docs/reference/lexicon.md, after checking that spec/grammar.md and
// spec/SPEC.md §5 still say the same thing.
//
//     node tools/gen-lexicon.mjs            write the generated files
//     node tools/gen-lexicon.mjs --check    validate and diff, write nothing
//
// The renderings ARE committed (see tools/gen-builtins.mjs for why). Each
// host's lexer takes its token list and reserved words from its rendering, its
// parser builds its binding-power table from it, and the evaluator, optimiser,
// join pre-filter and SQL translator ask its per-operator record (family,
// relation, compound operator, short circuit) instead of keeping string lists
// of their own. Like spec/limits.json, the lexicon is NOT a second authority:
// the grammar and §5 are, and this generator fails when the lexicon says
// something they do not.

import { readFileSync } from 'node:fs';
import { genArgs, writeOrCheck, jsStr, pyStr, phpStr, cppStr, lispStr, goStr, rustStr } from './gen-lib.mjs';
import { fileURLToPath } from 'node:url';
import { dirname, resolve } from 'node:path';

const ROOT = resolve(dirname(fileURLToPath(import.meta.url)), '..');
const USAGE = `usage: node tools/gen-lexicon.mjs            write the generated files
       node tools/gen-lexicon.mjs --check    validate and diff, write nothing`;
const { check } = genArgs('gen-lexicon', USAGE);
const SOURCE = 'spec/lexicon.json';

const OUTPUTS = {
  js: 'js/src/_lexicon.mjs',
  python: 'python/sel/_lexicon.py',
  php: 'php/src/Lexicon.php',
  cpp: 'cpp/sel_lexicon.hpp',
  lisp: 'lisp/src/lexicon.lisp',
  go: 'go/internal/lexicon/lexicon.go',
  rust: 'rust/src/lexicon.rs',
  docs: 'docs/reference/lexicon.md',
};

const HEADER = `GENERATED by tools/gen-lexicon.mjs from ${SOURCE} — do not edit; edit the lexicon and regenerate.`;

function fail(msg) {
  process.stderr.write(`gen-lexicon: ${msg}\n`);
  process.exit(1);
}

// The relations of the two comparison families, in the order every host
// numbers them (C++'s contiguous BinOp codes, Lisp's and Rust's comparison
// helpers): the index is what a host may store.
const RELATIONS = ['eq', 'ne', 'lt', 'le', 'gt', 'ge'];
const FIXITIES = ['infix', 'prefix', 'postfix'];
const ASSOCS = { left: 'L', right: 'R', none: 'N' };
const OP_KEYS = new Set(['family', 'relation', 'compound', 'shortCircuit', 'name', 'node']);
// The parse-tree node an infix operator builds, by family; every other family
// builds a binary node.
const INFIX_NODE = { assign: 'assign', list: 'list', sequence: 'seq' };
const isWord = (t) => /^[A-Z][A-Z0-9_]*$/.test(t);

// ---------------------------------------------------------------------------
// Validation (spec/lexicon.md).

function load() {
  const doc = JSON.parse(readFileSync(resolve(ROOT, SOURCE), 'utf8'));
  for (const k of Object.keys(doc)) {
    if (!['$comment', 'reserved', 'punctuation', 'families', 'levels'].includes(k)) fail(`${k}: unknown key`);
  }
  const reserved = doc.reserved;
  if (!Array.isArray(reserved) || reserved.length === 0) fail('reserved: a non-empty list');
  for (const w of reserved) if (!isWord(w)) fail(`reserved: "${w}" is not an upper-case ASCII word`);
  if (new Set(reserved).size !== reserved.length) fail('reserved: a word is listed twice');

  const punctuation = doc.punctuation;
  if (!Array.isArray(punctuation)) fail('punctuation: a list');
  for (const p of punctuation) if (typeof p !== 'string' || p === '' || isWord(p)) fail(`punctuation: "${p}" is not a symbol token`);

  const families = doc.families;
  if (!families || typeof families !== 'object') fail('families: an object');
  for (const [f, e] of Object.entries(families)) {
    if (!/^[a-z][a-z-]*$/.test(f)) fail(`families.${f}: a family name is lower-case`);
    if (typeof e.spec !== 'string' || !/^§\d+(\.\d+)*$/.test(e.spec)) fail(`families.${f}.spec: "§n.m"`);
    if (typeof e.title !== 'string' || e.title === '') fail(`families.${f}.title: required`);
    for (const k of Object.keys(e)) if (!['spec', 'title'].includes(k)) fail(`families.${f}.${k}: unknown key`);
  }

  const levels = doc.levels;
  if (!Array.isArray(levels) || levels.length === 0) fail('levels: a non-empty list, tightest first');
  const ops = [];
  const levelNames = new Set();
  const seen = new Set();
  levels.forEach((lv, i) => {
    const where = `levels[${i}]`;
    for (const k of Object.keys(lv)) if (!['name', 'fixity', 'assoc', 'operators'].includes(k)) fail(`${where}.${k}: unknown key`);
    if (typeof lv.name !== 'string' || !/^[A-Z][A-Z0-9_]*$/.test(lv.name)) fail(`${where}.name: upper-case`);
    if (levelNames.has(lv.name)) fail(`${where}.name: ${lv.name} twice`);
    levelNames.add(lv.name);
    if (!FIXITIES.includes(lv.fixity)) fail(`${where}.fixity: ${FIXITIES.join(' | ')}`);
    if (lv.fixity === 'infix') {
      if (!Object.hasOwn(ASSOCS, lv.assoc)) fail(`${where}.assoc: left | right | none`);
    } else if (lv.assoc !== undefined) {
      fail(`${where}.assoc: only an infix level associates`);
    }
    if (!lv.operators || typeof lv.operators !== 'object' || Object.keys(lv.operators).length === 0) {
      fail(`${where}.operators: a non-empty object`);
    }
    // Binding power: the loosest level binds at 1, each tighter one at one more
    // (SPEC §5 numbers the rows the other way round, tightest first).
    const bp = levels.length - i;
    for (const [token, e] of Object.entries(lv.operators)) {
      const ow = `${where}.operators["${token}"]`;
      for (const k of Object.keys(e)) if (!OP_KEYS.has(k)) fail(`${ow}.${k}: unknown key`);
      const key = `${lv.fixity === 'infix' ? 'infix' : 'other'}:${token}`;
      if (seen.has(key)) fail(`${ow}: claimed twice`);
      seen.add(key);
      const word = isWord(token);
      if (word && !reserved.includes(token)) fail(`${ow}: a word operator must be reserved`);
      if (!word && /[A-Za-z0-9_\s]/.test(token)) fail(`${ow}: a symbol token is punctuation only`);
      if (!Object.hasOwn(families, e.family)) fail(`${ow}.family: not one of the families`);
      const compares = e.family === 'compare' || e.family === 'text-compare';
      if (compares !== (e.relation !== undefined)) fail(`${ow}.relation: exactly the two comparison families have one`);
      if (e.relation !== undefined && !RELATIONS.includes(e.relation)) fail(`${ow}.relation: ${RELATIONS.join(' | ')}`);
      if (e.shortCircuit !== undefined && e.shortCircuit !== true) fail(`${ow}.shortCircuit: true or absent`);
      if (e.shortCircuit && lv.fixity !== 'infix') fail(`${ow}.shortCircuit: only a binary operator`);
      if ((lv.fixity === 'prefix') !== (e.name !== undefined)) fail(`${ow}.name: exactly a prefix operator has one`);
      if (e.name !== undefined && !/^[A-Z]+$/.test(e.name)) fail(`${ow}.name: upper-case`);
      if ((lv.fixity === 'postfix') !== (e.node !== undefined)) fail(`${ow}.node: exactly a postfix operator has one`);
      if (e.node !== undefined && !['index', 'pipe'].includes(e.node)) fail(`${ow}.node: index | pipe`);
      if (e.compound !== undefined && e.family !== 'assign') fail(`${ow}.compound: only an assignment`);
      const node = lv.fixity === 'prefix' ? 'un' : lv.fixity === 'postfix' ? e.node : (INFIX_NODE[e.family] ?? 'bin');
      ops.push({
        token, word, fixity: lv.fixity, level: lv.name, bp,
        assoc: lv.fixity === 'infix' ? ASSOCS[lv.assoc] : null,
        family: e.family, node, name: e.name ?? null,
        relation: e.relation ?? null, compound: e.compound ?? null, shortCircuit: !!e.shortCircuit,
      });
    }
  });
  // A compound assignment applies a binary operator of the arithmetic or
  // concatenation family (§5.8).
  for (const o of ops) {
    if (o.compound === null) continue;
    const target = ops.find((x) => x.fixity === 'infix' && x.token === o.compound && x.node === 'bin');
    if (!target) fail(`${o.token}: compound "${o.compound}" is not a binary operator`);
    if (o.token !== o.compound + '=') fail(`${o.token}: a compound assignment is spelled <operator>=`);
  }
  for (const w of reserved) {
    if (isWord(w) && !ops.some((o) => o.token === w) && !['TRUE', 'FALSE', 'NULL'].includes(w)) {
      fail(`reserved: ${w} is neither an operator nor a literal`);
    }
  }
  for (const p of punctuation) if (ops.some((o) => o.token === p)) fail(`punctuation: "${p}" is an operator`);
  for (const f of Object.keys(families)) if (!ops.some((o) => o.family === f)) fail(`families.${f}: no operator has it`);

  // Every symbol the lexer knows, longest first: maximal munch is the only
  // ordering rule (spec/grammar.md), and two tokens that can both match at a
  // position are one a prefix of the other.
  const symbols = [];
  for (const t of [...ops.map((o) => o.token), ...punctuation]) if (!isWord(t) && !symbols.includes(t)) symbols.push(t);
  const ordered = symbols.map((t, i) => [t, i]).sort((a, b) => b[0].length - a[0].length || a[1] - b[1]).map(([t]) => t);

  const bps = levels.map((lv, i) => [lv.name, levels.length - i]);
  return { reserved, punctuation, families, levels, ops, symbols: ordered, bps };
}

// ---------------------------------------------------------------------------
// The spec text must agree. Nothing is rendered from it; it is checked.

function checkSpec(lex) {
  const grammar = readFileSync(resolve(ROOT, 'spec/grammar.md'), 'utf8');
  const spec = readFileSync(resolve(ROOT, 'spec/SPEC.md'), 'utf8');
  const sameSet = (a, b) => a.length === b.length && a.every((x) => b.includes(x));

  const rm = grammar.match(/Reserved: `([^`]*)`/);
  if (!rm) fail('spec/grammar.md: no "Reserved: `...`" line');
  const words = rm[1].trim().split(/\s+/);
  if (words.join(' ') !== lex.reserved.join(' ')) {
    fail(`spec/grammar.md reserves ${words.join(' ')}; the lexicon ${lex.reserved.join(' ')}`);
  }

  const bm = grammar.match(/Operator tokens[\s\S]*?```\n([\s\S]*?)```/);
  if (!bm) fail('spec/grammar.md: no operator token block');
  const tokens = bm[1].split(/\s+/).filter(Boolean);
  if (!sameSet(tokens, lex.symbols)) {
    fail(`spec/grammar.md's operator tokens (${tokens.join(' ')}) are not the lexicon's (${lex.symbols.join(' ')})`);
  }
  // The grammar's own order must honour maximal munch too.
  tokens.forEach((t, i) => {
    for (let j = 0; j < i; j++) {
      if (t.startsWith(tokens[j]) && t !== tokens[j]) fail(`spec/grammar.md lists ${tokens[j]} before ${t}`);
    }
  });

  const production = (name) => {
    const m = grammar.match(new RegExp(`^${name}\\s*=([^\\n]*(?:\\n\\s+\\|[^\\n]*)*)`, 'm'));
    if (!m) fail(`spec/grammar.md: no ${name} production`);
    return [...m[1].replace(/\(\*.*?\*\)/g, '').matchAll(/"([^"]+)"/g)].map((x) => x[1]);
  };
  const levelTokens = (name) => lex.ops.filter((o) => o.level === name).map((o) => o.token);
  if (!sameSet(production('assign_op'), levelTokens('ASSIGN'))) fail('spec/grammar.md assign_op is not the ASSIGN level');
  if (!sameSet(production('compare_op'), levelTokens('COMPARE'))) fail('spec/grammar.md compare_op is not the COMPARE level');

  // SPEC §5's table: one row per level, tightest first, the same operators and
  // the same associativity.
  const sec = spec.match(/## 5\. Operators\n([\s\S]*?)\n### /);
  if (!sec) fail('spec/SPEC.md: no §5');
  const rows = sec[1].split('\n').filter((l) => /^\| \d+ \|/.test(l));
  if (rows.length !== lex.levels.length) fail(`spec/SPEC.md §5 has ${rows.length} rows; the lexicon ${lex.levels.length} levels`);
  rows.forEach((row, i) => {
    const cells = row.split('|').map((c) => c.trim());
    const lv = lex.levels[i];
    if (Number(cells[1]) !== i + 1) fail(`spec/SPEC.md §5 row ${i + 1} is numbered ${cells[1]}`);
    const spans = [...cells[2].matchAll(/`([^`]+)`/g)].map((m) => m[1]);
    const mine = Object.keys(lv.operators);
    const assoc = cells[3].replace(/\*/g, '');
    if (lv.fixity === 'postfix') {
      for (const t of mine) if (!spans.some((s) => s.includes(t))) fail(`spec/SPEC.md §5 row ${i + 1} lacks ${t}`);
      return;
    }
    if (lv.fixity === 'prefix') {
      const stripped = spans.map((s) => s.replace(/\s*x$/, ''));
      if (!sameSet(stripped, mine)) fail(`spec/SPEC.md §5 row ${i + 1} (${spans.join(' ')}) is not level ${lv.name}`);
      if (assoc !== 'prefix') fail(`spec/SPEC.md §5 row ${i + 1} is not marked prefix`);
      return;
    }
    if (!sameSet(spans, mine)) fail(`spec/SPEC.md §5 row ${i + 1} (${spans.join(' ')}) is not level ${lv.name} (${mine.join(' ')})`);
    if (assoc !== lv.assoc) fail(`spec/SPEC.md §5 row ${i + 1} associates ${assoc}; level ${lv.name} ${lv.assoc}`);
  });
}

// ---------------------------------------------------------------------------
// Renderers. Every string literal goes through the host's own escaping.

const camel = (f) => f.replace(/(^|-)([a-z])/g, (_, __, c) => c.toUpperCase());
const relIndex = (o) => (o.relation === null ? -1 : RELATIONS.indexOf(o.relation));

function renderJs(lex) {
  const l = [`// ${HEADER}`, '//',
    '// RESERVED: the reserved words. SYMBOLS: every symbol token, longest first.',
    '// BP: each precedence level\'s binding power (higher binds tighter). OPS: one',
    '// record per operator, tightest level first: token, word (lexes as an',
    '// identifier), fixity, level, bp, assoc (\'L\' | \'R\' | \'N\', null unless',
    '// infix), family, node (the parse-tree node it builds), name (a prefix',
    '// operator\'s node name), relation (index into RELATIONS, -1 when none),',
    '// compound (the binary operator a compound assignment applies) and',
    '// shortCircuit (the right operand may never run).', '',
    `export const RESERVED = Object.freeze([${lex.reserved.map(jsStr).join(', ')}]);`, '',
    `export const SYMBOLS = Object.freeze([${lex.symbols.map(jsStr).join(', ')}]);`, '',
    `export const RELATIONS = Object.freeze([${RELATIONS.map(jsStr).join(', ')}]);`, '',
    'export const BP = Object.freeze({'];
  for (const [n, bp] of lex.bps) l.push(`  ${n}: ${bp},`);
  l.push('});', '', 'export const OPS = Object.freeze([');
  for (const o of lex.ops) {
    l.push(`  Object.freeze({ token: ${jsStr(o.token)}, word: ${o.word}, fixity: ${jsStr(o.fixity)}, level: ${jsStr(o.level)}, bp: ${o.bp}, assoc: ${o.assoc === null ? 'null' : jsStr(o.assoc)}, family: ${jsStr(o.family)}, node: ${jsStr(o.node)}, name: ${o.name === null ? 'null' : jsStr(o.name)}, relation: ${relIndex(o)}, compound: ${o.compound === null ? 'null' : jsStr(o.compound)}, shortCircuit: ${o.shortCircuit} }),`);
  }
  l.push(']);', '');
  return l.join('\n');
}

function renderPython(lex) {
  const py = (v) => (v === null ? 'None' : typeof v === 'boolean' ? (v ? 'True' : 'False') : typeof v === 'number' ? String(v) : pyStr(v));
  const l = [`# ${HEADER}`, '#',
    '# RESERVED: the reserved words. SYMBOLS: every symbol token, longest first.',
    '# BP: each precedence level\'s binding power (higher binds tighter). OPS: one',
    '# Op per operator, tightest level first; see spec/lexicon.md for the fields.',
    '# relation indexes RELATIONS (-1 when none); assoc is \'L\', \'R\', \'N\' or None.', '',
    'from typing import NamedTuple, Optional', '', '',
    'class Op(NamedTuple):',
    '    token: str', '    word: bool', '    fixity: str', '    level: str', '    bp: int',
    '    assoc: Optional[str]', '    family: str', '    node: str', '    name: Optional[str]',
    '    relation: int', '    compound: Optional[str]', '    short_circuit: bool', '', '',
    `RESERVED = (${lex.reserved.map(pyStr).join(', ')})`, '',
    `SYMBOLS = (${lex.symbols.map(pyStr).join(', ')})`, '',
    `RELATIONS = (${RELATIONS.map(pyStr).join(', ')})`, '',
    'BP = {'];
  for (const [n, bp] of lex.bps) l.push(`    ${pyStr(n)}: ${bp},`);
  l.push('}', '', 'OPS = (');
  for (const o of lex.ops) {
    l.push(`    Op(${[o.token, o.word, o.fixity, o.level, o.bp, o.assoc, o.family, o.node, o.name, relIndex(o), o.compound, o.shortCircuit].map(py).join(', ')}),`);
  }
  l.push(')', '');
  return l.join('\n');
}

function renderPhp(lex) {
  const ph = (v) => (v === null ? 'null' : typeof v === 'boolean' ? String(v) : typeof v === 'number' ? String(v) : phpStr(v));
  const l = ['<?php', `// ${HEADER}`, '//',
    '// RESERVED: the reserved words. SYMBOLS: every symbol token, longest first.',
    '// BP: each precedence level\'s binding power (higher binds tighter). OPS: one',
    '// row per operator, tightest level first; see spec/lexicon.md for the fields.',
    "// relation indexes RELATIONS (-1 when none); assoc is 'L', 'R', 'N' or null.", '',
    'declare(strict_types=1);', '', 'namespace Sel;', '', 'final class Lexicon', '{',
    '    /** @var list<string> */',
    `    public const RESERVED = [${lex.reserved.map(phpStr).join(', ')}];`, '',
    '    /** @var list<string> */',
    `    public const SYMBOLS = [${lex.symbols.map(phpStr).join(', ')}];`, '',
    '    /** @var list<string> */',
    `    public const RELATIONS = [${RELATIONS.map(phpStr).join(', ')}];`, '',
    '    /** @var array<string,int> */', '    public const BP = ['];
  for (const [n, bp] of lex.bps) l.push(`        ${phpStr(n)} => ${bp},`);
  l.push('    ];', '',
    '    /** @var list<array{token:string,word:bool,fixity:string,level:string,bp:int,assoc:?string,family:string,node:string,name:?string,relation:int,compound:?string,shortCircuit:bool}> */',
    '    public const OPS = [');
  for (const o of lex.ops) {
    l.push(`        ['token' => ${ph(o.token)}, 'word' => ${ph(o.word)}, 'fixity' => ${ph(o.fixity)}, 'level' => ${ph(o.level)}, 'bp' => ${o.bp}, 'assoc' => ${ph(o.assoc)}, 'family' => ${ph(o.family)}, 'node' => ${ph(o.node)}, 'name' => ${ph(o.name)}, 'relation' => ${relIndex(o)}, 'compound' => ${ph(o.compound)}, 'shortCircuit' => ${ph(o.shortCircuit)}],`);
  }
  l.push('    ];', '}', '');
  return l.join('\n');
}

function renderCpp(lex) {
  const fams = Object.keys(lex.families);
  const cs = (v) => (v === null ? 'nullptr' : cppStr(v));
  const l = [`// ${HEADER}`, '//',
    '// RESERVED: the reserved words. SYMBOLS: every symbol token, longest first.',
    '// BP_<LEVEL>: each precedence level\'s binding power (higher binds tighter).',
    '// OPS: one entry per operator, tightest level first; see spec/lexicon.md for',
    '// the fields. relation is an index into eq ne lt le gt ge (-1 when none);',
    '// assoc is \'L\', \'R\', \'N\', or 0 unless infix.',
    '#pragma once', '', 'namespace sel_lexicon {', '',
    'enum class Fixity : unsigned char { Infix, Prefix, Postfix };', '',
    `enum class Family : unsigned char { ${fams.map(camel).join(', ')} };`, '',
    'struct Op {', '  const char* token;', '  bool word;', '  Fixity fixity;', '  const char* level;',
    '  int bp;', '  char assoc;', '  Family family;', '  const char* node;', '  const char* name;',
    '  int relation;', '  const char* compound;', '  bool short_circuit;', '};', '',
    `inline const char* const RESERVED[] = {${lex.reserved.map(cppStr).join(', ')}};`,
    `inline constexpr int RESERVED_COUNT = ${lex.reserved.length};`, '',
    `inline const char* const SYMBOLS[] = {${lex.symbols.map(cppStr).join(', ')}};`,
    `inline constexpr int SYMBOL_COUNT = ${lex.symbols.length};`, ''];
  for (const [n, bp] of lex.bps) l.push(`inline constexpr int BP_${n} = ${bp};`);
  l.push('', 'inline const Op OPS[] = {');
  for (const o of lex.ops) {
    l.push(`  {${cppStr(o.token)}, ${o.word}, Fixity::${camel(o.fixity)}, ${cppStr(o.level)}, ${o.bp}, ${o.assoc === null ? '0' : `'${o.assoc}'`}, Family::${camel(o.family)}, ${cppStr(o.node)}, ${cs(o.name)}, ${relIndex(o)}, ${cs(o.compound)}, ${o.shortCircuit}},`);
  }
  l.push('};', '', `inline constexpr int OP_COUNT = ${lex.ops.length};`, '', '}  // namespace sel_lexicon', '');
  return l.join('\n');
}

function renderLisp(lex) {
  const lv = (v) => (v === null ? 'nil' : typeof v === 'boolean' ? (v ? 't' : 'nil') : typeof v === 'number' ? String(v) : lispStr(v));
  const kw = (s) => ':' + s.toLowerCase();
  const l = [`;;;; ${HEADER}`, ';;;;',
    ';;;; *LEXICON-RESERVED*: the reserved words. *LEXICON-SYMBOLS*: every symbol',
    ';;;; token, longest first. *LEXICON-BP*: (level . binding power), higher binds',
    ';;;; tighter. *LEXICON-OPS*: one plist per operator, tightest level first; see',
    ';;;; spec/lexicon.md for the fields. :relation is an index into eq ne lt le gt',
    ';;;; ge (-1 when none); :assoc is #\\L, #\\R, #\\N or NIL.', '',
    '(in-package #:sel)', '',
    `(defparameter *lexicon-reserved* '(${lex.reserved.map(lispStr).join(' ')}))`, '',
    `(defparameter *lexicon-symbols* '(${lex.symbols.map(lispStr).join(' ')}))`, '',
    '(defparameter *lexicon-bp*', "  '("];
  for (const [n, bp] of lex.bps) l.push(`    (${kw(n)} . ${bp})`);
  l[l.length - 1] += '))';
  l.push('', '(defparameter *lexicon-ops*', "  '(");
  for (const o of lex.ops) {
    l.push(`    (${lispStr(o.token)} :word ${lv(o.word)} :fixity ${kw(o.fixity)} :level ${kw(o.level)} :bp ${o.bp} :assoc ${o.assoc === null ? 'nil' : '#\\' + o.assoc} :family ${kw(o.family)} :node ${kw(o.node)} :name ${lv(o.name)} :relation ${relIndex(o)} :compound ${lv(o.compound)} :short-circuit ${lv(o.shortCircuit)})`);
  }
  l[l.length - 1] += '))';
  l.push('');
  return l.join('\n');
}

// gofmt's layout, so the rendering needs no formatter: tabs, struct fields
// aligned, one composite literal per line.
function renderGo(lex) {
  const fams = Object.keys(lex.families);
  const gs = (v) => (v === null ? '""' : goStr(v));
  const fields = [['Token', 'string'], ['Word', 'bool'], ['Fixity', 'Fixity'], ['Level', 'string'], ['BP', 'int'],
    ['Assoc', 'byte'], ['Family', 'Family'], ['Node', 'string'], ['Name', 'string'], ['Relation', 'int'],
    ['Compound', 'string'], ['ShortCircuit', 'bool']];
  const w = Math.max(...fields.map(([n]) => n.length));
  const l = [`// ${HEADER}`, '//',
    '// Reserved: the reserved words. Symbols: every symbol token, longest first.',
    '// BP<Level>: each precedence level\'s binding power (higher binds tighter).',
    '// Ops: one entry per operator, tightest level first; see spec/lexicon.md.',
    '// Assoc is \'L\', \'R\', \'N\', or 0 unless infix; Name is a prefix operator\'s',
    '// node name; Relation indexes eq ne lt le gt ge (-1 when none); Compound is',
    '// the binary operator a compound assignment applies.', '',
    'package lexicon', '',
    'type Fixity uint8', '', 'const (', '\tInfix Fixity = iota', '\tPrefix', '\tPostfix', ')', '',
    'type Family uint8', '', 'const ('];
  fams.forEach((f, i) => l.push(i === 0 ? `\tFamily${camel(f)} Family = iota` : `\tFamily${camel(f)}`));
  l.push(')', '', 'type Op struct {');
  for (const [n, t] of fields) l.push(`\t${n.padEnd(w)} ${t}`);
  l.push('}', '',
    `var Reserved = []string{${lex.reserved.map(goStr).join(', ')}}`, '',
    `var Symbols = []string{${lex.symbols.map(goStr).join(', ')}}`, '', 'const (');
  const bw = Math.max(...lex.bps.map(([n]) => `BP${camel(n.toLowerCase())}`.length));
  for (const [n, bp] of lex.bps) l.push(`\t${`BP${camel(n.toLowerCase())}`.padEnd(bw)} = ${bp}`);
  l.push(')', '', 'var Ops = []Op{');
  for (const o of lex.ops) {
    l.push(`\t{Token: ${goStr(o.token)}, Word: ${o.word}, Fixity: ${camel(o.fixity)}, Level: ${goStr(o.level)}, BP: ${o.bp}, Assoc: ${o.assoc === null ? '0' : `'${o.assoc}'`}, Family: Family${camel(o.family)}, Node: ${goStr(o.node)}, Name: ${gs(o.name)}, Relation: ${relIndex(o)}, Compound: ${gs(o.compound)}, ShortCircuit: ${o.shortCircuit}},`);
  }
  l.push('}', '');
  return l.join('\n');
}

function renderRust(lex) {
  const fams = Object.keys(lex.families);
  const opt = (v) => (v === null ? 'None' : `Some(${rustStr(v)})`);
  const l = [`// ${HEADER}`, '//',
    '// RESERVED: the reserved words. SYMBOLS: every symbol token, longest first.',
    '// BP_<LEVEL>: each precedence level\'s binding power (higher binds tighter).',
    '// OPS: one entry per operator, tightest level first; see spec/lexicon.md for',
    '// the fields. infix_symbol / infix_word / prefix answer the parser\'s lookups',
    '// with a match, so the table costs nothing per token.', '',
    '#[derive(Clone, Copy, Debug, PartialEq, Eq)]', 'pub enum Fixity {', '    Infix,', '    Prefix,', '    Postfix,', '}', '',
    '#[derive(Clone, Copy, Debug, PartialEq, Eq)]', 'pub enum Assoc {', '    Left,', '    Right,', '    NonAssoc,', '}', '',
    '#[derive(Clone, Copy, Debug, PartialEq, Eq)]', 'pub enum Family {'];
  for (const f of fams) l.push(`    ${camel(f)},`);
  l.push('}', '',
    '#[derive(Clone, Copy, Debug, PartialEq, Eq)]', 'pub enum Relation {', '    Eq,', '    Ne,', '    Lt,', '    Le,', '    Gt,', '    Ge,', '}', '',
    '#[derive(Clone, Copy, Debug)]', 'pub struct Op {',
    "    pub token: &'static str,",
    '    pub word: bool,', '    pub fixity: Fixity,', "    pub level: &'static str,", '    pub bp: u8,',
    '    pub assoc: Option<Assoc>,', '    pub family: Family,', "    pub node: &'static str,",
    "    pub name: Option<&'static str>,", '    pub relation: Option<Relation>,',
    "    pub compound: Option<&'static str>,", '    pub short_circuit: bool,', '}', '',
    `pub const RESERVED: &[&str] = &[${lex.reserved.map(rustStr).join(', ')}];`, '',
    `pub const SYMBOLS: &[&str] = &[${lex.symbols.map(rustStr).join(', ')}];`, '');
  for (const [n, bp] of lex.bps) l.push(`pub const BP_${n}: u8 = ${bp};`);
  l.push('', 'pub const OPS: &[Op] = &[');
  const assocR = { L: 'Some(Assoc::Left)', R: 'Some(Assoc::Right)', N: 'Some(Assoc::NonAssoc)' };
  for (const o of lex.ops) {
    l.push(`    Op { token: ${rustStr(o.token)}, word: ${o.word}, fixity: Fixity::${camel(o.fixity)}, level: ${rustStr(o.level)}, bp: ${o.bp}, assoc: ${o.assoc === null ? 'None' : assocR[o.assoc]}, family: Family::${camel(o.family)}, node: ${rustStr(o.node)}, name: ${opt(o.name)}, relation: ${o.relation === null ? 'None' : `Some(Relation::${camel(o.relation)})`}, compound: ${opt(o.compound)}, short_circuit: ${o.shortCircuit} },`);
  }
  l.push('];', '');
  const lookup = (fn, doc, pick) => {
    l.push(doc, `pub fn ${fn}(token: &str) -> Option<&'static Op> {`, '    match token {');
    lex.ops.forEach((o, i) => { if (pick(o)) l.push(`        ${rustStr(o.token)} => Some(&OPS[${i}]),`); });
    l.push('        _ => None,', '    }', '}', '');
  };
  lookup('infix_symbol', '/// A symbol token as an infix operator.', (o) => o.fixity === 'infix' && !o.word);
  lookup('infix_word', '/// A word (an identifier token) as an infix operator.', (o) => o.fixity === 'infix' && o.word);
  lookup('prefix', '/// A token as a prefix operator.', (o) => o.fixity === 'prefix');
  l.pop();
  l.push('');
  return l.join('\n');
}

function renderDocs(lex) {
  const code = (t) => '`' + t + '`';
  const l = [`<!-- ${HEADER} -->`, '# Lexicon', '',
    'The reserved words, the operator tokens and the precedence table, from',
    '`spec/lexicon.json` (format: `spec/lexicon.md`), which `tools/gen-lexicon.mjs`',
    'checks against `spec/grammar.md` and `spec/SPEC.md` §5 before rendering — the',
    'prose there defines them; this page lists them. Every host\'s lexer and parser',
    'are built from the same table.', '',
    '## Reserved words', '',
    lex.reserved.map(code).join(' '), '',
    'Reserved words are case-insensitive, like every identifier, and cannot name a',
    'variable.', '',
    '## Operator tokens', '',
    'Longest match first:', '',
    lex.symbols.map(code).join(' '), '',
    '## Precedence', '',
    'Tightest first. *Binding power* is the number the parsers climb by (higher',
    'binds tighter).', '',
    '| # | Binding power | Operators | Associativity | Family |', '|---|---|---|---|---|'];
  lex.levels.forEach((lv, i) => {
    const mine = lex.ops.filter((o) => o.level === lv.name);
    const assoc = lv.fixity === 'infix' ? { left: 'left', right: 'right', none: '**none**' }[lv.assoc] : lv.fixity;
    const fams = [...new Set(mine.map((o) => o.family))].map((f) => `${lex.families[f].title} (${lex.families[f].spec})`).join(', ');
    l.push(`| ${i + 1} | ${lex.levels.length - i} | ${mine.map((o) => code(o.token)).join(' ')} | ${assoc} | ${fams} |`);
  });
  l.push('', '## Operators', '',
    '| Operator | Fixity | Family | Comparison | Notes |', '|---|---|---|---|---|');
  for (const o of lex.ops) {
    const notes = [];
    if (o.name) notes.push(`parse-tree name ${code(o.name)}`);
    if (o.compound) notes.push(`applies ${code(o.compound)}`);
    if (o.shortCircuit) notes.push('short-circuit: the right operand may not run');
    l.push(`| ${code(o.token)} | ${o.fixity} | ${o.family} | ${o.relation ?? ''} | ${notes.join('; ')} |`);
  }
  l.push('', `${lex.ops.length} operators on ${lex.levels.length} levels; ${lex.reserved.length} reserved words; ${lex.symbols.length} symbol tokens.`, '');
  return l.join('\n');
}

const lex = load();
checkSpec(lex);
const rendered = {
  js: renderJs(lex), python: renderPython(lex), php: renderPhp(lex),
  cpp: renderCpp(lex), lisp: renderLisp(lex), go: renderGo(lex),
  rust: renderRust(lex), docs: renderDocs(lex),
};
writeOrCheck('gen-lexicon', ROOT, Object.entries(OUTPUTS).map(([host, path]) => [path, rendered[host]]),
  { check, rerun: 'node tools/gen-lexicon.mjs' });
if (check) process.stdout.write(`gen-lexicon: ${lex.ops.length} operators, ${Object.keys(OUTPUTS).length} renderings current\n`);
