#!/usr/bin/env node
// Renders spec/limits.json — the normative limits and error catalogue — into
// every host's constants and into docs/reference/limits.md, after checking that the spec
// text still states every fact in it.
//
//     node tools/gen-limits.mjs            write the generated files
//     node tools/gen-limits.mjs --check    validate and diff, write nothing
//
// The renderings ARE committed (see tools/gen-builtins.mjs for why). The
// manifest is deliberately NOT an authority: spec/SPEC.md and spec/errors.md
// are, and this generator fails when the manifest says something they do not.

import { readFileSync } from 'node:fs';
import { genArgs, writeOrCheck, jsStr, pyStr, phpStr, cppStr, lispStr } from './gen-lib.mjs';
import { fileURLToPath } from 'node:url';
import { dirname, resolve } from 'node:path';

const ROOT = resolve(dirname(fileURLToPath(import.meta.url)), '..');
const USAGE = `usage: node tools/gen-limits.mjs            write the generated files
       node tools/gen-limits.mjs --check    validate and diff, write nothing`;
const { check } = genArgs('gen-limits', USAGE);
const SOURCE = 'spec/limits.json';
const OUTPUTS = {
  js: 'js/src/_limits.mjs',
  python: 'python/sel/_limits.py',
  php: 'php/src/Limits.php',
  cpp: 'cpp/sel_limits.hpp',
  lisp: 'lisp/src/limits.lisp',
  go: 'go/internal/limits/limits.go',
  rust: 'rust/src/limits.rs',
  docs: 'docs/reference/limits.md',
};
const HEADER = `GENERATED by tools/gen-limits.mjs from ${SOURCE} — do not edit; edit the manifest and regenerate.`;

function fail(msg) {
  process.stderr.write(`gen-limits: ${msg}\n`);
  process.exit(1);
}

// The spec's own statements of each number, as written there. A limit is
// accepted only if its sentence is found.
const SPEC_STATEMENTS = {
  MAX_DEPTH: (v) => [`at least ${v})`],
  MAX_INT_DIGITS: (v) => [`| integer digits of a number | ${spaced(v)} |`],
  MAX_FRAC_DIGITS: (v) => [`| fractional digits of a number | ${spaced(v)} |`],
  MAX_TEXT_LEN: (v) => [`| a TEXT value's code points, a BIN value's bytes | ${spaced(v)} |`],
  MAX_COLLECTION: (v) => [`| the children of a collection an operation builds | ${spaced(v)} |`],
  MAX_REGEX_PATTERN: (v) => [`| a regex pattern's code points | ${spaced(v)} |`],
  MAX_REGEX_GROUPS: (v) => [`| the groups in a regex pattern | ${spaced(v)} |`],
  MAX_SQL_NODES: (v) => [`| the nodes of a translated SQL expression | ${spaced(v)} |`],
  DIV_SCALE: (v) => ['`DIV_SCALE` is **' + v + '**'],
  MAX_ROUND_SCALE: (v) => [`| \`ROUND(x, n)\` scale | ${spaced(v)} |`],
  MAX_POWER_EXPONENT: (v) => [`| \`POWER(x, n)\` exponent | ${spaced(v)} |`],
  MAX_REGEX_QUANTIFIER: (v) => [`| a regex quantifier bound, as in \`a{n}\` or \`a{n,m}\` | ${spaced(v)} |`],
  // §7.8's ambiguity rule states its budget in words and its caps as powers of
  // two; the spec text is matched with its line breaks folded to spaces.
  REGEX_AMBIGUITY_BUDGET: (v) => [`More than ${v} is refused.`],
  REGEX_ANALYSIS_POSITIONS: (v) => [`More than ${pow2(v)} positions`],
  REGEX_ANALYSIS_EDGES: (v) => [`more than ${pow2(v)} follow edges`],
  REGEX_ANALYSIS_RANGES: (v) => [`a sum over edges of the number of ranges at the target above ${pow2(v)}`],
  REGEX_ANALYSIS_PAIR_WORK: (v) => [`more than ${pow2(v)} units of pair-graph work`],
};
function spaced(v) {
  return String(v).replace(/\B(?=(\d{3})+(?!\d))/g, ' ');
}
// 2^k for a power of two; anything else cannot match the spec's 2^k spelling.
function pow2(v) {
  const k = Math.log2(v);
  return Number.isInteger(k) ? `2^${k}` : String(v);
}

function load() {
  const doc = JSON.parse(readFileSync(resolve(ROOT, SOURCE), 'utf8'));
  // Line breaks (and the indentation of a wrapped list item) are folded to one
  // space, so a statement may wrap; table rows and sentences already use one.
  const spec = readFileSync(resolve(ROOT, 'spec/SPEC.md'), 'utf8').replace(/[ \t]*\n[ \t]*/g, ' ');
  const errors = readFileSync(resolve(ROOT, 'spec/errors.md'), 'utf8');

  const limits = [];
  for (const [name, e] of Object.entries(doc.limits || {})) {
    if (!/^[A-Z][A-Z0-9_]*$/.test(name)) fail(`${name}: a limit name is upper-case ASCII`);
    for (const k of Object.keys(e)) if (!['value', 'spec', 'meaning'].includes(k)) fail(`${name}.${k}: unknown key`);
    if (!Number.isInteger(e.value) || e.value <= 0) fail(`${name}.value: a positive integer`);
    if (typeof e.spec !== 'string' || !/^§\d+(\.\d+)*$/.test(e.spec)) fail(`${name}.spec: "§n.m"`);
    if (typeof e.meaning !== 'string' || !e.meaning) fail(`${name}.meaning: a sentence`);
    const statements = SPEC_STATEMENTS[name];
    if (!statements) fail(`${name}: no known spec statement to check it against — add one to gen-limits.mjs`);
    for (const s of statements(e.value)) {
      if (!spec.includes(s)) fail(`${name}: spec/SPEC.md no longer states "${s}" — the manifest says ${e.value}`);
    }
    limits.push({ name, value: e.value, spec: e.spec, meaning: e.meaning });
  }
  for (const name of Object.keys(SPEC_STATEMENTS)) if (!limits.some((l) => l.name === name)) fail(`${name}: missing from the manifest`);

  // spec/errors.md: which codes appear under "## Compile time" and "## Run time".
  const phases = new Map();
  let phase = null;
  for (const line of errors.split('\n')) {
    if (line.startsWith('## Compile time')) phase = 'compile';
    else if (line.startsWith('## Run time')) phase = 'run';
    else if (line.startsWith('## ')) phase = null;
    const m = /^\| `(E_[A-Z0-9_]+)` \|/.exec(line);
    if (m && phase) {
      const have = phases.get(m[1]);
      phases.set(m[1], have && have !== phase ? 'both' : phase);
    }
  }
  const codes = [];
  for (const [code, e] of Object.entries(doc.errors || {})) {
    if (!/^E_[A-Z0-9_]+$/.test(code)) fail(`${code}: an error code is E_ and upper-case ASCII`);
    for (const k of Object.keys(e)) if (k !== 'phase') fail(`${code}.${k}: unknown key`);
    if (!['compile', 'run', 'both'].includes(e.phase)) fail(`${code}.phase: compile, run or both`);
    const documented = phases.get(code);
    if (!documented) fail(`${code}: has no row in spec/errors.md`);
    if (documented !== e.phase) fail(`${code}: spec/errors.md lists it as ${documented}, the manifest says ${e.phase}`);
    codes.push({ code, phase: e.phase });
  }
  for (const code of phases.keys()) if (!codes.some((c) => c.code === code)) fail(`${code}: in spec/errors.md but not in the manifest`);
  return { limits, codes };
}


function renderJs({ limits, codes }) {
  return [`// ${HEADER}`, '',
    ...limits.map((l) => `export const ${l.name} = ${l.value};   // ${l.spec}: ${l.meaning}`),
    '', "// The language's error codes and the phase that raises each: 'compile', 'run' or 'both'.",
    'export const ERROR_CODES = Object.freeze({',
    ...codes.map((c) => `  ${c.code}: ${jsStr(c.phase)},`),
    '});', ''].join('\n');
}
function renderPython({ limits, codes }) {
  return [`# ${HEADER}`, '',
    ...limits.map((l) => `${l.name} = ${l.value}   # ${l.spec}: ${l.meaning}`),
    '', "# The language's error codes and the phase that raises each: 'compile', 'run' or 'both'.",
    'ERROR_CODES = {',
    ...codes.map((c) => `    ${pyStr(c.code)}: ${pyStr(c.phase)},`),
    '}', ''].join('\n');
}
function renderPhp({ limits, codes }) {
  return ['<?php', `// ${HEADER}`, '', 'declare(strict_types=1);', '', 'namespace Sel;', '', 'final class Limits', '{',
    ...limits.map((l) => `    /** ${l.spec}: ${l.meaning} */\n    public const ${l.name} = ${l.value};`),
    '', "    /** The language's error codes and the phase that raises each: 'compile', 'run' or 'both'. @var array<string,string> */",
    '    public const ERROR_CODES = [',
    ...codes.map((c) => `        ${phpStr(c.code)} => ${phpStr(c.phase)},`),
    '    ];', '}', ''].join('\n');
}
function renderCpp({ limits, codes }) {
  return [`// ${HEADER}`, '#pragma once', '', 'namespace sel_limits {', '',
    ...limits.map((l) => `inline constexpr long long ${l.name} = ${l.value};   // ${l.spec}: ${l.meaning}`),
    '', "// The language's error codes and the phase that raises each: 'compile', 'run' or 'both'.",
    'struct ErrorCode { const char* code; const char* phase; };',
    'inline const ErrorCode ERROR_CODES[] = {',
    ...codes.map((c) => `  {"${c.code}", "${c.phase}"},`),
    '};', `inline constexpr int ERROR_CODE_COUNT = ${codes.length};`, '', '}  // namespace sel_limits', ''].join('\n');
}
function renderLisp({ limits, codes }) {
  const kebab = (s) => '+limit-' + s.toLowerCase().replace(/_/g, '-') + '+';
  return [`;;;; ${HEADER}`, '', '(in-package #:sel)', '',
    ...limits.map((l) => `(defconstant ${kebab(l.name)} ${l.value})   ; ${l.spec}: ${l.meaning}`),
    '', ";;; The language's error codes and the phase that raises each: :compile, :run or :both.",
    '(defparameter +error-codes+', "  '(",
    ...codes.map((c) => `    ("${c.code}" :${c.phase})`),
    '))', ''].join('\n');
}
// Go: gofmt's layout, written out (the bytes must not depend on whether gofmt is
// on PATH): the const block's names, values and comments in aligned columns, the
// map's values aligned after the keys, and a doc comment that names its subject.
function renderGo({ limits, codes }) {
  const nameW = Math.max(...limits.map((l) => l.name.length));
  const valueW = Math.max(...limits.map((l) => String(l.value).length));
  const keyW = Math.max(...codes.map((c) => c.code.length + 3));
  return [`// ${HEADER}`, '',
    'package limits', '',
    'const (',
    ...limits.map((l) => `\t${l.name.padEnd(nameW)} = ${String(l.value).padEnd(valueW)} // ${l.spec}: ${l.meaning}`),
    ')', '',
    '// ErrorCodes holds the language\'s error codes and the phase that raises each: "compile", "run" or "both".',
    'var ErrorCodes = map[string]string{',
    ...codes.map((c) => `\t${`"${c.code}":`.padEnd(keyW)} "${c.phase}",`),
    '}', ''].join('\n');
}
function renderRust({ limits, codes }) {
  return [`// ${HEADER}`, '',
    ...limits.map((l) => `pub const ${l.name}: usize = ${l.value}; // ${l.spec}: ${l.meaning}`),
    '',
    "// The language's error codes and the phase that raises each: \"compile\", \"run\" or \"both\".",
    'pub const ERROR_CODES: &[(&str, &str)] = &[',
    ...codes.map((c) => `    ("${c.code}", "${c.phase}"),`),
    '];', ''].join('\n');
}
function renderDocs({ limits, codes }) {
  return [`<!-- ${HEADER} -->`, '# Limits and error codes', '',
    'The normative numbers and error identifiers, from `spec/limits.json`, which',
    '`tools/gen-limits.mjs` checks against `spec/SPEC.md` and `spec/errors.md`',
    'before rendering — the prose there defines them; this page lists them.', '',
    '| Limit | Value | Spec | Meaning |', '|---|---|---|---|',
    ...limits.map((l) => `| \`${l.name}\` | ${l.value.toLocaleString('en-US')} | ${l.spec} | ${l.meaning} |`),
    '', '| Code | Phase |', '|---|---|',
    ...codes.map((c) => `| \`${c.code}\` | ${c.phase === 'both' ? 'compile and run' : c.phase} |`),
    '', `${limits.length} limits, ${codes.length} error codes. The SQL layer's own codes are in \`sql/errors.md\`.`, ''].join('\n');
}

const data = load();
const rendered = { js: renderJs(data), python: renderPython(data), php: renderPhp(data), cpp: renderCpp(data), lisp: renderLisp(data), go: renderGo(data), rust: renderRust(data), docs: renderDocs(data) };
writeOrCheck('gen-limits', ROOT, Object.entries(OUTPUTS).map(([host, path]) => [path, rendered[host]]),
  { check, rerun: 'node tools/gen-limits.mjs' });
if (check) process.stdout.write(`gen-limits: ${data.limits.length} limits and ${data.codes.length} error codes agree with the spec; ${Object.keys(OUTPUTS).length} renderings current\n`);
