#!/usr/bin/env node
// Renders spec/limits.json — the normative limits and error catalogue — into
// every host's constants and into docs/LIMITS.md, after checking that the spec
// text still states every fact in it.
//
//     node tools/gen-limits.mjs            write the generated files
//     node tools/gen-limits.mjs --check    validate and diff, write nothing
//
// The renderings ARE committed (see tools/gen-builtins.mjs for why). The
// manifest is deliberately NOT an authority: spec/SPEC.md and spec/errors.md
// are, and this generator fails when the manifest says something they do not.

import { readFileSync, writeFileSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import { dirname, resolve } from 'node:path';

const ROOT = resolve(dirname(fileURLToPath(import.meta.url)), '..');
const SOURCE = 'spec/limits.json';
const OUTPUTS = {
  js: 'js/src/_limits.mjs',
  python: 'python/sel/_limits.py',
  php: 'php/src/Limits.php',
  cpp: 'cpp/sel_limits.hpp',
  lisp: 'lisp/src/limits.lisp',
  docs: 'docs/LIMITS.md',
};
const HEADER = `GENERATED by tools/gen-limits.mjs from ${SOURCE} — do not edit; edit the manifest and regenerate.`;

function fail(msg) {
  process.stderr.write(`gen-limits: ${msg}\n`);
  process.exit(1);
}

// The spec's own statements of each number, as written there. A limit is
// accepted only if its sentence is found.
const SPEC_STATEMENTS = {
  MAX_DEPTH: (v) => [`at least ${v})`],
  MAX_INT_DIGITS: (v) => [`| integer digits of a number | ${String(v).replace(/\B(?=(\d{3})+(?!\d))/g, ' ')} |`],
  MAX_FRAC_DIGITS: (v) => [`| fractional digits of a number | ${String(v).replace(/\B(?=(\d{3})+(?!\d))/g, ' ')} |`],
  DIV_SCALE: (v) => ['`DIV_SCALE` is **' + v + '**'],
};

function load() {
  const doc = JSON.parse(readFileSync(resolve(ROOT, SOURCE), 'utf8'));
  const spec = readFileSync(resolve(ROOT, 'spec/SPEC.md'), 'utf8');
  const errors = readFileSync(resolve(ROOT, 'spec/errors.md'), 'utf8');

  const limits = [];
  for (const [name, e] of Object.entries(doc.limits || {})) {
    if (!/^[A-Z][A-Z0-9_]*$/.test(name)) fail(`${name}: a limit name is upper-case ASCII`);
    for (const k of Object.keys(e)) if (!['value', 'spec', 'meaning'].includes(k)) fail(`${name}.${k}: unknown key`);
    if (!Number.isInteger(e.value) || e.value <= 0) fail(`${name}.value: a positive integer`);
    if (typeof e.spec !== 'string' || !/^§\d+(\.\d+)*$/.test(e.spec)) fail(`${name}.spec: "§n.m"`);
    if (typeof e.meaning !== 'string' || !e.meaning) fail(`${name}.meaning: a sentence`);
    const statements = SPEC_STATEMENTS[name];
    if (!statements) fail(`${name}: no known spec statement to check it against — add one to gen-limits.mjs`);
    for (const s of statements(e.value)) {
      if (!spec.includes(s)) fail(`${name}: spec/SPEC.md no longer states "${s}" — the manifest says ${e.value}`);
    }
    limits.push({ name, value: e.value, spec: e.spec, meaning: e.meaning });
  }
  for (const name of Object.keys(SPEC_STATEMENTS)) if (!limits.some((l) => l.name === name)) fail(`${name}: missing from the manifest`);

  // spec/errors.md: which codes appear under "## Compile time" and "## Run time".
  const phases = new Map();
  let phase = null;
  for (const line of errors.split('\n')) {
    if (line.startsWith('## Compile time')) phase = 'compile';
    else if (line.startsWith('## Run time')) phase = 'run';
    else if (line.startsWith('## ')) phase = null;
    const m = /^\| `(E_[A-Z0-9_]+)` \|/.exec(line);
    if (m && phase) {
      const have = phases.get(m[1]);
      phases.set(m[1], have && have !== phase ? 'both' : phase);
    }
  }
  const codes = [];
  for (const [code, e] of Object.entries(doc.errors || {})) {
    if (!/^E_[A-Z0-9_]+$/.test(code)) fail(`${code}: an error code is E_ and upper-case ASCII`);
    for (const k of Object.keys(e)) if (k !== 'phase') fail(`${code}.${k}: unknown key`);
    if (!['compile', 'run', 'both'].includes(e.phase)) fail(`${code}.phase: compile, run or both`);
    const documented = phases.get(code);
    if (!documented) fail(`${code}: has no row in spec/errors.md`);
    if (documented !== e.phase) fail(`${code}: spec/errors.md lists it as ${documented}, the manifest says ${e.phase}`);
    codes.push({ code, phase: e.phase });
  }
  for (const code of phases.keys()) if (!codes.some((c) => c.code === code)) fail(`${code}: in spec/errors.md but not in the manifest`);
  return { limits, codes };
}

const jsStr = JSON.stringify;
const pyStr = (s) => "'" + s + "'";

function renderJs({ limits, codes }) {
  return [`// ${HEADER}`, '',
    ...limits.map((l) => `export const ${l.name} = ${l.value};   // ${l.spec}: ${l.meaning}`),
    '', "// The language's error codes and the phase that raises each: 'compile', 'run' or 'both'.",
    'export const ERROR_CODES = Object.freeze({',
    ...codes.map((c) => `  ${c.code}: ${jsStr(c.phase)},`),
    '});', ''].join('\n');
}
function renderPython({ limits, codes }) {
  return [`# ${HEADER}`, '',
    ...limits.map((l) => `${l.name} = ${l.value}   # ${l.spec}: ${l.meaning}`),
    '', "# The language's error codes and the phase that raises each: 'compile', 'run' or 'both'.",
    'ERROR_CODES = {',
    ...codes.map((c) => `    ${pyStr(c.code)}: ${pyStr(c.phase)},`),
    '}', ''].join('\n');
}
function renderPhp({ limits, codes }) {
  return ['<?php', `// ${HEADER}`, '', 'declare(strict_types=1);', '', 'namespace Sel;', '', 'final class Limits', '{',
    ...limits.map((l) => `    /** ${l.spec}: ${l.meaning} */\n    public const ${l.name} = ${l.value};`),
    '', "    /** The language's error codes and the phase that raises each: 'compile', 'run' or 'both'. @var array<string,string> */",
    '    public const ERROR_CODES = [',
    ...codes.map((c) => `        ${pyStr(c.code)} => ${pyStr(c.phase)},`),
    '    ];', '}', ''].join('\n');
}
function renderCpp({ limits, codes }) {
  return [`// ${HEADER}`, '#pragma once', '', 'namespace sel_limits {', '',
    ...limits.map((l) => `inline constexpr long long ${l.name} = ${l.value};   // ${l.spec}: ${l.meaning}`),
    '', "// The language's error codes and the phase that raises each: 'compile', 'run' or 'both'.",
    'struct ErrorCode { const char* code; const char* phase; };',
    'inline const ErrorCode ERROR_CODES[] = {',
    ...codes.map((c) => `  {"${c.code}", "${c.phase}"},`),
    '};', `inline constexpr int ERROR_CODE_COUNT = ${codes.length};`, '', '}  // namespace sel_limits', ''].join('\n');
}
function renderLisp({ limits, codes }) {
  const kebab = (s) => '+limit-' + s.toLowerCase().replace(/_/g, '-') + '+';
  return [`;;;; ${HEADER}`, '', '(in-package #:sel)', '',
    ...limits.map((l) => `(defconstant ${kebab(l.name)} ${l.value})   ; ${l.spec}: ${l.meaning}`),
    '', ";;; The language's error codes and the phase that raises each: :compile, :run or :both.",
    '(defparameter +error-codes+', "  '(",
    ...codes.map((c) => `    ("${c.code}" :${c.phase})`),
    '))', ''].join('\n');
}
function renderDocs({ limits, codes }) {
  return [`<!-- ${HEADER} -->`, '# Limits and error codes', '',
    'The normative numbers and error identifiers, from `spec/limits.json`, which',
    '`tools/gen-limits.mjs` checks against `spec/SPEC.md` and `spec/errors.md`',
    'before rendering — the prose there defines them; this page lists them.', '',
    '| Limit | Value | Spec | Meaning |', '|---|---|---|---|',
    ...limits.map((l) => `| \`${l.name}\` | ${l.value.toLocaleString('en-US')} | ${l.spec} | ${l.meaning} |`),
    '', '| Code | Phase |', '|---|---|',
    ...codes.map((c) => `| \`${c.code}\` | ${c.phase === 'both' ? 'compile and run' : c.phase} |`),
    '', `${limits.length} limits, ${codes.length} error codes. The SQL layer's own codes are in \`sql/errors.md\`.`, ''].join('\n');
}

const data = load();
const rendered = { js: renderJs(data), python: renderPython(data), php: renderPhp(data), cpp: renderCpp(data), lisp: renderLisp(data), docs: renderDocs(data) };
if (process.argv.includes('--check')) {
  let stale = 0;
  for (const [host, path] of Object.entries(OUTPUTS)) {
    let current = null;
    try { current = readFileSync(resolve(ROOT, path), 'utf8'); } catch { /* missing */ }
    if (current !== rendered[host]) { process.stderr.write(`gen-limits: ${path} is ${current === null ? 'missing' : 'stale'}\n`); stale++; }
  }
  if (stale) process.exit(1);
  process.stdout.write(`gen-limits: ${data.limits.length} limits and ${data.codes.length} error codes agree with the spec; ${Object.keys(OUTPUTS).length} renderings current\n`);
} else {
  for (const [host, path] of Object.entries(OUTPUTS)) {
    writeFileSync(resolve(ROOT, path), rendered[host]);
    process.stdout.write(`wrote ${path}\n`);
  }
}
