# GENERATED by tools/gen-lexicon.mjs from spec/lexicon.json — do not edit; edit the lexicon and regenerate.
#
# RESERVED: the reserved words. SYMBOLS: every symbol token, longest first.
# BP: each precedence level's binding power (higher binds tighter). OPS: one
# Op per operator, tightest level first; see spec/lexicon.md for the fields.
# relation indexes RELATIONS (-1 when none); assoc is 'L', 'R', 'N' or None.

from typing import NamedTuple, Optional


class Op(NamedTuple):
    token: str
    word: bool
    fixity: str
    level: str
    bp: int
    assoc: Optional[str]
    family: str
    node: str
    name: Optional[str]
    relation: int
    compound: Optional[str]
    short_circuit: bool


RESERVED = ("TRUE", "FALSE", "NULL", "AND", "OR", "NOT", "XOR", "EQL", "IN", "BAND", "BOR", "BXOR")

SYMBOLS = ("???", "$==", "$!=", "$<=", "$>=", ".>", "??", "==", "!=", "<=", ">=", "$<", "$>", "+=", "-=", "*=", "/=", "%=", "&=", "[", "-", "*", "/", "%", "+", "&", "<", ">", "=", ",", ";", "(", ")", "]")

RELATIONS = ("eq", "ne", "lt", "le", "gt", "ge")

BP = {
    "POSTFIX": 17,
    "NEG": 16,
    "MUL": 15,
    "ADD": 14,
    "CONCAT": 13,
    "BAND": 12,
    "BXOR": 11,
    "BOR": 10,
    "COALESCE": 9,
    "COMPARE": 8,
    "NOT": 7,
    "AND": 6,
    "XOR": 5,
    "OR": 4,
    "ASSIGN": 3,
    "LIST": 2,
    "SEQ": 1,
}

OPS = (
    Op("[", False, "postfix", "POSTFIX", 17, None, "postfix", "index", None, -1, None, False),
    Op(".>", False, "postfix", "POSTFIX", 17, None, "postfix", "pipe", None, -1, None, False),
    Op("-", False, "prefix", "NEG", 16, None, "arith", "un", "NEG", -1, None, False),
    Op("*", False, "infix", "MUL", 15, "L", "arith", "bin", None, -1, None, False),
    Op("/", False, "infix", "MUL", 15, "L", "arith", "bin", None, -1, None, False),
    Op("%", False, "infix", "MUL", 15, "L", "arith", "bin", None, -1, None, False),
    Op("+", False, "infix", "ADD", 14, "L", "arith", "bin", None, -1, None, False),
    Op("-", False, "infix", "ADD", 14, "L", "arith", "bin", None, -1, None, False),
    Op("&", False, "infix", "CONCAT", 13, "L", "concat", "bin", None, -1, None, False),
    Op("BAND", True, "infix", "BAND", 12, "L", "bitwise", "bin", None, -1, None, False),
    Op("BXOR", True, "infix", "BXOR", 11, "L", "bitwise", "bin", None, -1, None, False),
    Op("BOR", True, "infix", "BOR", 10, "L", "bitwise", "bin", None, -1, None, False),
    Op("??", False, "infix", "COALESCE", 9, "R", "coalesce", "bin", None, -1, None, True),
    Op("???", False, "infix", "COALESCE", 9, "R", "coalesce", "bin", None, -1, None, True),
    Op("==", False, "infix", "COMPARE", 8, "N", "compare", "bin", None, 0, None, False),
    Op("!=", False, "infix", "COMPARE", 8, "N", "compare", "bin", None, 1, None, False),
    Op("<", False, "infix", "COMPARE", 8, "N", "compare", "bin", None, 2, None, False),
    Op("<=", False, "infix", "COMPARE", 8, "N", "compare", "bin", None, 3, None, False),
    Op(">", False, "infix", "COMPARE", 8, "N", "compare", "bin", None, 4, None, False),
    Op(">=", False, "infix", "COMPARE", 8, "N", "compare", "bin", None, 5, None, False),
    Op("$==", False, "infix", "COMPARE", 8, "N", "text-compare", "bin", None, 0, None, False),
    Op("$!=", False, "infix", "COMPARE", 8, "N", "text-compare", "bin", None, 1, None, False),
    Op("$<", False, "infix", "COMPARE", 8, "N", "text-compare", "bin", None, 2, None, False),
    Op("$<=", False, "infix", "COMPARE", 8, "N", "text-compare", "bin", None, 3, None, False),
    Op("$>", False, "infix", "COMPARE", 8, "N", "text-compare", "bin", None, 4, None, False),
    Op("$>=", False, "infix", "COMPARE", 8, "N", "text-compare", "bin", None, 5, None, False),
    Op("EQL", True, "infix", "COMPARE", 8, "N", "deep-compare", "bin", None, -1, None, False),
    Op("IN", True, "infix", "COMPARE", 8, "N", "deep-compare", "bin", None, -1, None, False),
    Op("NOT", True, "prefix", "NOT", 7, None, "logic", "un", "NOT", -1, None, False),
    Op("AND", True, "infix", "AND", 6, "L", "logic", "bin", None, -1, None, True),
    Op("XOR", True, "infix", "XOR", 5, "L", "logic", "bin", None, -1, None, False),
    Op("OR", True, "infix", "OR", 4, "L", "logic", "bin", None, -1, None, True),
    Op("=", False, "infix", "ASSIGN", 3, "R", "assign", "assign", None, -1, None, False),
    Op("+=", False, "infix", "ASSIGN", 3, "R", "assign", "assign", None, -1, "+", False),
    Op("-=", False, "infix", "ASSIGN", 3, "R", "assign", "assign", None, -1, "-", False),
    Op("*=", False, "infix", "ASSIGN", 3, "R", "assign", "assign", None, -1, "*", False),
    Op("/=", False, "infix", "ASSIGN", 3, "R", "assign", "assign", None, -1, "/", False),
    Op("%=", False, "infix", "ASSIGN", 3, "R", "assign", "assign", None, -1, "%", False),
    Op("&=", False, "infix", "ASSIGN", 3, "R", "assign", "assign", None, -1, "&", False),
    Op(",", False, "infix", "LIST", 2, "L", "list", "list", None, -1, None, False),
    Op(";", False, "infix", "SEQ", 1, "L", "sequence", "seq", None, -1, None, False),
)
