# GENERATED by tools/gen-math-ops.mjs from spec/math-ops.json — do not edit; edit the manifest and regenerate.
#
# What the math plan compiles: MATH_OPERATORS maps a binary operator token and
# MATH_PREFIX a prefix operator name to a symbolic operation; MATH_BUILTINS
# maps a builtin name to (op, arity 1 | 2 | 'fold', aux). MATH_OPS lists every
# operation; math_plan.py maps each to its own OpCode and refuses to import if
# one is missing.

MATH_OPERATORS = {
    '+': 'ADD',
    '-': 'SUB',
    '*': 'MUL',
    '/': 'DIV',
    '%': 'MOD',
}

MATH_PREFIX = {
    'NEG': 'NEG',
}

MATH_BUILTINS = {
    'ABS': ('ABS', 1, None),
    'SIGN': ('SIGN', 1, None),
    'CEIL': ('CEIL', 1, None),
    'FLOOR': ('FLOOR', 1, None),
    'TRUNC': ('TRUNC', 1, None),
    'ROUND': ('ROUND', 2, 1),
    'POWER': ('POWER', 2, 1),
    'MIN': ('MIN', 'fold', None),
    'MAX': ('MAX', 'fold', None),
}

MATH_OPS = ('ADD', 'SUB', 'MUL', 'DIV', 'MOD', 'NEG', 'ABS', 'SIGN', 'CEIL', 'FLOOR', 'TRUNC', 'ROUND', 'POWER', 'MIN', 'MAX')
