#!/usr/bin/env python3
"""Read-only lexical triage; candidates require manual reachability/API review."""
import ast, collections, hashlib, json, pathlib, re, subprocess
ROOT=pathlib.Path(__file__).resolve().parents[2]
lanes={'python':list(ROOT.glob('python/sel/**/*.py')), 'javascript':list(ROOT.glob('js/src/**/*.mjs')),
       'php':list(ROOT.glob('php/src/**/*.php')), 'lisp':list(ROOT.glob('lisp/src/**/*.lisp')),
       'cpp':[p for p in ROOT.glob('cpp/sel*') if p.suffix in ('.cpp','.hpp')]}
patterns={'javascript':r'(?:export\s+)?function\s+(\w+)\s*\(', 'php':r'(?:private|protected)\s+(?:static\s+)?function\s+(\w+)\s*\(',
'lisp':r'\(defun\s+([^\s()]+)', 'cpp':r'^(?:\[\[maybe_unused\]\]\s+)?(?:static\s+)?[\w:<>,*& ]+\s+(\w+)\s*\([^;\n]*\)\s*\{'}
report={'revision':subprocess.check_output(['git','rev-parse','HEAD'],cwd=ROOT,text=True).strip(),
        'method':'lexical single-reference declarations; Python AST imports; exact normalized eight-line windows. No reachability proof.', 'lanes':{}}
for lane,files in lanes.items():
 files=sorted(files);texts={str(p.relative_to(ROOT)):p.read_text() for p in files}
 corpus='\n'.join(texts.values());tokens=collections.Counter(x.lstrip("#':") for x in re.findall(r"[A-Za-z_][A-Za-z_0-9!?*+<>/=-]*",corpus)) if lane=='lisp' else collections.Counter(re.findall(r'[A-Za-z_][A-Za-z_0-9]*',corpus))
 generated=[f for f,t in texts.items() if re.search(r'GENERATED by|AUTO-GENERATED', '\n'.join(t.splitlines()[:8]),re.I)]
 candidates=[];imports=[];windows=collections.defaultdict(list)
 for f,t in texts.items():
  if f in generated:continue
  if lane=='python':
   tree=ast.parse(t);decls=[(n.name,n.lineno) for n in ast.walk(tree) if isinstance(n,(ast.FunctionDef,ast.AsyncFunctionDef))]
   used={n.id for n in ast.walk(tree) if isinstance(n,ast.Name)}
   for n in ast.walk(tree):
    if isinstance(n,(ast.Import,ast.ImportFrom)) and getattr(n,'module',None)!='__future__':
     for a in n.names:
      bound=a.asname or a.name.split('.')[0]
      if bound not in used:imports.append(dict(file=f,line=n.lineno,name=bound))
  else:
   decls=[(m.group(1),t.count('\n',0,m.start())+1) for m in re.finditer(patterns[lane],t,re.M)]
  for name,line in decls:
   if tokens[name]==1:candidates.append(dict(file=f,line=line,name=name))
  lines=[(i,re.sub(r'\s+',' ',x.strip())) for i,x in enumerate(t.splitlines(),1) if x.strip() and not x.lstrip().startswith(('//','#',';','/*','*'))]
  for i in range(len(lines)-7):
   block='\n'.join(x[1] for x in lines[i:i+8])
   if len(block)>=220:windows[block].append((f,lines[i][0]))
 clones=[];covered=set()
 for block,locs in windows.items():
  if len(locs)<2:continue
  if all((f,line-1) in covered or (f,line) in covered for f,line in locs):continue
  clones.append(dict(locations=[dict(file=f,line=line) for f,line in locs],sample=block))
  for f,line in locs:
   for k in range(line,line+12):covered.add((f,k))
 report['lanes'][lane]=dict(files=len(files),lines=sum(len(t.splitlines()) for t in texts.values()),generated_excluded=generated,
       single_reference_declarations=candidates,unused_import_candidates=imports,duplicate_windows=clones,
       source_sha256={f:hashlib.sha256(t.encode()).hexdigest() for f,t in texts.items()})
out=ROOT/'tools/code-scan/results/scan.json';out.write_text(json.dumps(report,indent=2)+'\n')
for lane,d in report['lanes'].items():
 print(lane,d['files'],'files',len(d['single_reference_declarations']),'single-reference declarations',len(d['unused_import_candidates']),'import candidates',len(d['duplicate_windows']),'clone groups')
